export const attributes = [
  {
    dn: "inum=98FC,ou=attributes,o=jans",
    selected: false,
    inum: "98FC",
    name: "birthdate",
    displayName: "Birthdate",
    description:
      "End-User's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "birthdate",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:birthdate",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.326",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/birthdate",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=98FC,ou=attributes,o=jans"
  },
  {
    dn: "inum=6EEB,ou=attributes,o=jans",
    selected: false,
    inum: "6EEB",
    name: "l",
    displayName: "City",
    description: "City",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "locality",
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:l",
    saml2Uri: "urn:oid:2.5.4.7",
    urn: "urn:mace:dir:attribute-def:l",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=6EEB,ou=attributes,o=jans"
  },
  {
    dn: "inum=BCE8,ou=attributes,o=jans",
    selected: false,
    inum: "BCE8",
    name: "c",
    displayName: "Country",
    description: "Country",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "country",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:c",
    saml2Uri: "urn:oid:2.5.4.6",
    urn: "urn:jans:dir:attribute-def:c",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=BCE8,ou=attributes,o=jans"
  },
  {
    dn: "inum=08E2,ou=attributes,o=jans",
    selected: false,
    inum: "08E2",
    name: "departmentNumber",
    displayName: "Department",
    description: "Organizational Department",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:departmentNumber",
    saml2Uri: "urn:oid:2.16.840.1.113730.3.1.2",
    urn: "urn:mace:dir:attribute-def:departmentNumber",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=08E2,ou=attributes,o=jans"
  },
  {
    dn: "inum=2B29,ou=attributes,o=jans",
    selected: false,
    inum: "2B29",
    name: "displayName",
    displayName: "Display Name",
    description:
      "End-User's full name in displayable formincluding all name parts, possibly including titles andsuffixes, ordered according to the End-User's locale and preferences.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "name",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:displayName",
    saml2Uri: "urn:oid:2.16.840.1.113730.3.1.241",
    urn: "urn:mace:dir:attribute-def:displayName",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=2B29,ou=attributes,o=jans"
  },
  {
    dn: "inum=CAE3,ou=attributes,o=jans",
    selected: false,
    inum: "CAE3",
    name: "mail",
    displayName: "Email",
    description: "Primary Email Address",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "email",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:mail",
    saml2Uri: "urn:oid:0.9.2342.19200300.100.1.3",
    urn: "urn:mace:dir:attribute-def:mail",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=CAE3,ou=attributes,o=jans"
  },
  {
    dn: "inum=8F88,ou=attributes,o=jans",
    selected: false,
    inum: "8F88",
    name: "emailVerified",
    displayName: "Email Verified",
    description:
      "True if the End-User's e-mail address has been verified; otherwise false",
    origin: "jansPerson",
    dataType: "BOOLEAN",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "email_verified",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:emailVerified",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.324",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/email_verified",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=8F88,ou=attributes,o=jans"
  },
  {
    dn: "inum=D0C9,ou=attributes,o=jans",
    selected: false,
    inum: "D0C9",
    name: "employeeNumber",
    displayName: "Employee Number",
    description: "Employee Number",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:employeeNumber",
    saml2Uri: "urn:oid:2.16.840.1.113730.3.1.3",
    urn: "urn:mace:dir:attribute-def:employeeNumber",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: false,
    userCanView: false,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=D0C9,ou=attributes,o=jans"
  },
  {
    dn: "inum=3D44,ou=attributes,o=jans",
    selected: false,
    inum: "3D44",
    name: "employeeType",
    displayName: "Employee Type",
    description: "Employee Type",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:employeeType",
    saml2Uri: "urn:oid:2.16.840.1.113730.3.1.4",
    urn: "urn:mace:dir:attribute-def:employeeType",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: false,
    userCanView: false,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=3D44,ou=attributes,o=jans"
  },
  {
    dn: "inum=BD22,ou=attributes,o=jans",
    selected: false,
    inum: "BD22",
    name: "facsimileTelephoneNumber",
    displayName: "Fax Number",
    description: "Fax Telephone Number",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:facsimileTelephoneNumber",
    saml2Uri: "urn:oid:2.5.4.23",
    urn: "urn:mace:dir:attribute-def:facsimileTelephoneNumber",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=BD22,ou=attributes,o=jans"
  },
  {
    dn: "inum=B4B0,ou=attributes,o=jans",
    selected: false,
    inum: "B4B0",
    name: "givenName",
    displayName: "First Name",
    description:
      "Given name(s) or first name(s) of the End-User.Note that in some cultures, people can have multiple given names;all can be present, with the names being separated by space characters.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "given_name",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:givenName",
    saml2Uri: "urn:oid:2.5.4.42",
    urn: "urn:mace:dir:attribute-def:givenName",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=B4B0,ou=attributes,o=jans"
  },
  {
    dn: "inum=3692,ou=attributes,o=jans",
    selected: false,
    inum: "3692",
    name: "gender",
    displayName: "Gender, male or female",
    description: "Gender of the person, either male or female",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "gender",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:gender",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.325",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/gender",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=3692,ou=attributes,o=jans"
  },
  {
    dn: "inum=27DB,ou=attributes,o=jans",
    selected: false,
    inum: "27DB",
    name: "homePostalAddress",
    displayName: "Home Address",
    description: "Home Address",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "formatted",
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:homePostalAddress",
    saml2Uri: "urn:oid:0.9.2342.19200300.100.1.39",
    urn: "urn:mace:dir:attribute-def:homePostalAddress",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=27DB,ou=attributes,o=jans"
  },
  {
    dn: "inum=0C18,ou=attributes,o=jans",
    selected: false,
    inum: "0C18",
    name: "telephoneNumber",
    displayName: "Home Telephone Number",
    description: "Home Telephone Number",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "phone_number",
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:telephoneNumber",
    saml2Uri: "urn:oid:2.5.4.20",
    urn: "urn:mace:dir:attribute-def:phone_number",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=0C18,ou=attributes,o=jans"
  },
  {
    dn: "inum=29DA,ou=attributes,o=jans",
    selected: false,
    inum: "29DA",
    name: "inum",
    displayName: "Inum",
    description: "XRI i-number, persistent non-reassignable identifier",
    origin: "jansPerson",
    dataType: "STRING",
    viewType: ["USER", "ADMIN"],
    claimName: "inum",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:inum",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.117",
    urn: "urn:jans:dir:attribute-def:inum",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: false,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=29DA,ou=attributes,o=jans"
  },
  {
    dn: "inum=0C85,ou=attributes,o=jans",
    selected: false,
    inum: "0C85",
    name: "sn",
    displayName: "Last Name",
    description: "Last Name",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "family_name",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:sn",
    saml2Uri: "urn:oid:2.5.4.4",
    urn: "urn:mace:dir:attribute-def:sn",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=0C85,ou=attributes,o=jans"
  },
  {
    dn: "inum=BE64,ou=attributes,o=jans",
    selected: false,
    inum: "BE64",
    name: "updatedAt",
    displayName: "Last Updated",
    description:
      "Time the End-User's information was last updated. Its value isaJSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured inUTC until the date/time.",
    origin: "jansPerson",
    dataType: "DATE",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "updated_at",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:updatedAt",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.331",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/address",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=BE64,ou=attributes,o=jans"
  },
  {
    dn: "inum=4502,ou=attributes,o=jans",
    selected: false,
    inum: "4502",
    name: "carLicense",
    displayName: "License Plate",
    description: "Vehicle License Plate Number",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:carLicense",
    saml2Uri: "urn:oid:2.16.840.1.113730.3.1.1",
    urn: "urn:mace:dir:attribute-def:carLicense",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=4502,ou=attributes,o=jans"
  },
  {
    dn: "inum=36D9,ou=attributes,o=jans",
    selected: false,
    inum: "36D9",
    name: "locale",
    displayName: "Locale",
    description:
      "End-User's locale, represented as a BCP47 (RFC5646) language tag. This is typically anISO 639-1 Alpha-2 [ISO639‑1] language code in lowercase and an ISO 3166-1 Alpha-2country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note,some implementations have used an underscore as the separator rather than a dash, for example, en_US;Relying Parties MAY choose to accept this locale syntax as well.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "locale",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:locale",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.328",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/locale",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=36D9,ou=attributes,o=jans"
  },
  {
    dn: "inum=42D8,ou=attributes,o=jans",
    selected: false,
    inum: "42D8",
    name: "manager",
    displayName: "Manager",
    description: "Manager",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:manager",
    saml2Uri: "urn:oid:0.9.2342.19200300.100.1.10",
    urn: "urn:mace:dir:attribute-def:manager",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: false,
    userCanView: false,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=42D8,ou=attributes,o=jans"
  },
  {
    dn: "inum=D2E0,ou=attributes,o=jans",
    selected: false,
    inum: "D2E0",
    name: "memberOf",
    displayName: "memberOf",
    description: "memberOf",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN"],
    claimName: "member_of",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:memberOf",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.121",
    urn: "urn:jans:dir:attribute-def:memberOf",
    oxMultiValuedAttribute: true,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: false,
    userCanView: false,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=D2E0,ou=attributes,o=jans"
  },
  {
    dn: "inum=A0E8,ou=attributes,o=jans",
    selected: false,
    inum: "A0E8",
    name: "middleName",
    displayName: "Middle Name",
    description:
      "Middle name(s) of the End-User. Note that in some cultures,people can have multiple middle names; all can be present, with the namesbeingseparated by space characters. Also note that in some cultures,middle names are not used.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "middle_name",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:middleName",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.318",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/middle_username",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=A0E8,ou=attributes,o=jans"
  },
  {
    dn: "inum=6DA6,ou=attributes,o=jans",
    selected: false,
    inum: "6DA6",
    name: "mobile",
    displayName: "Mobile Telephone Number",
    description: "Mobile Telephone Number",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "phone_mobile_number",
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:mobile",
    saml2Uri: "urn:oid:0.9.2342.19200300.100.1.41",
    urn: "urn:mace:dir:attribute-def:mobile",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=6DA6,ou=attributes,o=jans"
  },
  {
    dn: "inum=D054,ou=attributes,o=jans",
    selected: false,
    inum: "D054",
    name: "cn",
    displayName: "Name search keywords",
    description: "Name search keywords",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:cn",
    saml2Uri: "urn:oid:2.5.4.3",
    urn: "urn:mace:dir:attribute-def:cn",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=D054,ou=attributes,o=jans"
  },
  {
    dn: "inum=5EC6,ou=attributes,o=jans",
    selected: false,
    inum: "5EC6",
    name: "nickname",
    displayName: "Nickname",
    description:
      "Casual name of the End-User that may or may not be the same asthe given_name.For instance, a nickname value of Mike might be returned alongside a given_name value of Michael.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "nickname",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:nickname",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.319",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/nickname",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=5EC6,ou=attributes,o=jans"
  },
  {
    dn: "inum=C8D5,ou=attributes,o=jans",
    selected: false,
    inum: "C8D5",
    name: "address",
    displayName: "OpenID Connect JSON formatted address",
    description:
      "End-User's preferred postal address. The value of the address member is aJSON [RFC4627] structure containing some or all of the members defined inOpenID Connect 1.0 Core Standard Section 5.1.1",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "address",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:address",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.330",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/address",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=C8D5,ou=attributes,o=jans"
  },
  {
    dn: "inum=D03E,ou=attributes,o=jans",
    selected: false,
    inum: "D03E",
    name: "o",
    displayName: "Organization",
    description: "Organization",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN"],
    claimName: "o",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:o",
    saml2Uri: "urn:oid:2.5.4.10",
    urn: "urn:mace:dir:attribute-def:o",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: false,
    userCanView: false,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=D03E,ou=attributes,o=jans"
  },
  {
    dn: "inum=AAEE,ou=attributes,o=jans",
    selected: false,
    inum: "AAEE",
    name: "userPassword",
    displayName: "Password",
    description: "User secret string",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:userPassword",
    saml2Uri: "urn:oid:2.5.4.35",
    urn: "urn:jans:dir:attribute-def:userPassword",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=AAEE,ou=attributes,o=jans"
  },
  {
    dn: "inum=BCB8,ou=attributes,o=jans",
    selected: false,
    inum: "BCB8",
    name: "persistentId",
    displayName: "PersistentId",
    description: "PersistentId",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:persistentId",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.291",
    urn: "mace:shibboleth:1.0:nameIdentifier",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=BCB8,ou=attributes,o=jans"
  },
  {
    dn: "inum=B17A,ou=attributes,o=jans",
    selected: false,
    inum: "B17A",
    name: "phoneNumberVerified",
    displayName: "Phone Number Verified",
    description:
      "True if the End-User's phone number has been verified; otherwise false",
    origin: "jansPerson",
    dataType: "BOOLEAN",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "phone_number_verified",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:phoneNumberVerified",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.329",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/phone_number_verified",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=B17A,ou=attributes,o=jans"
  },
  {
    dn: "inum=EC3A,ou=attributes,o=jans",
    selected: false,
    inum: "EC3A",
    name: "picture",
    displayName: "Picture URL",
    description: "URL of the End-User's profile picture",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "picture",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:picture",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.322",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/picture",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=EC3A,ou=attributes,o=jans"
  },
  {
    dn: "inum=E999,ou=attributes,o=jans",
    selected: false,
    inum: "E999",
    name: "postOfficeBox",
    displayName: "PO Box",
    description: "Postal Box",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:postOfficeBox",
    saml2Uri: "urn:oid:2.5.4.18",
    urn: "urn:mace:dir:attribute-def:postOfficeBox",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=E999,ou=attributes,o=jans"
  },
  {
    dn: "inum=2A3D,ou=attributes,o=jans",
    selected: false,
    inum: "2A3D",
    name: "postalCode",
    displayName: "Postal Code",
    description: "Postal or Zip Code",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "postal_code",
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:postalCode",
    saml2Uri: "urn:oid:2.5.4.17",
    urn: "urn:mace:dir:attribute-def:postalCode",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=2A3D,ou=attributes,o=jans"
  },
  {
    dn: "inum=894A,ou=attributes,o=jans",
    selected: false,
    inum: "894A",
    name: "preferredDeliveryMethod",
    displayName: "Preferred Delivery Method",
    description: "Preferred Delivery Method",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:preferredDeliveryMethod",
    saml2Uri: "urn:oid:2.5.4.28",
    urn: "urn:jans:dir:attribute-def:preferredDeliveryMethod",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: false,
    userCanView: false,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=894A,ou=attributes,o=jans"
  },
  {
    dn: "inum=6493,ou=attributes,o=jans",
    selected: false,
    inum: "6493",
    name: "preferredLanguage",
    displayName: "Preferred Language",
    description: "Preferred Language",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN", "WHITEPAGES"],
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:preferredLanguage",
    saml2Uri: "urn:oid:2.16.840.1.113730.3.1.39",
    urn: "urn:mace:dir:attribute-def:preferredLanguage",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: true,
    userCanEdit: true,
    baseDn: "inum=6493,ou=attributes,o=jans"
  },
  {
    dn: "inum=B52A,ou=attributes,o=jans",
    selected: false,
    inum: "B52A",
    name: "jansPrefUsrName",
    displayName: "Preferred Username",
    description:
      "A domain issued and managed identifier for the person.Subject - Identifier for the End-User at the Issuer.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "preferred_username",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:preferredUsername",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.320",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/preferred_username",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=B52A,ou=attributes,o=jans"
  },
  {
    dn: "inum=64A0,ou=attributes,o=jans",
    selected: false,
    inum: "64A0",
    name: "profile",
    displayName: "Profile URL",
    description:
      "URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "profile",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:profile",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.321",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/profile",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=64A0,ou=attributes,o=jans"
  },
  {
    dn: "inum=D90B,ou=attributes,o=jans",
    selected: false,
    inum: "D90B",
    name: "roomNumber",
    displayName: "Room Number",
    description: "Room Number",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:roomNumber",
    saml2Uri: "urn:oid:0.9.2342.19200300.100.1.6",
    urn: "urn:mace:dir:attribute-def:roomNumber",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=D90B,ou=attributes,o=jans"
  },
  {
    dn: "inum=C703,ou=attributes,o=jans",
    selected: false,
    inum: "C703",
    name: "secretAnswer",
    displayName: "Secret Answer",
    description: "Secret Answer",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:secretAnswer",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.305",
    urn: "urn:jans:dir:attribute-def:secretAnswer",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=C703,ou=attributes,o=jans"
  },
  {
    dn: "inum=8A11,ou=attributes,o=jans",
    selected: false,
    inum: "8A11",
    name: "secretQuestion",
    displayName: "Secret Question",
    description: "Secret Question",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:secretQuestion",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.306",
    urn: "urn:jans:dir:attribute-def:secretQuestion",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=8A11,ou=attributes,o=jans"
  },
  {
    dn: "inum=AC0B,ou=attributes,o=jans",
    selected: false,
    inum: "AC0B",
    name: "secretary",
    displayName: "Secretary",
    description: "Secretary",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:secretary",
    saml2Uri: "urn:oid:0.9.2342.19200300.100.1.21",
    urn: "urn:jans:dir:attribute-def:secretary",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: false,
    userCanView: false,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=AC0B,ou=attributes,o=jans"
  },
  {
    dn: "inum=E6B8,ou=attributes,o=jans",
    selected: false,
    inum: "E6B8",
    name: "st",
    displayName: "State or Province",
    description: "State or Province",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "region",
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:st",
    saml2Uri: "urn:oid:2.5.4.8",
    urn: "urn:mace:dir:attribute-def:st",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=E6B8,ou=attributes,o=jans"
  },
  {
    dn: "inum=6609,ou=attributes,o=jans",
    selected: false,
    inum: "6609",
    name: "street",
    displayName: "Street",
    description: "Street",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "street_address",
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:street",
    saml2Uri: "urn:oid:2.5.4.9",
    urn: "urn:mace:dir:attribute-def:street",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=6609,ou=attributes,o=jans"
  },
  {
    dn: "inum=A901,ou=attributes,o=jans",
    selected: false,
    inum: "A901",
    name: "zoneinfo",
    displayName: "Time zone info",
    description:
      "String from time zone database representing the End-User's time zone. For example,Europe/Paris or America/Los_Angeles.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "zoneinfo",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:zoneinfo",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.327",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/zoneinfo",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=A901,ou=attributes,o=jans"
  },
  {
    dn: "inum=C001,ou=attributes,o=jans",
    selected: false,
    inum: "C001",
    name: "title",
    displayName: "Title",
    description: "Organizational Title",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:title",
    saml2Uri: "urn:oid:2.5.4.12",
    urn: "urn:mace:dir:attribute-def:title",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=C001,ou=attributes,o=jans"
  },
  {
    dn: "inum=BCA8,ou=attributes,o=jans",
    selected: false,
    inum: "BCA8",
    name: "transientId",
    displayName: "TransientId",
    description: "TransientId",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:transientId",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.312",
    urn: "mace:shibboleth:1.0:nameIdentifier",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=BCA8,ou=attributes,o=jans"
  },
  {
    dn: "inum=4649,ou=attributes,o=jans",
    selected: false,
    inum: "4649",
    name: "jansStatus",
    displayName: "User Status",
    description: "User status to allow/disable user access",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["ADMIN", "USER"],
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:jansStatus",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.97",
    urn: "urn:jans:dir:attribute-def:status",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=4649,ou=attributes,o=jans"
  },
  {
    dn: "inum=42E0,ou=attributes,o=jans",
    selected: false,
    inum: "42E0",
    name: "uid",
    displayName: "Username",
    description:
      "A domain issued and managed identifier for the person.Subject - Identifier for the End-User at the Issuer.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "user_name",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:uid",
    saml2Uri: "urn:oid:0.9.2342.19200300.100.1.1",
    urn: "urn:mace:dir:attribute-def:uid",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: false,
    baseDn: "inum=42E0,ou=attributes,o=jans"
  },
  {
    dn: "inum=3B47,ou=attributes,o=jans",
    selected: false,
    inum: "3B47",
    name: "website",
    displayName: "Website URL",
    description: "URL of the End-User's Web page or blog.",
    origin: "jansPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    claimName: "website",
    status: "ACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:website",
    saml2Uri: "urn:oid:1.3.6.1.4.1.48710.1.3.323",
    urn:
      "http://openid.net/specs/openid-connect-core-1_0.html/StandardClaims/website",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=3B47,ou=attributes,o=jans"
  },
  {
    dn: "inum=570B,ou=attributes,o=jans",
    selected: false,
    inum: "570B",
    name: "telephoneNumber",
    displayName: "Work Telephone Number",
    description: "Work Telephone Number",
    origin: "jansCustomPerson",
    dataType: "STRING",
    editType: ["USER", "ADMIN"],
    viewType: ["USER", "ADMIN"],
    status: "INACTIVE",
    saml1Uri: "urn:mace:dir:attribute-def:telephoneNumber",
    saml2Uri: "urn:oid:2.5.4.20",
    urn: "urn:mace:dir:attribute-def:telephoneNumber",
    oxMultiValuedAttribute: false,
    custom: false,
    requred: false,
    adminCanAccess: true,
    adminCanView: true,
    adminCanEdit: true,
    userCanAccess: true,
    userCanView: true,
    whitePagesCanView: false,
    userCanEdit: true,
    baseDn: "inum=570B,ou=attributes,o=jans"
  }
];
