{{- if not .Values.global.istio.gateways }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-global-gtw
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.istio.additionalLabels }}
  labels:
{{ toYaml .Values.global.istio.additionalLabels | indent 4 }}
{{- end }}
{{- if or (.Values.global.istio.additionalAnnotations) (.Values.global.istio.customAnnotations.gateway) }}
  annotations:
{{- if .Values.global.istio.additionalLabels }}  
{{ toYaml .Values.global.istio.additionalAnnotations | indent 4 }}
{{- end }}
{{- if .Values.global.istio.customAnnotations.gateway }}
{{ toYaml .Values.global.istio.customAnnotations.gateway | indent 4 }}
{{- end }}
{{- end }}
spec:
  selector:
    istio: ingressgateway
  servers:
  # admin-ui
  - port:
      number: 80
      name: http-admin-ui
      protocol: HTTP
    hosts:
      - {{ .Values.global.fqdn }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      - {{ .Values.global.fqdn }}
    tls:
      mode: SIMPLE # enable https on this port
      credentialName: tls-certificate # fetch cert from k8s secret
{{- end }}