
apiVersion: v2
name: scim
version: 1.8.0
kubeVersion: ">=v1.21.0-0"
description: System for Cross-domain Identity Management (SCIM) version 2.0
type: application
keywords:
  - SCIM
  - API
home: https://docs.gluu.org
sources:
  - https://github.com/JanssenProject/jans/jans-scim
  - https://github.com/JanssenProject/jans/docker-jans-scim
  - https://github.com/GluuFederation/flex/tree/main/charts/gluu/charts/scim
maintainers:
  - name: Mohammad Abudayyeh
    email: team@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "1.8.0"
