export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const SHOW_USERS = "SHOW_USERS";
export const SEARCH_USERS = "SEARCH_USERS";

export const ADD_GROUP = "ADD_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const SHOW_GROUPS = "SHOW_GROUPS";
export const SEARCH_GROUPS = "SEARCH_GROUPS";

export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE";
export const EDIT_ATTRIBUTE = "EDIT_ATTRIBUTE";
export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE";
export const SHOW_ATTRIBUTES = "SHOW_ATTRIBUTES";
export const SEARCH_ATTRIBUTES = "SEARCH_ATTRIBUTES";

export const ADD_PROVIDER = "ADD_PROVIDER";
export const EDIT_PROVIDER = "EDIT_PROVIDER";
export const DELETE_PROVIDER = "DELETE_PROVIDER";
export const SHOW_PROVIDERS = "SHOW_PROVIDERS";
export const SEARCH_PROVIDERS = "SEARCH_PROVIDERS";

export const ADD_CLIENT = "ADD_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const SHOW_CLIENTS = "SHOW_CLIENTS";
export const SEARCH_CLIENTS = "SEARCH_CLIENTS";
