export const SCRIPT = 'custom-script'
export const API_ROLE = 'api-role'
export const API_CONFIG = 'api-config'
export const API_PERMISSION = 'api-permission'
export const API_MAPPING = 'api-role-mapping'
