package org.gluu.credmanager.core.ldap;

import com.unboundid.ldap.sdk.ReadOnlyEntry;
import com.unboundid.ldap.sdk.persist.*;

/**
 * This class provides an implementation of an object that can be used to
 * represent organizationalUnit objects in the directory.
 * It was generated by the generate-source-from-schema tool provided with the
 * UnboundID LDAP SDK for Java.  It may be customized as desired to better suit
 * your needs.
 */
@LDAPObject(structuralClass="organizationalUnit",
        superiorClass="top")
public class organizationalUnit {

    // The field to use to hold a read-only copy of the associated entry.
    @LDAPEntryField()
    private ReadOnlyEntry ldapEntry;

    // The field used for RDN attribute ou.
    @LDAPField(inRDN=true,
            filterUsage= FilterUsage.ALWAYS_ALLOWED,
            requiredForEncode=true)
    private String[] ou;

    @LDAPDNField
    private String dn;

    /**
     * Retrieves the values for the field associated with the
     * ou attribute, if present.
     *
     * @return  The values for the field associated with the
     *          ou attribute, or
     *          {@code null} if that attribute was not present in the entry.
     */
    public String[] getOu()
    {
        return ou;
    }

    /**
     * Sets the values for the field associated with the
     * ou attribute.
     *
     * @param  v  The values for the field associated with the
     *            ou attribute.
     */
    public void setOu(final String... v)
    {
        this.ou = v;
    }

    public String getDn() {
        return dn;
    }

    public void setDn(String dn) {
        this.dn = dn;
    }

}
