package org.gluu.credmanager.core.ldap;

import com.unboundid.ldap.sdk.ReadOnlyEntry;
import com.unboundid.ldap.sdk.persist.FilterUsage;
import com.unboundid.ldap.sdk.persist.LDAPEntryField;
import com.unboundid.ldap.sdk.persist.LDAPField;
import com.unboundid.ldap.sdk.persist.LDAPObject;

/**
 * This class provides an implementation of an object that can be used to
 * represent oxTrustConfiguration objects in the directory.
 * It was generated by the generate-source-from-schema tool provided with the
 * UnboundID LDAP SDK for Java.  It may be customized as desired to better suit
 * your needs.
 */
@LDAPObject(structuralClass="oxTrustConfiguration",
            superiorClass="top")
public class oxTrustConfiguration
{

  // The field to use to hold a read-only copy of the associated entry.
  @LDAPEntryField()
  private ReadOnlyEntry ldapEntry;

  // The field used for RDN attribute ou.
  @LDAPField(inRDN=true,
             filterUsage=FilterUsage.ALWAYS_ALLOWED,
             requiredForEncode=true)
  private String[] ou;

  // The field used for optional attribute oxTrustConfApplication.
  @LDAPField
  private String[] oxTrustConfApplication;

  // The field used for optional attribute oxTrustConfCacheRefresh.
  @LDAPField
  private String[] oxTrustConfCacheRefresh;

  /**
   * Retrieves the first value for the field associated with the
   * oxTrustConfApplication attribute, if present.
   *
   * @return  The first value for the field associated with the
   *          oxTrustConfApplication attribute, or
   *          {@code null} if that attribute was not present in the entry or
   *          does not have any values.
   */
  public String getOxTrustConfApplication()
  {
    if ((oxTrustConfApplication == null) ||
        (oxTrustConfApplication.length == 0))
    {
      return null;
    }
    else
    {
      return oxTrustConfApplication[0];
    }
  }


  /**
   * Retrieves the first value for the field associated with the
   * oxTrustConfCacheRefresh attribute, if present.
   *
   * @return  The first value for the field associated with the
   *          oxTrustConfCacheRefresh attribute, or
   *          {@code null} if that attribute was not present in the entry or
   *          does not have any values.
   */
  public String getOxTrustConfCacheRefresh()
  {
    if ((oxTrustConfCacheRefresh == null) ||
        (oxTrustConfCacheRefresh.length == 0))
    {
      return null;
    }
    else
    {
      return oxTrustConfCacheRefresh[0];
    }
  }

}
