{{ if index .Values "admin-ui" "ingress" "adminUiEnabled" -}}
{{ $fullName := include "flex-all-in-one.fullname" . -}}
{{- $ingressPath := index .Values "nginx-ingress" "ingress" "path" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-admin-ui
  labels:
    app: {{ $fullName }}-admin-ui
{{- if index .Values "nginx-ingress" "ingress" "additionalLabels" }}
{{ toYaml (index .Values "nginx-ingress" "ingress" "additionalLabels") | indent 4 }}
{{- end }}
{{- if index .Values "auth-server" "ingress" "authServerLabels" }}
{{ toYaml (index .Values "auth-server" "ingress" "authServerLabels") | indent 4 }}
{{- end }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
{{- if index .Values "auth-server" "ingress" "webfingerAdditionalAnnotations" }}
{{ toYaml (index .Values "auth-server" "ingress" "webfingerAdditionalAnnotations") | indent 4 }}
{{- end }}
{{- if index .Values "nginx-ingress" "ingress" "additionalAnnotations" }}
{{ toYaml (index .Values "nginx-ingress" "ingress" "additionalAnnotations") | indent 4 }}
{{- end }}
{{- if index .Values "admin-ui" "ingress" "adminUiAdditionalAnnotations" }}
{{ toYaml (index .Values "admin-ui" "ingress" "adminUiAdditionalAnnotations") | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ index .Values "nginx-ingress" "ingress" "ingressClassName" }}
{{- if index .Values "nginx-ingress" "ingress" "tlsSecretName" }}
  tls:
    - hosts:
        - {{ .Values.fqdn | quote }}
      secretName: {{ index .Values "nginx-ingress" "ingress" "tlsSecretName" }}
{{- end }}
  rules:
    - host: {{ .Values.fqdn | quote }}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: 8080
{{- end }}