{{- if and (index .Values "gateway-api" "enabled") (eq (index .Values "gateway-api" "gateway" "className") "nginx") -}}

{{- if index .Values "gateway-api" "gateway" "caCert" }}
apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: {{ .Release.Name }}-nginx-proxy-config
  namespace: {{ .Release.Namespace }}
spec:
  kubernetes:
    deployment:
      container:
        volumeMounts:
          - mountPath: /etc/nginx/extra-secrets/ca.crt
            name: gateway-ca-cert
            subPath: ca.crt
          - mountPath: /etc/nginx/extra-secrets
            name: extra-secrets
      pod:
        volumes:
          - name: extra-secrets
            emptyDir: {}
          - name: gateway-ca-cert
            secret:
              defaultMode: 0664
              secretName: {{ .Release.Name }}-gateway-ca-cert
{{- end }}

{{- /* Start of Snippets definition */}}
{{- if and (index .Values "gateway-api" "gateway" "verifyClientCertProtection") (index .Values "gateway-api" "additionalConfig" "nginx" "enableClientCertSnippets") }}
---

apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: {{ .Release.Name }}-nginx-verify-client
  namespace: {{ .Release.Namespace }}
spec:
  snippets:
    - context: http.server.location
      value: |
        if ($ssl_client_verify != SUCCESS) {
          return 403;
        }
        proxy_set_header X-ClientCert $ssl_client_escaped_cert;

{{- if index .Values "gateway-api" "gateway" "caCert" }}
---

apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsPolicy
metadata:
  name: {{ .Release.Name }}-nginx-verify-client
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ index .Values "gateway-api" "gateway" "name" }}
  snippets:
    - context: http.server
      value: |
        ssl_client_certificate /etc/nginx/extra-secrets/ca.crt;
        ssl_verify_client optional;
{{- end }}

{{- end }}
{{- /* End of Snippets definition */}}

{{- end }}
