{{- if index .Values "gateway-api" "enabled" -}}
{{- if index .Values "gateway-api" "gateway" "caCert" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-ca-cert
  namespace: {{ .Release.Namespace }}
data:
  ca.crt: {{ index .Values "gateway-api" "gateway" "caCert" }}
{{- end }}
{{- end }}
