apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-license-ssa
  labels:
{{ include "flex-all-in-one.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ssa: {{ required ".admin-ui.licenseSsa is required in chart values. This is a base64 string provided by Gluu to activate your license." (index .Values "admin-ui" "licenseSsa") }}
