{{ if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flex-all-in-one.fullname" . }}
  labels:
    APP_NAME: flex-all-in-one
{{ include "flex-all-in-one.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if or (.Values.additionalAnnotations) (.Values.customAnnotations.podDisruptionBudget) }}
  annotations:
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
{{- if .Values.customAnnotations.podDisruptionBudget }}
{{ toYaml .Values.customAnnotations.podDisruptionBudget | indent 4 }}
{{- end }}
{{- end }}  
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ include "flex-all-in-one.name" . }}-aio
{{- end }}