#! /usr/bin/env python3

import sys
import argparse
import subprocess

parser = argparse.ArgumentParser(description="Gluu/Flex Admin-UI command line utility")
parser.add_argument('-restart', help="Restarts services for Janssen config-api and apache web server", action='store_true')
argsp = parser.parse_args()

if len(sys.argv) < 2:
    print("No argument was provided.")
    sys.exit()

httpd_name = None
for sname in ('httpd', 'apache2'):
    cmd = f'systemctl show --no-pager {sname} | grep LoadState=loaded'
    cmd_output = subprocess.getoutput(cmd).strip()
    if cmd_output:
        httpd_name = sname
        break
if not httpd_name:
    print("\033[93mUnable to determine httpd server name\033[0m")
    sys.exit()

if argsp.restart:
    print("Restarting Admin-UI components")
    for service in ('jans-config-api', httpd_name):
        cmd = f'sudo systemctl restart {service}'
        print(f"Executing {cmd}")
        out = subprocess.getoutput(cmd).strip()
        if out:
            print(f"Command output: {out}")
