export const OIDC_CLIENT = 'openid_client'
export const SCOPE = 'scope'
export const ATTRIBUTE = 'attribute'
export const SCRIPT = 'script'
export const JSON_CONFIG = 'json_properties'
export const SETTINGS = 'settings'
export const LICENSE = 'license'
export const LDAP = 'ldap'
