
apiVersion: v2
name:  cn-istio-ingress
version: 6.5.0
kubeVersion: ">=v1.21.0-0"
description: Istio Gateway
type: application
keywords:
  - istio
  - gateway
home: https://docs.gluu.org/
sources:
  - https://github.com/GluuFederation/flex/tree/main/charts/gluu/charts/cn-istio-ingress
maintainers:
  - name: Mohammad Abudayyeh
    email: team@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/brand/favicon.png
appVersion: "6.5.0"
