apiVersion: v2
name: gateway-api
version: 6.0.0
kubeVersion: ">=v1.23.0-0"
description: Gateway API definitions chart
type: application
keywords:
  - application load balancer
  - Gateway API
home: https://docs.gluu.org
sources:
  - https://github.com/GluuFederation/flex/tree/main/charts/gluu/charts/gateway-api
maintainers:
  - name: Mohammad Abudayyeh
    email: team@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "6.0.0"
