/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JansConfigApi);
  }
}(this, function(expect, JansConfigApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JansConfigApi.CIBAEndUserNotificationConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CIBAEndUserNotificationConfig', function() {
    it('should create an instance of CIBAEndUserNotificationConfig', function() {
      // uncomment below and update the code to test CIBAEndUserNotificationConfig
      //var instane = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be.a(JansConfigApi.CIBAEndUserNotificationConfig);
    });

    it('should have the property apiKey (base name: "apiKey")', function() {
      // uncomment below and update the code to test the property apiKey
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property authDomain (base name: "authDomain")', function() {
      // uncomment below and update the code to test the property authDomain
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property databaseURL (base name: "databaseURL")', function() {
      // uncomment below and update the code to test the property databaseURL
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "projectId")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property storageBucket (base name: "storageBucket")', function() {
      // uncomment below and update the code to test the property storageBucket
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property messagingSenderId (base name: "messagingSenderId")', function() {
      // uncomment below and update the code to test the property messagingSenderId
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property appId (base name: "appId")', function() {
      // uncomment below and update the code to test the property appId
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property notificationUrl (base name: "notificationUrl")', function() {
      // uncomment below and update the code to test the property notificationUrl
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property notificationKey (base name: "notificationKey")', function() {
      // uncomment below and update the code to test the property notificationKey
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

    it('should have the property publicVapidKey (base name: "publicVapidKey")', function() {
      // uncomment below and update the code to test the property publicVapidKey
      //var instance = new JansConfigApi.CIBAEndUserNotificationConfig();
      //expect(instance).to.be();
    });

  });

}));
