/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JansConfigApi);
  }
}(this, function(expect, JansConfigApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JansConfigApi.InlineResponse2005();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2005', function() {
    it('should create an instance of InlineResponse2005', function() {
      // uncomment below and update the code to test InlineResponse2005
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be.a(JansConfigApi.InlineResponse2005);
    });

    it('should have the property loggingLevel (base name: "loggingLevel")', function() {
      // uncomment below and update the code to test the property loggingLevel
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property loggingLayout (base name: "loggingLayout")', function() {
      // uncomment below and update the code to test the property loggingLayout
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property httpLoggingEnabled (base name: "httpLoggingEnabled")', function() {
      // uncomment below and update the code to test the property httpLoggingEnabled
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property disableJdkLogger (base name: "disableJdkLogger")', function() {
      // uncomment below and update the code to test the property disableJdkLogger
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property enabledOAuthAuditLogging (base name: "enabledOAuthAuditLogging")', function() {
      // uncomment below and update the code to test the property enabledOAuthAuditLogging
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property externalLoggerConfiguration (base name: "externalLoggerConfiguration")', function() {
      // uncomment below and update the code to test the property externalLoggerConfiguration
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property httpLoggingExludePaths (base name: "httpLoggingExludePaths")', function() {
      // uncomment below and update the code to test the property httpLoggingExludePaths
      //var instane = new JansConfigApi.InlineResponse2005();
      //expect(instance).to.be();
    });

  });

}));
