export const GET_MAU = 'GET_MAU'
export const GET_MAU_RESPONSE = 'GET_MAU_RESPONSE'
export const RESET = 'RESET'

// Custom Script
export const GET_CUSTOM_SCRIPT = 'GET_CUSTOM_SCRIPT'
export const GET_CUSTOM_SCRIPT_RESPONSE = 'GET_CUSTOM_SCRIPT_RESPONSE'
export const ADD_CUSTOM_SCRIPT = 'ADD_CUSTOM_SCRIPT'
export const ADD_CUSTOM_SCRIPT_RESPONSE = 'ADD_CUSTOM_SCRIPT_RESPONSE'
export const EDIT_CUSTOM_SCRIPT = 'EDIT_CUSTOM_SCRIPT'
export const EDIT_CUSTOM_SCRIPT_RESPONSE = 'EDIT_CUSTOM_SCRIPT_RESPONSE'
export const GET_CUSTOM_SCRIPT_BY_INUM = 'GET_CUSTOM_SCRIPT_BY_INUM'
export const GET_CUSTOM_SCRIPT_BY_INUM_RESPONSE =
  'GET_CUSTOM_SCRIPT_BY_INUM_RESPONSE'
export const GET_CUSTOM_SCRIPT_BY_TYPE = 'GET_CUSTOM_SCRIPT_BY_TYPE'
export const GET_CUSTOM_SCRIPT_BY_TYPE_RESPONSE =
  'GET_CUSTOM_SCRIPT_BY_TYPE_RESPONSE'
export const DELETE_CUSTOM_SCRIPT = 'DELETE_CUSTOM_SCRIPT'
export const DELETE_CUSTOM_SCRIPT_RESPONSE = 'DELETE_CUSTOM_SCRIPT_RESPONSE'
export const SET_SCRIPT_ITEM = 'SET_SCRIPT_ITEM'
