kubeVersion: ">=v1.22.0-0"
annotations:
  artifacthub.io/changes: |
    - 1.0.20 dev chart release
  artifacthub.io/containsSecurityUpdates: 'true'
  artifacthub.io/images: |
    - name: all-in-one
      image: ghcr.io/gluufederation/flex/flex-all-in-one:1.0.20_dev
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: 'true'
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: flex-all-in-one
  catalog.cattle.io/display-name: Flex Cloud Identity and Access Management All-in-One
apiVersion: v2
appVersion: "1.0.20-dev"
icon: >-
  https://gluu.org/docs/gluu-server/favicon.ico
home: https://docs.gluu.org
sources:
  - https://docs.gluu.org
  - https://github.com/GluuProject/jans/charts/janssen
maintainers:
  - name: moabu
    email: support@gluu.org
description: Gluu Access and Identity Management All-in-One Chart. This chart deploys the selected janssen microservice all in one deployment.
name: flex-all-in-one
version: 1.0.20-dev
