/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import JansFido2DynConfiguration from '../model/JansFido2DynConfiguration';

/**
* ConfigurationFido2 service.
* @module api/ConfigurationFido2Api
* @version 1.0.0
*/
export default class ConfigurationFido2Api {

    /**
    * Constructs a new ConfigurationFido2Api. 
    * @alias module:api/ConfigurationFido2Api
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getPropertiesFido2 operation.
     * @callback module:api/ConfigurationFido2Api~getPropertiesFido2Callback
     * @param {String} error Error message, if any.
     * @param {module:model/JansFido2DynConfiguration} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets Jans Authorization Server Fido2 configuration properties.
     * Gets Jans Authorization Server Fido2 configuration properties.
     * @param {module:api/ConfigurationFido2Api~getPropertiesFido2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JansFido2DynConfiguration}
     */
    getPropertiesFido2(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = JansFido2DynConfiguration;
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/fido2/config', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putPropertiesFido2 operation.
     * @callback module:api/ConfigurationFido2Api~putPropertiesFido2Callback
     * @param {String} error Error message, if any.
     * @param {module:model/JansFido2DynConfiguration} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates Fido2 configuration properties.
     * Updates Fido2 configuration properties.
     * @param {Object} opts Optional parameters
     * @param {module:model/JansFido2DynConfiguration} opts.jansFido2DynConfiguration 
     * @param {module:api/ConfigurationFido2Api~putPropertiesFido2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JansFido2DynConfiguration}
     */
    putPropertiesFido2(opts, callback) {
      opts = opts || {};
      let postBody = opts['jansFido2DynConfiguration'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = JansFido2DynConfiguration;
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/fido2/config', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
