/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import PatchRequest from '../model/PatchRequest';
import SectorIdentifier from '../model/SectorIdentifier';

/**
* OAuthOpenIDConnectSectorIdentifiers service.
* @module api/OAuthOpenIDConnectSectorIdentifiersApi
* @version 1.0.0
*/
export default class OAuthOpenIDConnectSectorIdentifiersApi {

    /**
    * Constructs a new OAuthOpenIDConnectSectorIdentifiersApi. 
    * @alias module:api/OAuthOpenIDConnectSectorIdentifiersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteOauthOpenidSectorsById operation.
     * @callback module:api/OAuthOpenIDConnectSectorIdentifiersApi~deleteOauthOpenidSectorsByIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete OpenID Connect Sector.
     * Delete OpenID Connect Sector.
     * @param {String} inum Scope ID.
     * @param {module:api/OAuthOpenIDConnectSectorIdentifiersApi~deleteOauthOpenidSectorsByIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteOauthOpenidSectorsById(inum, callback) {
      let postBody = null;
      // verify the required parameter 'inum' is set
      if (inum === undefined || inum === null) {
        throw new Error("Missing the required parameter 'inum' when calling deleteOauthOpenidSectorsById");
      }

      let pathParams = {
        'inum': inum
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/openid/sectoridentifiers/{inum}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOauthOpenidSectors operation.
     * @callback module:api/OAuthOpenIDConnectSectorIdentifiersApi~getOauthOpenidSectorsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SectorIdentifier>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets list of OpenID Connect Sectors.
     * Gets list of OpenID Connect Sectors.
     * @param {module:api/OAuthOpenIDConnectSectorIdentifiersApi~getOauthOpenidSectorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SectorIdentifier>}
     */
    getOauthOpenidSectors(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SectorIdentifier];
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/openid/sectoridentifiers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOauthOpenidSectorsById operation.
     * @callback module:api/OAuthOpenIDConnectSectorIdentifiersApi~getOauthOpenidSectorsByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SectorIdentifier} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get OpenID Connect Sector by Inum.
     * Get OpenID Connect Sector by Inum.
     * @param {String} inum Scope ID.
     * @param {module:api/OAuthOpenIDConnectSectorIdentifiersApi~getOauthOpenidSectorsByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SectorIdentifier}
     */
    getOauthOpenidSectorsById(inum, callback) {
      let postBody = null;
      // verify the required parameter 'inum' is set
      if (inum === undefined || inum === null) {
        throw new Error("Missing the required parameter 'inum' when calling getOauthOpenidSectorsById");
      }

      let pathParams = {
        'inum': inum
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SectorIdentifier;
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/openid/sectoridentifiers/{inum}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the patchOauthOpenidSectorsById operation.
     * @callback module:api/OAuthOpenIDConnectSectorIdentifiersApi~patchOauthOpenidSectorsByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SectorIdentifier} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Partially update OpenId Connect Sector by Inum.
     * Partially update OpenId Connect Sector by Inum.
     * @param {String} inum Scope ID.
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/PatchRequest>} opts.patchRequest 
     * @param {module:api/OAuthOpenIDConnectSectorIdentifiersApi~patchOauthOpenidSectorsByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SectorIdentifier}
     */
    patchOauthOpenidSectorsById(inum, opts, callback) {
      opts = opts || {};
      let postBody = opts['patchRequest'];
      // verify the required parameter 'inum' is set
      if (inum === undefined || inum === null) {
        throw new Error("Missing the required parameter 'inum' when calling patchOauthOpenidSectorsById");
      }

      let pathParams = {
        'inum': inum
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = ['application/json-patch+json'];
      let accepts = ['application/json'];
      let returnType = SectorIdentifier;
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/openid/sectoridentifiers/{inum}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postOauthOpenidSectors operation.
     * @callback module:api/OAuthOpenIDConnectSectorIdentifiersApi~postOauthOpenidSectorsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SectorIdentifier} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create new OpenID Connect Sector.
     * Create new OpenID Connect Sector.
     * @param {Object} opts Optional parameters
     * @param {module:model/SectorIdentifier} opts.sectorIdentifier 
     * @param {module:api/OAuthOpenIDConnectSectorIdentifiersApi~postOauthOpenidSectorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SectorIdentifier}
     */
    postOauthOpenidSectors(opts, callback) {
      opts = opts || {};
      let postBody = opts['sectorIdentifier'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SectorIdentifier;
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/openid/sectoridentifiers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the putOauthOpenidSectors operation.
     * @callback module:api/OAuthOpenIDConnectSectorIdentifiersApi~putOauthOpenidSectorsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SectorIdentifier} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update OpenId Connect Sector.
     * Update OpenId Connect Sector.
     * @param {Object} opts Optional parameters
     * @param {module:model/SectorIdentifier} opts.sectorIdentifier 
     * @param {module:api/OAuthOpenIDConnectSectorIdentifiersApi~putOauthOpenidSectorsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SectorIdentifier}
     */
    putOauthOpenidSectors(opts, callback) {
      opts = opts || {};
      let postBody = opts['sectorIdentifier'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['jans-auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SectorIdentifier;
      return this.apiClient.callApi(
        '/jans-config-api/api/v1/openid/sectoridentifiers', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
