version: "3.7"
services:
  mysql:
    image: mysql:8.0.30
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - cloud_bridge
    environment:
      - MYSQL_DATABASE=gluu
      - MYSQL_USER=gluu
      - MYSQL_PASSWORD=1t5Fin3#security
      - MYSQL_ROOT_PASSWORD=1t5Fin3#security
  flex:
    image: gluufederation/monolith:5.0.0_dev
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - mysql
    networks:
      - cloud_bridge
    environment:
      - CN_HOSTNAME=demoexample.gluu.org
      - CN_ADMIN_PASS=1t5Fin3#security
      - CN_ORG_NAME=Janssen
      - CN_EMAIL=support@gluu.org
      - CN_CITY=Austin
      - CN_STATE=TX
      - CN_COUNTRY=US
      - IS_FQDN_REGISTERED=false
      - CN_INSTALL_CONFIG_API=true
      - CN_INSTALL_SCIM=true
      - CN_INSTALL_FIDO2=true
      - CN_INSTALL_CASA=true
      - CN_INSTALL_ADMIN_UI=true
      - MYSQL_DATABASE=gluu
      - MYSQL_USER=gluu
      - MYSQL_PASSWORD=1t5Fin3#security
      - MYSQL_HOST=mysql
    volumes:
      - ./jans-auth-custom:/opt/jans/jetty/jans-auth/custom
      - ./jans-config-api-custom:/opt/jans/jetty/jans-config-api/custom
      - ./jans-fido2-custom:/opt/jans/jetty/jans-fido2/custom
      - ./jans-scim-custom:/opt/jans/jetty/jans-scim/custom
      - ./flex-casa:/opt/jans/jetty/casa/custom
volumes:
  db-data:
networks:
  cloud_bridge:
    driver: bridge
