version: "3.7"
services:
  flex:
    image: gluufederation/monolith:5.0.0_dev
    restart: always
    ports:
      - "443:443"
      - "80:80"
    networks:
      - cloud_bridge
    environment:
      - CN_HOSTNAME=demoexample.gluu.org
      - CN_ADMIN_PASS=1t5Fin3#security
      - CN_ORG_NAME=Gluu
      - CN_EMAIL=support@gluu.org
      - CN_CITY=Austin
      - CN_STATE=TX
      - CN_COUNTRY=US
      - CN_INSTALL_LDAP=true
      - IS_FQDN_REGISTERED=false
      - CN_INSTALL_CONFIG_API=true
      - CN_INSTALL_SCIM=true
      - CN_INSTALL_FIDO2=true
      - CN_INSTALL_CASA=true
      - CN_INSTALL_ADMIN_UI=true
      - TEST_CLIENT_ID=9876baac-de39-4c23-8a78-674b59df8c09
      - TEST_CLIENT_TRUSTED=true
      - TEST_CLIENT_SECRET=1t5Fin3#security
    volumes:
      - ./jans-auth-custom:/opt/jans/jetty/jans-auth/custom
      - ./jans-config-api-custom:/opt/jans/jetty/jans-config-api/custom
      - ./jans-fido2-custom:/opt/jans/jetty/jans-fido2/custom
      - ./jans-scim-custom:/opt/jans/jetty/jans-scim/custom
      - ./flex-casa:/opt/jans/jetty/casa/custom
volumes:
  db-data:
networks:
  cloud_bridge:
    driver: bridge
