version: "3.7"
services:
  mysql:
    image: mysql:8.0.30
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - cloud_bridge
    environment:
      - MYSQL_DATABASE=gluu
      - MYSQL_USER=gluu
      - MYSQL_PASSWORD=1t5Fin3#security
      - MYSQL_ROOT_PASSWORD=1t5Fin3#security
  flex:
    image: ghcr.io/gluufederation/flex/monolith:5.1.6_dev
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - mysql
    networks:
      - cloud_bridge
    environment:
      #- CN_HOSTNAME=demoexample.gluu.org
      - CN_ADMIN_PASS=1t5Fin3#security
      - CN_ORG_NAME=Gluu
      - CN_EMAIL=team@gluu.org
      - CN_CITY=Austin
      - CN_STATE=TX
      - CN_COUNTRY=US
      - CN_INSTALL_MYSQL=true
      - IS_FQDN_REGISTERED=false
      - CN_INSTALL_CONFIG_API=true
      - CN_INSTALL_SCIM=true
      - CN_INSTALL_FIDO2=true
      - CN_INSTALL_CASA=true
      - CN_INSTALL_ADMIN_UI=true
      - CN_INSTALL_KC_LINK=true
      - CN_INSTALL_LOCK=true
      - CN_INSTALL_SAML=true
      - CN_INSTALL_OPA=true
      - TEST_CLIENT_ID=9876baac-de39-4c23-8a78-674b59df8c09
      - TEST_CLIENT_TRUSTED=true
      - TEST_CLIENT_SECRET=1t5Fin3#security
      - RDBMS_DATABASE=gluu
      - RDBMS_USER=gluu
      - RDBMS_PASSWORD=1t5Fin3#security
      - RDBMS_HOST=mysql
    volumes:
      - ./jans-auth-custom:/opt/jans/jetty/jans-auth/custom
      - ./jans-config-api-custom:/opt/jans/jetty/jans-config-api/custom
      - ./jans-fido2-custom:/opt/jans/jetty/jans-fido2/custom
      - ./jans-scim-custom:/opt/jans/jetty/jans-scim/custom
      - ./jans-casa-custom:/opt/jans/jetty/casa/custom
      - ./jans-auth-log:/opt/jans/jetty/jans-auth/logs
      - ./jans-config-api-log:/opt/jans/jetty/jans-config-api/logs
      - ./jans-scim-log:/opt/jans/jetty/jans-scim/logs
      - ./jans-fido2-log:/opt/jans/jetty/jans-fido2/log
volumes:
  db-data:
networks:
  cloud_bridge:
    driver: bridge
