export const GET_MAU = 'GET_MAU'
export const GET_MAU_RESPONSE = 'GET_MAU_RESPONSE'
//Stat Actions
export const GET_SCRIPTS_FOR_STAT = 'GET_SCRIPTS_FOR_STAT'
export const GET_SCRIPTS_FOR_STAT_RESPONSE = 'GET_SCRIPTS_FOR_STAT_RESPONSE'
export const GET_SCOPES_FOR_STAT = 'GET_SCOPES_FOR_STAT'
export const GET_SCOPES_FOR_STAT_RESPONSE = 'GET_SCOPES_FOR_STAT_RESPONSE'
export const GET_ATTRIBUTES_FOR_STAT = 'GET_ATTRIBUTES_FOR_STAT'
export const GET_ATTRIBUTES_FOR_STAT_RESPONSE =
  'GET_ATTRIBUTES_FOR_STAT_RESPONSE'
export const GET_CLIENTS_FOR_STAT = 'GET_CLIENTS_FOR_STAT'
export const GET_CLIENTS_FOR_STAT_RESPONSE = 'GET_CLIENTS_FOR_STAT_RESPONSE'

// Auth Actions
export const GET_OAUTH2_CONFIG = 'GET_OAUTH2_CONFIG'
export const GET_OAUTH2_CONFIG_RESPONSE = 'GET_OAUTH2_CONFIG_RESPONSE'
export const GET_API_ACCESS_TOKEN = 'GET_API_ACCESS_TOKEN'
export const GET_API_ACCESS_TOKEN_RESPONSE = 'GET_API_ACCESS_TOKEN_RESPONSE'
export const SET_STATE = 'SET_STATE'
export const USERINFO_REQUEST = 'USERINFO_REQUEST'
export const USERINFO_RESPONSE = 'USERINFO_RESPONSE'
export const GET_SCOPES = 'GET_SCOPES'
export const GET_ATTRIBUTES = 'GET_ATTRIBUTES'
export const GET_OPENID_CLIENTS = 'GET_OPENID_CLIENTS'
export const GET_CUSTOM_SCRIPT = 'GET_CUSTOM_SCRIPT'
export const GET_ACR_AUTH_SCRIPT = 'GET_ACR_AUTH_SCRIPT'
export const GET_ACR_AUTH_SCRIPT_RESPONSE = 'GET_ACR_AUTH_SCRIPT_RESPONSE'
//user location
export const GET_USER_LOCATION = 'GET_USER_LOCATION'
export const GET_USER_LOCATION_RESPONSE = 'GET_USER_LOCATION_RESPONSE'
// fido
export const GET_FIDO = 'GET_FIDO'
export const GET_FIDO_RESPONSE = 'GET_FIDO_RESPONSE'
export const PUT_FIDO = 'PUT_FIDO'
export const PUT_FIDO_RESPONSE = 'PUT_FIDO_RESPONSE'
export const RESET = 'RESET'
export const SET_ITEM = 'SET_ITEM'
// Plugin
export const GET_ALL_PLUGIN_MENU = 'GET_ALL_PLUGIN_MENU'
export const GET_ALL_PLUGIN_MENU_RESPONSE = 'GET_ALL_PLUGIN_MENU_RESPONSE'
// Ldap
export const GET_LDAP = 'GET_LDAP'
export const GET_LDAP_RESPONSE = 'GET_LDAP_RESPONSE'
export const SET_LDAP = 'SET_LDAP'
export const SET_LDAP_RESPONSE = 'SET_LDAP_RESPONSE'
export const PUT_LDAP = 'PUT_LDAP'
export const PUT_LDAP_RESPONSE = 'PUT_LDAP_RESPONSE'
export const ADD_LDAP = 'ADD_LDAP'
export const ADD_LDAP_RESPONSE = 'ADD_LDAP_RESPONSE'
export const DELETE_LDAP = 'DELETE_LDAP'
export const DELETE_LDAP_RESPONSE = 'DELETE_LDAP_RESPONSE'
export const TEST_LDAP = 'TEST_LDAP'
export const TEST_LDAP_RESPONSE = 'TEST_LDAP_RESPONSE'
// Couchbase
export const GET_COUCHBASE = 'GET_COUCHBASE'
export const GET_COUCHBASE_RESPONSE = 'GET_COUCHBASE_RESPONSE'
export const SET_COUCHBASE = 'SET_COUCHBASE'
export const SET_COUCHBASE_RESPONSE = 'SET_COUCHBASE_RESPONSE'
export const PUT_COUCHBASE = 'PUT_COUCHBASE'
export const PUT_COUCHBASE_RESPONSE = 'PUT_COUCHBASE_RESPONSE'
// User Logout
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
//License
export const CHECK_FOR_VALID_LICENSE = 'CHECK_FOR_VALID_LICENSE'
export const CHECK_FOR_VALID_LICENSE_RESPONSE =
  'CHECK_FOR_VALID_LICENSE_RESPONSE'
export const ACTIVATE_LICENSE = 'ACTIVATE_LICENSE'
export const ACTIVATE_LICENSE_RESPONSE = 'ACTIVATE_LICENSE_RESPONSE'
//OIDC DISCOVERY
export const GET_OIDC_DISCOVERY = 'GET_OIDC_DISCOVERY'
export const GET_OIDC_DISCOVERY_RESPONSE = 'GET_OIDC_DISCOVERY_RESPONSE'
// Health
export const GET_HEALTH = 'GET_HEALTH'
export const GET_HEALTH_RESPONSE = 'GET_HEALTH_RESPONSE'
//License Details
export const GET_LICENSE_DETAILS = 'GET_LICENSE_DETAILS'
export const GET_LICENSE_DETAILS_RESPONSE = 'GET_LICENSE_DETAILS_RESPONSE'
export const UPDATE_LICENSE_DETAILS = 'UPDATE_LICENSE_DETAILS'
export const UPDATE_LICENSE_DETAILS_RESPONSE = 'UPDATE_LICENSE_DETAILS_RESPONSE'