apiVersion: v2
name: admin-ui
version: 5.0.7
kubeVersion: ">=v1.21.0-0"
description: Admin GUI. Requires license.
type: application
keywords:
  - Authorization
  - OpenID
  - GUI
home: https://gluu.org/docs/gluu-server
sources:
  - https://github.com/GluuFederation/docker-gluu-admin-ui
  - https://github.com/GluuFederation/flex/tree/main/flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/admin-ui
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: 5.0.0
