export const SCRIPT = 'custom-script'
export const API_ROLE = 'api-role'
export const API_PERMISSION = 'api-permission'
export const API_MAPPING = 'api-role-mapping'
export const API_USERS = 'api-users'
export const API_LICENSE = 'api-license'
export const API_LOGGING = 'api-logging'
