export const API_USERS = 'api-users'
export const API_LICENSE = 'api-license'
export const API_LOGGING = 'api-logging'
export const API_ACRS = 'api-acrs'
export const CONFIG_API_CONFIGURATION = 'Config API configuration'
export const SCRIPT = 'SCRIPT'
export const ASSET = 'asset'
