export const FETCH = 'FETCH'
export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETION = 'DELETION'
export const PATCH = 'PATCH'
export const FETCH_SCRIPTS_FOR_STAT = 'FETCH SCRIPTS FOR STAT'
