// SMTP Management

export const GET_FIDO_CONFIGURATION = 'GET_FIDO_CONFIGURATION'
export const PUT_FIDO_CONFIGURATION = 'PUT_FIDO_CONFIGURATION'
export const GET_FIDO_CONFIGURATION_RESPONSE = 'GET_FIDO_CONFIGURATION_RESPONSE'