/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AppConfigurationAuthenticationProtectionConfiguration model module.
 * @module model/AppConfigurationAuthenticationProtectionConfiguration
 * @version 1.0.0
 */
class AppConfigurationAuthenticationProtectionConfiguration {
    /**
     * Constructs a new <code>AppConfigurationAuthenticationProtectionConfiguration</code>.
     * Authentication Brute Force Protection Configuration.
     * @alias module:model/AppConfigurationAuthenticationProtectionConfiguration
     */
    constructor() { 
        
        AppConfigurationAuthenticationProtectionConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppConfigurationAuthenticationProtectionConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppConfigurationAuthenticationProtectionConfiguration} obj Optional instance to populate.
     * @return {module:model/AppConfigurationAuthenticationProtectionConfiguration} The populated <code>AppConfigurationAuthenticationProtectionConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppConfigurationAuthenticationProtectionConfiguration();

            if (data.hasOwnProperty('attemptExpiration')) {
                obj['attemptExpiration'] = ApiClient.convertToType(data['attemptExpiration'], 'Number');
            }
            if (data.hasOwnProperty('maximumAllowedAttemptsWithoutDelay')) {
                obj['maximumAllowedAttemptsWithoutDelay'] = ApiClient.convertToType(data['maximumAllowedAttemptsWithoutDelay'], 'Number');
            }
            if (data.hasOwnProperty('delayTime')) {
                obj['delayTime'] = ApiClient.convertToType(data['delayTime'], 'Number');
            }
            if (data.hasOwnProperty('bruteForceProtectionEnabled')) {
                obj['bruteForceProtectionEnabled'] = ApiClient.convertToType(data['bruteForceProtectionEnabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} attemptExpiration
 */
AppConfigurationAuthenticationProtectionConfiguration.prototype['attemptExpiration'] = undefined;

/**
 * @member {Number} maximumAllowedAttemptsWithoutDelay
 */
AppConfigurationAuthenticationProtectionConfiguration.prototype['maximumAllowedAttemptsWithoutDelay'] = undefined;

/**
 * @member {Number} delayTime
 */
AppConfigurationAuthenticationProtectionConfiguration.prototype['delayTime'] = undefined;

/**
 * @member {Boolean} bruteForceProtectionEnabled
 */
AppConfigurationAuthenticationProtectionConfiguration.prototype['bruteForceProtectionEnabled'] = undefined;






export default AppConfigurationAuthenticationProtectionConfiguration;

