/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthenticationMethod model module.
 * @module model/AuthenticationMethod
 * @version 1.0.0
 */
class AuthenticationMethod {
    /**
     * Constructs a new <code>AuthenticationMethod</code>.
     * Default authentication method.
     * @alias module:model/AuthenticationMethod
     */
    constructor() { 
        
        AuthenticationMethod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthenticationMethod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthenticationMethod} obj Optional instance to populate.
     * @return {module:model/AuthenticationMethod} The populated <code>AuthenticationMethod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticationMethod();

            if (data.hasOwnProperty('defaultAcr')) {
                obj['defaultAcr'] = ApiClient.convertToType(data['defaultAcr'], 'String');
            }
            if (data.hasOwnProperty('oxtrustAcr')) {
                obj['oxtrustAcr'] = ApiClient.convertToType(data['oxtrustAcr'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} defaultAcr
 */
AuthenticationMethod.prototype['defaultAcr'] = undefined;

/**
 * @member {String} oxtrustAcr
 */
AuthenticationMethod.prototype['oxtrustAcr'] = undefined;






export default AuthenticationMethod;

