/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthenticationFilters model module.
 * @module model/AuthenticationFilters
 * @version 1.0.0
 */
class AuthenticationFilters {
    /**
     * Constructs a new <code>AuthenticationFilters</code>.
     * Represents the authentication filter.
     * @alias module:model/AuthenticationFilters
     */
    constructor() { 
        
        AuthenticationFilters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthenticationFilters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthenticationFilters} obj Optional instance to populate.
     * @return {module:model/AuthenticationFilters} The populated <code>AuthenticationFilters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticationFilters();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], 'String');
            }
            if (data.hasOwnProperty('bind')) {
                obj['bind'] = ApiClient.convertToType(data['bind'], 'Boolean');
            }
            if (data.hasOwnProperty('bind-password-attribute')) {
                obj['bind-password-attribute'] = ApiClient.convertToType(data['bind-password-attribute'], 'String');
            }
            if (data.hasOwnProperty('base-dn')) {
                obj['base-dn'] = ApiClient.convertToType(data['base-dn'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Filter to be used.
 * @member {String} filter
 */
AuthenticationFilters.prototype['filter'] = undefined;

/**
 * Filter bind.
 * @member {Boolean} bind
 */
AuthenticationFilters.prototype['bind'] = undefined;

/**
 * Filter bind password attribute.
 * @member {String} bind-password-attribute
 */
AuthenticationFilters.prototype['bind-password-attribute'] = undefined;

/**
 * Bind filter base distinguished name.
 * @member {String} base-dn
 */
AuthenticationFilters.prototype['base-dn'] = undefined;






export default AuthenticationFilters;

