/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InMemoryConfiguration from './InMemoryConfiguration';
import MemcachedConfiguration from './MemcachedConfiguration';
import NativePersistenceConfiguration from './NativePersistenceConfiguration';
import RedisConfiguration from './RedisConfiguration';

/**
 * The CacheConfiguration model module.
 * @module model/CacheConfiguration
 * @version 1.0.0
 */
class CacheConfiguration {
    /**
     * Constructs a new <code>CacheConfiguration</code>.
     * Cache Configuration Details.
     * @alias module:model/CacheConfiguration
     */
    constructor() { 
        
        CacheConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CacheConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CacheConfiguration} obj Optional instance to populate.
     * @return {module:model/CacheConfiguration} The populated <code>CacheConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CacheConfiguration();

            if (data.hasOwnProperty('cacheProviderType')) {
                obj['cacheProviderType'] = ApiClient.convertToType(data['cacheProviderType'], 'String');
            }
            if (data.hasOwnProperty('memcachedConfiguration')) {
                obj['memcachedConfiguration'] = MemcachedConfiguration.constructFromObject(data['memcachedConfiguration']);
            }
            if (data.hasOwnProperty('redisConfiguration')) {
                obj['redisConfiguration'] = RedisConfiguration.constructFromObject(data['redisConfiguration']);
            }
            if (data.hasOwnProperty('inMemoryConfiguration')) {
                obj['inMemoryConfiguration'] = InMemoryConfiguration.constructFromObject(data['inMemoryConfiguration']);
            }
            if (data.hasOwnProperty('nativePersistenceConfiguration')) {
                obj['nativePersistenceConfiguration'] = NativePersistenceConfiguration.constructFromObject(data['nativePersistenceConfiguration']);
            }
        }
        return obj;
    }


}

/**
 * The cache Provider Type.
 * @member {module:model/CacheConfiguration.CacheProviderTypeEnum} cacheProviderType
 */
CacheConfiguration.prototype['cacheProviderType'] = undefined;

/**
 * @member {module:model/MemcachedConfiguration} memcachedConfiguration
 */
CacheConfiguration.prototype['memcachedConfiguration'] = undefined;

/**
 * @member {module:model/RedisConfiguration} redisConfiguration
 */
CacheConfiguration.prototype['redisConfiguration'] = undefined;

/**
 * @member {module:model/InMemoryConfiguration} inMemoryConfiguration
 */
CacheConfiguration.prototype['inMemoryConfiguration'] = undefined;

/**
 * @member {module:model/NativePersistenceConfiguration} nativePersistenceConfiguration
 */
CacheConfiguration.prototype['nativePersistenceConfiguration'] = undefined;





/**
 * Allowed values for the <code>cacheProviderType</code> property.
 * @enum {String}
 * @readonly
 */
CacheConfiguration['CacheProviderTypeEnum'] = {

    /**
     * value: "IN_MEMORY"
     * @const
     */
    "IN_MEMORY": "IN_MEMORY",

    /**
     * value: "MEMCACHED"
     * @const
     */
    "MEMCACHED": "MEMCACHED",

    /**
     * value: "REDIS"
     * @const
     */
    "REDIS": "REDIS",

    /**
     * value: "NATIVE_PERSISTENCE"
     * @const
     */
    "NATIVE_PERSISTENCE": "NATIVE_PERSISTENCE"
};



export default CacheConfiguration;

