/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CIBAEndUserNotificationConfig model module.
 * @module model/CIBAEndUserNotificationConfig
 * @version 1.0.0
 */
class CIBAEndUserNotificationConfig {
    /**
     * Constructs a new <code>CIBAEndUserNotificationConfig</code>.
     * CIBA End User Notification Config.
     * @alias module:model/CIBAEndUserNotificationConfig
     */
    constructor() { 
        
        CIBAEndUserNotificationConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CIBAEndUserNotificationConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CIBAEndUserNotificationConfig} obj Optional instance to populate.
     * @return {module:model/CIBAEndUserNotificationConfig} The populated <code>CIBAEndUserNotificationConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CIBAEndUserNotificationConfig();

            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
            if (data.hasOwnProperty('authDomain')) {
                obj['authDomain'] = ApiClient.convertToType(data['authDomain'], 'String');
            }
            if (data.hasOwnProperty('databaseURL')) {
                obj['databaseURL'] = ApiClient.convertToType(data['databaseURL'], 'String');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('storageBucket')) {
                obj['storageBucket'] = ApiClient.convertToType(data['storageBucket'], 'String');
            }
            if (data.hasOwnProperty('messagingSenderId')) {
                obj['messagingSenderId'] = ApiClient.convertToType(data['messagingSenderId'], 'String');
            }
            if (data.hasOwnProperty('appId')) {
                obj['appId'] = ApiClient.convertToType(data['appId'], 'String');
            }
            if (data.hasOwnProperty('notificationUrl')) {
                obj['notificationUrl'] = ApiClient.convertToType(data['notificationUrl'], 'String');
            }
            if (data.hasOwnProperty('notificationKey')) {
                obj['notificationKey'] = ApiClient.convertToType(data['notificationKey'], 'String');
            }
            if (data.hasOwnProperty('publicVapidKey')) {
                obj['publicVapidKey'] = ApiClient.convertToType(data['publicVapidKey'], 'String');
            }
        }
        return obj;
    }


}

/**
 * API Key
 * @member {String} apiKey
 */
CIBAEndUserNotificationConfig.prototype['apiKey'] = undefined;

/**
 * Auth Domain
 * @member {String} authDomain
 */
CIBAEndUserNotificationConfig.prototype['authDomain'] = undefined;

/**
 * Database URL
 * @member {String} databaseURL
 */
CIBAEndUserNotificationConfig.prototype['databaseURL'] = undefined;

/**
 * Project ID
 * @member {String} projectId
 */
CIBAEndUserNotificationConfig.prototype['projectId'] = undefined;

/**
 * Storage Bucket
 * @member {String} storageBucket
 */
CIBAEndUserNotificationConfig.prototype['storageBucket'] = undefined;

/**
 * Messaging Sender ID
 * @member {String} messagingSenderId
 */
CIBAEndUserNotificationConfig.prototype['messagingSenderId'] = undefined;

/**
 * App ID
 * @member {String} appId
 */
CIBAEndUserNotificationConfig.prototype['appId'] = undefined;

/**
 * Notification URL
 * @member {String} notificationUrl
 */
CIBAEndUserNotificationConfig.prototype['notificationUrl'] = undefined;

/**
 * Notification Key
 * @member {String} notificationKey
 */
CIBAEndUserNotificationConfig.prototype['notificationKey'] = undefined;

/**
 * Public Vapid Key
 * @member {String} publicVapidKey
 */
CIBAEndUserNotificationConfig.prototype['publicVapidKey'] = undefined;






export default CIBAEndUserNotificationConfig;

