/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClientAttributes model module.
 * @module model/ClientAttributes
 * @version 1.0.0
 */
class ClientAttributes {
    /**
     * Constructs a new <code>ClientAttributes</code>.
     * Attribute.
     * @alias module:model/ClientAttributes
     */
    constructor() { 
        
        ClientAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClientAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientAttributes} obj Optional instance to populate.
     * @return {module:model/ClientAttributes} The populated <code>ClientAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientAttributes();

            if (data.hasOwnProperty('tlsClientAuthSubjectDn')) {
                obj['tlsClientAuthSubjectDn'] = ApiClient.convertToType(data['tlsClientAuthSubjectDn'], 'String');
            }
            if (data.hasOwnProperty('runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims')) {
                obj['runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims'] = ApiClient.convertToType(data['runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims'], 'Boolean');
            }
            if (data.hasOwnProperty('keepClientAuthorizationAfterExpiration')) {
                obj['keepClientAuthorizationAfterExpiration'] = ApiClient.convertToType(data['keepClientAuthorizationAfterExpiration'], 'Boolean');
            }
            if (data.hasOwnProperty('allowSpontaneousScopes')) {
                obj['allowSpontaneousScopes'] = ApiClient.convertToType(data['allowSpontaneousScopes'], 'Boolean');
            }
            if (data.hasOwnProperty('spontaneousScopes')) {
                obj['spontaneousScopes'] = ApiClient.convertToType(data['spontaneousScopes'], ['String']);
            }
            if (data.hasOwnProperty('spontaneousScopeScriptDns')) {
                obj['spontaneousScopeScriptDns'] = ApiClient.convertToType(data['spontaneousScopeScriptDns'], ['String']);
            }
            if (data.hasOwnProperty('backchannelLogoutUri')) {
                obj['backchannelLogoutUri'] = ApiClient.convertToType(data['backchannelLogoutUri'], ['String']);
            }
            if (data.hasOwnProperty('backchannelLogoutSessionRequired')) {
                obj['backchannelLogoutSessionRequired'] = ApiClient.convertToType(data['backchannelLogoutSessionRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('additionalAudience')) {
                obj['additionalAudience'] = ApiClient.convertToType(data['additionalAudience'], ['String']);
            }
            if (data.hasOwnProperty('postAuthnScripts')) {
                obj['postAuthnScripts'] = ApiClient.convertToType(data['postAuthnScripts'], ['String']);
            }
            if (data.hasOwnProperty('consentGatheringScripts')) {
                obj['consentGatheringScripts'] = ApiClient.convertToType(data['consentGatheringScripts'], ['String']);
            }
            if (data.hasOwnProperty('introspectionScripts')) {
                obj['introspectionScripts'] = ApiClient.convertToType(data['introspectionScripts'], ['String']);
            }
            if (data.hasOwnProperty('rptClaimsScripts')) {
                obj['rptClaimsScripts'] = ApiClient.convertToType(data['rptClaimsScripts'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} tlsClientAuthSubjectDn
 */
ClientAttributes.prototype['tlsClientAuthSubjectDn'] = undefined;

/**
 * Run Introspection Script Before Access Token as Jwt Creation and Include Claims. Default value is false.
 * @member {Boolean} runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims
 */
ClientAttributes.prototype['runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims'] = undefined;

/**
 * Keep Client Authorization After Expiration.
 * @member {Boolean} keepClientAuthorizationAfterExpiration
 */
ClientAttributes.prototype['keepClientAuthorizationAfterExpiration'] = undefined;

/**
 * @member {Boolean} allowSpontaneousScopes
 */
ClientAttributes.prototype['allowSpontaneousScopes'] = undefined;

/**
 * @member {Array.<String>} spontaneousScopes
 */
ClientAttributes.prototype['spontaneousScopes'] = undefined;

/**
 * @member {Array.<String>} spontaneousScopeScriptDns
 */
ClientAttributes.prototype['spontaneousScopeScriptDns'] = undefined;

/**
 * @member {Array.<String>} backchannelLogoutUri
 */
ClientAttributes.prototype['backchannelLogoutUri'] = undefined;

/**
 * @member {Boolean} backchannelLogoutSessionRequired
 */
ClientAttributes.prototype['backchannelLogoutSessionRequired'] = undefined;

/**
 * @member {Array.<String>} additionalAudience
 */
ClientAttributes.prototype['additionalAudience'] = undefined;

/**
 * @member {Array.<String>} postAuthnScripts
 */
ClientAttributes.prototype['postAuthnScripts'] = undefined;

/**
 * @member {Array.<String>} consentGatheringScripts
 */
ClientAttributes.prototype['consentGatheringScripts'] = undefined;

/**
 * @member {Array.<String>} introspectionScripts
 */
ClientAttributes.prototype['introspectionScripts'] = undefined;

/**
 * @member {Array.<String>} rptClaimsScripts
 */
ClientAttributes.prototype['rptClaimsScripts'] = undefined;






export default ClientAttributes;

