/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClientAttributes from './ClientAttributes';
import CustomAttribute from './CustomAttribute';

/**
 * The Client model module.
 * @module model/Client
 * @version 1.0.0
 */
class Client {
    /**
     * Constructs a new <code>Client</code>.
     * Client.
     * @alias module:model/Client
     * @param frontChannelLogoutSessionRequired {Boolean} 
     * @param applicationType {module:model/Client.ApplicationTypeEnum} Kind of the application. The default, if omitted, is web. The defined values are native or web. Web Clients using the OAuth Implicit Grant Type must only register URLs using the HTTPS scheme as redirect_uris, they must not use localhost as the hostname. Native Clients must only register redirect_uris using custom URI schemes or URLs using the http scheme with localhost as the hostname.
     * @param clientName {String} A human-readable name of the client.
     * @param subjectType {module:model/Client.SubjectTypeEnum} Subject type requested for the Client ID. Valid types include pairwise and public.
     * @param includeClaimsInIdToken {Boolean} If true then claims are included in token id, default value is false.
     */
    constructor(frontChannelLogoutSessionRequired, applicationType, clientName, subjectType, includeClaimsInIdToken) { 
        
        Client.initialize(this, frontChannelLogoutSessionRequired, applicationType, clientName, subjectType, includeClaimsInIdToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, frontChannelLogoutSessionRequired, applicationType, clientName, subjectType, includeClaimsInIdToken) { 
        obj['frontChannelLogoutSessionRequired'] = frontChannelLogoutSessionRequired;
        obj['applicationType'] = applicationType;
        obj['clientName'] = clientName;
        obj['subjectType'] = subjectType;
        obj['includeClaimsInIdToken'] = includeClaimsInIdToken || false;
    }

    /**
     * Constructs a <code>Client</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Client} obj Optional instance to populate.
     * @return {module:model/Client} The populated <code>Client</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Client();

            if (data.hasOwnProperty('dn')) {
                obj['dn'] = ApiClient.convertToType(data['dn'], 'String');
            }
            if (data.hasOwnProperty('inum')) {
                obj['inum'] = ApiClient.convertToType(data['inum'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('frontChannelLogoutUri')) {
                obj['frontChannelLogoutUri'] = ApiClient.convertToType(data['frontChannelLogoutUri'], 'String');
            }
            if (data.hasOwnProperty('frontChannelLogoutSessionRequired')) {
                obj['frontChannelLogoutSessionRequired'] = ApiClient.convertToType(data['frontChannelLogoutSessionRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('registrationAccessToken')) {
                obj['registrationAccessToken'] = ApiClient.convertToType(data['registrationAccessToken'], 'String');
            }
            if (data.hasOwnProperty('clientIdIssuedAt')) {
                obj['clientIdIssuedAt'] = ApiClient.convertToType(data['clientIdIssuedAt'], 'Date');
            }
            if (data.hasOwnProperty('clientSecretExpiresAt')) {
                obj['clientSecretExpiresAt'] = ApiClient.convertToType(data['clientSecretExpiresAt'], 'Date');
            }
            if (data.hasOwnProperty('redirectUris')) {
                obj['redirectUris'] = ApiClient.convertToType(data['redirectUris'], ['String']);
            }
            if (data.hasOwnProperty('claimRedirectUris')) {
                obj['claimRedirectUris'] = ApiClient.convertToType(data['claimRedirectUris'], ['String']);
            }
            if (data.hasOwnProperty('responseTypes')) {
                obj['responseTypes'] = ApiClient.convertToType(data['responseTypes'], ['String']);
            }
            if (data.hasOwnProperty('grantTypes')) {
                obj['grantTypes'] = ApiClient.convertToType(data['grantTypes'], ['String']);
            }
            if (data.hasOwnProperty('applicationType')) {
                obj['applicationType'] = ApiClient.convertToType(data['applicationType'], 'String');
            }
            if (data.hasOwnProperty('contacts')) {
                obj['contacts'] = ApiClient.convertToType(data['contacts'], ['String']);
            }
            if (data.hasOwnProperty('clientName')) {
                obj['clientName'] = ApiClient.convertToType(data['clientName'], 'String');
            }
            if (data.hasOwnProperty('idTokenTokenBindingCnf')) {
                obj['idTokenTokenBindingCnf'] = ApiClient.convertToType(data['idTokenTokenBindingCnf'], 'String');
            }
            if (data.hasOwnProperty('logoUri')) {
                obj['logoUri'] = ApiClient.convertToType(data['logoUri'], 'String');
            }
            if (data.hasOwnProperty('clientUri')) {
                obj['clientUri'] = ApiClient.convertToType(data['clientUri'], 'String');
            }
            if (data.hasOwnProperty('policyUri')) {
                obj['policyUri'] = ApiClient.convertToType(data['policyUri'], 'String');
            }
            if (data.hasOwnProperty('tosUri')) {
                obj['tosUri'] = ApiClient.convertToType(data['tosUri'], 'String');
            }
            if (data.hasOwnProperty('jwksUri')) {
                obj['jwksUri'] = ApiClient.convertToType(data['jwksUri'], 'String');
            }
            if (data.hasOwnProperty('jwks')) {
                obj['jwks'] = ApiClient.convertToType(data['jwks'], 'String');
            }
            if (data.hasOwnProperty('sectorIdentifierUri')) {
                obj['sectorIdentifierUri'] = ApiClient.convertToType(data['sectorIdentifierUri'], 'String');
            }
            if (data.hasOwnProperty('subjectType')) {
                obj['subjectType'] = ApiClient.convertToType(data['subjectType'], 'String');
            }
            if (data.hasOwnProperty('idTokenSignedResponseAlg')) {
                obj['idTokenSignedResponseAlg'] = ApiClient.convertToType(data['idTokenSignedResponseAlg'], 'String');
            }
            if (data.hasOwnProperty('idTokenEncryptedResponseAlg')) {
                obj['idTokenEncryptedResponseAlg'] = ApiClient.convertToType(data['idTokenEncryptedResponseAlg'], 'String');
            }
            if (data.hasOwnProperty('idTokenEncryptedResponseEnc')) {
                obj['idTokenEncryptedResponseEnc'] = ApiClient.convertToType(data['idTokenEncryptedResponseEnc'], 'String');
            }
            if (data.hasOwnProperty('userInfoSignedResponseAlg')) {
                obj['userInfoSignedResponseAlg'] = ApiClient.convertToType(data['userInfoSignedResponseAlg'], 'String');
            }
            if (data.hasOwnProperty('userInfoEncryptedResponseAlg')) {
                obj['userInfoEncryptedResponseAlg'] = ApiClient.convertToType(data['userInfoEncryptedResponseAlg'], 'String');
            }
            if (data.hasOwnProperty('userInfoEncryptedResponseEnc')) {
                obj['userInfoEncryptedResponseEnc'] = ApiClient.convertToType(data['userInfoEncryptedResponseEnc'], 'String');
            }
            if (data.hasOwnProperty('requestObjectSigningAlg')) {
                obj['requestObjectSigningAlg'] = ApiClient.convertToType(data['requestObjectSigningAlg'], 'String');
            }
            if (data.hasOwnProperty('requestObjectEncryptionAlg')) {
                obj['requestObjectEncryptionAlg'] = ApiClient.convertToType(data['requestObjectEncryptionAlg'], 'String');
            }
            if (data.hasOwnProperty('requestObjectEncryptionEnc')) {
                obj['requestObjectEncryptionEnc'] = ApiClient.convertToType(data['requestObjectEncryptionEnc'], 'String');
            }
            if (data.hasOwnProperty('tokenEndpointAuthMethod')) {
                obj['tokenEndpointAuthMethod'] = ApiClient.convertToType(data['tokenEndpointAuthMethod'], 'String');
            }
            if (data.hasOwnProperty('tokenEndpointAuthSigningAlg')) {
                obj['tokenEndpointAuthSigningAlg'] = ApiClient.convertToType(data['tokenEndpointAuthSigningAlg'], 'String');
            }
            if (data.hasOwnProperty('defaultMaxAge')) {
                obj['defaultMaxAge'] = ApiClient.convertToType(data['defaultMaxAge'], 'Number');
            }
            if (data.hasOwnProperty('requireAuthTime')) {
                obj['requireAuthTime'] = ApiClient.convertToType(data['requireAuthTime'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultAcrValues')) {
                obj['defaultAcrValues'] = ApiClient.convertToType(data['defaultAcrValues'], ['String']);
            }
            if (data.hasOwnProperty('initiateLoginUri')) {
                obj['initiateLoginUri'] = ApiClient.convertToType(data['initiateLoginUri'], 'String');
            }
            if (data.hasOwnProperty('postLogoutRedirectUris')) {
                obj['postLogoutRedirectUris'] = ApiClient.convertToType(data['postLogoutRedirectUris'], ['String']);
            }
            if (data.hasOwnProperty('requestUris')) {
                obj['requestUris'] = ApiClient.convertToType(data['requestUris'], ['String']);
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
            if (data.hasOwnProperty('claims')) {
                obj['claims'] = ApiClient.convertToType(data['claims'], ['String']);
            }
            if (data.hasOwnProperty('trustedClient')) {
                obj['trustedClient'] = ApiClient.convertToType(data['trustedClient'], 'Boolean');
            }
            if (data.hasOwnProperty('lastAccessTime')) {
                obj['lastAccessTime'] = ApiClient.convertToType(data['lastAccessTime'], 'Date');
            }
            if (data.hasOwnProperty('lastLogonTime')) {
                obj['lastLogonTime'] = ApiClient.convertToType(data['lastLogonTime'], 'Date');
            }
            if (data.hasOwnProperty('persistClientAuthorizations')) {
                obj['persistClientAuthorizations'] = ApiClient.convertToType(data['persistClientAuthorizations'], 'Boolean');
            }
            if (data.hasOwnProperty('includeClaimsInIdToken')) {
                obj['includeClaimsInIdToken'] = ApiClient.convertToType(data['includeClaimsInIdToken'], 'Boolean');
            }
            if (data.hasOwnProperty('refreshTokenLifetime')) {
                obj['refreshTokenLifetime'] = ApiClient.convertToType(data['refreshTokenLifetime'], 'Number');
            }
            if (data.hasOwnProperty('accessTokenLifetime')) {
                obj['accessTokenLifetime'] = ApiClient.convertToType(data['accessTokenLifetime'], 'Number');
            }
            if (data.hasOwnProperty('customAttributes')) {
                obj['customAttributes'] = ApiClient.convertToType(data['customAttributes'], [CustomAttribute]);
            }
            if (data.hasOwnProperty('customObjectClasses')) {
                obj['customObjectClasses'] = ApiClient.convertToType(data['customObjectClasses'], ['String']);
            }
            if (data.hasOwnProperty('rptAsJwt')) {
                obj['rptAsJwt'] = ApiClient.convertToType(data['rptAsJwt'], 'Boolean');
            }
            if (data.hasOwnProperty('accessTokenAsJwt')) {
                obj['accessTokenAsJwt'] = ApiClient.convertToType(data['accessTokenAsJwt'], 'Boolean');
            }
            if (data.hasOwnProperty('accessTokenSigningAlg')) {
                obj['accessTokenSigningAlg'] = ApiClient.convertToType(data['accessTokenSigningAlg'], 'String');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('authorizedOrigins')) {
                obj['authorizedOrigins'] = ApiClient.convertToType(data['authorizedOrigins'], ['String']);
            }
            if (data.hasOwnProperty('softwareId')) {
                obj['softwareId'] = ApiClient.convertToType(data['softwareId'], 'String');
            }
            if (data.hasOwnProperty('softwareVersion')) {
                obj['softwareVersion'] = ApiClient.convertToType(data['softwareVersion'], 'String');
            }
            if (data.hasOwnProperty('softwareStatement')) {
                obj['softwareStatement'] = ApiClient.convertToType(data['softwareStatement'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ClientAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('backchannelTokenDeliveryMode')) {
                obj['backchannelTokenDeliveryMode'] = ApiClient.convertToType(data['backchannelTokenDeliveryMode'], 'String');
            }
            if (data.hasOwnProperty('backchannelClientNotificationEndpoint')) {
                obj['backchannelClientNotificationEndpoint'] = ApiClient.convertToType(data['backchannelClientNotificationEndpoint'], 'String');
            }
            if (data.hasOwnProperty('backchannelAuthenticationRequestSigningAlg')) {
                obj['backchannelAuthenticationRequestSigningAlg'] = ApiClient.convertToType(data['backchannelAuthenticationRequestSigningAlg'], 'String');
            }
            if (data.hasOwnProperty('backchannelUserCodeParameter')) {
                obj['backchannelUserCodeParameter'] = ApiClient.convertToType(data['backchannelUserCodeParameter'], 'Boolean');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
            if (data.hasOwnProperty('deletable')) {
                obj['deletable'] = ApiClient.convertToType(data['deletable'], 'Boolean');
            }
            if (data.hasOwnProperty('jansId')) {
                obj['jansId'] = ApiClient.convertToType(data['jansId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} dn
 */
Client.prototype['dn'] = undefined;

/**
 * XRI i-number. Client Identifier to uniquely identify the client.
 * @member {String} inum
 */
Client.prototype['inum'] = undefined;

/**
 * The client secret.  The client MAY omit the parameter if the client secret is an empty string.
 * @member {String} clientSecret
 */
Client.prototype['clientSecret'] = undefined;

/**
 * @member {String} frontChannelLogoutUri
 */
Client.prototype['frontChannelLogoutUri'] = undefined;

/**
 * @member {Boolean} frontChannelLogoutSessionRequired
 */
Client.prototype['frontChannelLogoutSessionRequired'] = undefined;

/**
 * @member {String} registrationAccessToken
 */
Client.prototype['registrationAccessToken'] = undefined;

/**
 * @member {Date} clientIdIssuedAt
 */
Client.prototype['clientIdIssuedAt'] = undefined;

/**
 * @member {Date} clientSecretExpiresAt
 */
Client.prototype['clientSecretExpiresAt'] = undefined;

/**
 * Redirection URI values used by the Client. One of these registered Redirection URI values must exactly match the redirect_uri parameter value used in each Authorization Request
 * @member {Array.<String>} redirectUris
 */
Client.prototype['redirectUris'] = undefined;

/**
 * Array of The Claims Redirect URIs to which the client wishes the authorization server to direct the requesting party's user agent after completing its interaction.
 * @member {Array.<String>} claimRedirectUris
 */
Client.prototype['claimRedirectUris'] = undefined;

/**
 * A list of the OAuth 2.0 response_type values that the Client is declaring that it will restrict itself to using. If omitted, the default is that the Client will use only the code Response Type. Allowed values are code, token, id_token.
 * @member {Array.<module:model/Client.ResponseTypesEnum>} responseTypes
 */
Client.prototype['responseTypes'] = undefined;

/**
 * A list of the OAuth 2.0 Grant Types that the Client is declaring that it will restrict itself to using.
 * @member {Array.<module:model/Client.GrantTypesEnum>} grantTypes
 */
Client.prototype['grantTypes'] = undefined;

/**
 * Kind of the application. The default, if omitted, is web. The defined values are native or web. Web Clients using the OAuth Implicit Grant Type must only register URLs using the HTTPS scheme as redirect_uris, they must not use localhost as the hostname. Native Clients must only register redirect_uris using custom URI schemes or URLs using the http scheme with localhost as the hostname.
 * @member {module:model/Client.ApplicationTypeEnum} applicationType
 */
Client.prototype['applicationType'] = undefined;

/**
 * e-mail addresses of people responsible for this Client.
 * @member {Array.<String>} contacts
 */
Client.prototype['contacts'] = undefined;

/**
 * A human-readable name of the client.
 * @member {String} clientName
 */
Client.prototype['clientName'] = undefined;

/**
 * Specifies the JWT Confirmation Method member name (e.g. tbh) that the Relying Party expects when receiving Token Bound ID Tokens. The presence of this parameter indicates that the Relying Party supports Token Binding of ID Tokens. If omitted, the default is that the Relying Party does not support Token Binding of ID Tokens.
 * @member {String} idTokenTokenBindingCnf
 */
Client.prototype['idTokenTokenBindingCnf'] = undefined;

/**
 * URL that references a logo for the Client application.
 * @member {String} logoUri
 */
Client.prototype['logoUri'] = undefined;

/**
 * URL of the home page of the Client. The value of this field must point to a valid Web page.
 * @member {String} clientUri
 */
Client.prototype['clientUri'] = undefined;

/**
 * URL that the Relying Party Client provides to the End-User to read about the how the profile data will be used.
 * @member {String} policyUri
 */
Client.prototype['policyUri'] = undefined;

/**
 * URL that the Relying Party Client provides to the End-User to read about the Relying Party's terms of service.
 * @member {String} tosUri
 */
Client.prototype['tosUri'] = undefined;

/**
 * URL for the Client's JSON Web Key Set (JWK) document containing key(s) that are used for signing requests to the OP. The JWK Set may also contain the Client's encryption keys(s) that are used by the OP to encrypt the responses to the Client. When both signing and encryption keys are made available, a use (Key Use) parameter value is required for all keys in the document to indicate each key's intended usage.
 * @member {String} jwksUri
 */
Client.prototype['jwksUri'] = undefined;

/**
 * List of JSON Web Key (JWK) - A JSON object that represents a cryptographic key. The members of the object represent properties of the key, including its value.
 * @member {String} jwks
 */
Client.prototype['jwks'] = undefined;

/**
 * URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP.
 * @member {String} sectorIdentifierUri
 */
Client.prototype['sectorIdentifierUri'] = undefined;

/**
 * Subject type requested for the Client ID. Valid types include pairwise and public.
 * @member {module:model/Client.SubjectTypeEnum} subjectType
 */
Client.prototype['subjectType'] = undefined;

/**
 * JWS alg algorithm (JWA) required for signing the ID Token issued to this Client.
 * @member {module:model/Client.IdTokenSignedResponseAlgEnum} idTokenSignedResponseAlg
 */
Client.prototype['idTokenSignedResponseAlg'] = undefined;

/**
 * JWE alg algorithm (JWA) required for encrypting the ID Token issued to this Client.
 * @member {module:model/Client.IdTokenEncryptedResponseAlgEnum} idTokenEncryptedResponseAlg
 */
Client.prototype['idTokenEncryptedResponseAlg'] = undefined;

/**
 * JWE enc algorithm (JWA) required for encrypting the ID Token issued to this Client.
 * @member {module:model/Client.IdTokenEncryptedResponseEncEnum} idTokenEncryptedResponseEnc
 */
Client.prototype['idTokenEncryptedResponseEnc'] = undefined;

/**
 * JWS alg algorithm (JWA) required for signing UserInfo Responses.
 * @member {module:model/Client.UserInfoSignedResponseAlgEnum} userInfoSignedResponseAlg
 */
Client.prototype['userInfoSignedResponseAlg'] = undefined;

/**
 * JWE alg algorithm (JWA) required for encrypting UserInfo Responses.
 * @member {module:model/Client.UserInfoEncryptedResponseAlgEnum} userInfoEncryptedResponseAlg
 */
Client.prototype['userInfoEncryptedResponseAlg'] = undefined;

/**
 * JWE enc algorithm (JWA) required for encrypting UserInfo Responses.
 * @member {module:model/Client.UserInfoEncryptedResponseEncEnum} userInfoEncryptedResponseEnc
 */
Client.prototype['userInfoEncryptedResponseEnc'] = undefined;

/**
 * JWS alg algorithm (JWA) that must be used for signing Request Objects sent to the OP.
 * @member {module:model/Client.RequestObjectSigningAlgEnum} requestObjectSigningAlg
 */
Client.prototype['requestObjectSigningAlg'] = undefined;

/**
 * JWE alg algorithm (JWA) the RP is declaring that it may use for encrypting Request Objects sent to the OP.
 * @member {module:model/Client.RequestObjectEncryptionAlgEnum} requestObjectEncryptionAlg
 */
Client.prototype['requestObjectEncryptionAlg'] = undefined;

/**
 * JWE enc algorithm (JWA) the RP is declaring that it may use for encrypting Request Objects sent to the OP.
 * @member {module:model/Client.RequestObjectEncryptionEncEnum} requestObjectEncryptionEnc
 */
Client.prototype['requestObjectEncryptionEnc'] = undefined;

/**
 * Requested Client Authentication method for the Token Endpoint.
 * @member {module:model/Client.TokenEndpointAuthMethodEnum} tokenEndpointAuthMethod
 */
Client.prototype['tokenEndpointAuthMethod'] = undefined;

/**
 * JWS alg algorithm (JWA) that must be used for signing the JWT used to authenticate the Client at the Token Endpoint for the private_key_jwt and client_secret_jwt authentication methods.
 * @member {module:model/Client.TokenEndpointAuthSigningAlgEnum} tokenEndpointAuthSigningAlg
 */
Client.prototype['tokenEndpointAuthSigningAlg'] = undefined;

/**
 * Specifies the Default Maximum Authentication Age.
 * @member {Number} defaultMaxAge
 */
Client.prototype['defaultMaxAge'] = undefined;

/**
 * Boolean value specifying whether the auth_time Claim in the ID Token is required. It is required when the value is true.
 * @member {Boolean} requireAuthTime
 */
Client.prototype['requireAuthTime'] = undefined;

/**
 * Array of default requested Authentication Context Class Reference values that the Authorization Server must use for processing requests from the Client.
 * @member {Array.<String>} defaultAcrValues
 */
Client.prototype['defaultAcrValues'] = undefined;

/**
 * Specifies the URI using the https scheme that the authorization server can call to initiate a login at the client.
 * @member {String} initiateLoginUri
 */
Client.prototype['initiateLoginUri'] = undefined;

/**
 * Provide the URLs supplied by the RP to request that the user be redirected to this location after a logout has been performed.
 * @member {Array.<String>} postLogoutRedirectUris
 */
Client.prototype['postLogoutRedirectUris'] = undefined;

/**
 * Provide a list of requests_uri values that are pre-registered by the Client for use at the Authorization Server.
 * @member {Array.<String>} requestUris
 */
Client.prototype['requestUris'] = undefined;

/**
 * Provide list of scopes granted to the client.
 * @member {Array.<String>} scopes
 */
Client.prototype['scopes'] = undefined;

/**
 * Provide list of claims granted to the client.
 * @member {Array.<String>} claims
 */
Client.prototype['claims'] = undefined;

/**
 * Attribute which corresponds to the \"Pre-Authorization\" property. Default value is false.
 * @member {Boolean} trustedClient
 * @default false
 */
Client.prototype['trustedClient'] = false;

/**
 * Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating last access time.
 * @member {Date} lastAccessTime
 */
Client.prototype['lastAccessTime'] = undefined;

/**
 * Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating last login time.
 * @member {Date} lastLogonTime
 */
Client.prototype['lastLogonTime'] = undefined;

/**
 * Specifies if the client authorization details are to be persisted. Default value is true.
 * @member {Boolean} persistClientAuthorizations
 */
Client.prototype['persistClientAuthorizations'] = undefined;

/**
 * If true then claims are included in token id, default value is false.
 * @member {Boolean} includeClaimsInIdToken
 * @default false
 */
Client.prototype['includeClaimsInIdToken'] = false;

/**
 * Specifies the Client-specific refresh token expiration.
 * @member {Number} refreshTokenLifetime
 */
Client.prototype['refreshTokenLifetime'] = undefined;

/**
 * Specifies the Client-specific access token expiration.
 * @member {Number} accessTokenLifetime
 */
Client.prototype['accessTokenLifetime'] = undefined;

/**
 * @member {Array.<module:model/CustomAttribute>} customAttributes
 */
Client.prototype['customAttributes'] = undefined;

/**
 * @member {Array.<String>} customObjectClasses
 */
Client.prototype['customObjectClasses'] = undefined;

/**
 * Specifies whether RPT should be return as signed JWT.
 * @member {Boolean} rptAsJwt
 */
Client.prototype['rptAsJwt'] = undefined;

/**
 * Specifies whether access token as signed JWT.
 * @member {Boolean} accessTokenAsJwt
 */
Client.prototype['accessTokenAsJwt'] = undefined;

/**
 * Specifies signing algorithm that has to be used during JWT signing. If it's not specified, then the default OP signing algorithm will be used.
 * @member {module:model/Client.AccessTokenSigningAlgEnum} accessTokenSigningAlg
 */
Client.prototype['accessTokenSigningAlg'] = undefined;

/**
 * Specifies whether client is disabled.
 * @member {Boolean} disabled
 * @default false
 */
Client.prototype['disabled'] = false;

/**
 * Specifies authorized JavaScript origins.
 * @member {Array.<String>} authorizedOrigins
 */
Client.prototype['authorizedOrigins'] = undefined;

/**
 * Specifies a unique identifier string (UUID) assigned by the client developer or software publisher used by registration endpoints to identify the client software to be dynamically registered.
 * @member {String} softwareId
 */
Client.prototype['softwareId'] = undefined;

/**
 * Specifies a version identifier string for the client software identified by 'software_id'. The value of the 'software_version' should change on any update to the client software identified by the same 'software_id'.
 * @member {String} softwareVersion
 */
Client.prototype['softwareVersion'] = undefined;

/**
 * Specifies a software statement containing client metadata values about the client software as claims. This is a string value containing the entire signed JWT.
 * @member {String} softwareStatement
 */
Client.prototype['softwareStatement'] = undefined;

/**
 * @member {module:model/ClientAttributes} attributes
 */
Client.prototype['attributes'] = undefined;

/**
 * specifies how backchannel token will be delivered.
 * @member {module:model/Client.BackchannelTokenDeliveryModeEnum} backchannelTokenDeliveryMode
 */
Client.prototype['backchannelTokenDeliveryMode'] = undefined;

/**
 * Client Initiated Backchannel Authentication (CIBA) enables a Client to initiate the authentication of an end-user by means of out-of-band mechanisms. Upon receipt of the notification, the Client makes a request to the token endpoint to obtain the tokens.
 * @member {String} backchannelClientNotificationEndpoint
 */
Client.prototype['backchannelClientNotificationEndpoint'] = undefined;

/**
 * The JWS algorithm alg value that the Client will use for signing authentication request, as described in Section 7.1.1. of OAuth 2.0 [RFC6749]. When omitted, the Client will not send signed authentication requests.
 * @member {module:model/Client.BackchannelAuthenticationRequestSigningAlgEnum} backchannelAuthenticationRequestSigningAlg
 */
Client.prototype['backchannelAuthenticationRequestSigningAlg'] = undefined;

/**
 * Boolean value specifying whether the Client supports the user_code parameter. If omitted, the default value is false.
 * @member {Boolean} backchannelUserCodeParameter
 */
Client.prototype['backchannelUserCodeParameter'] = undefined;

/**
 * Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this permission will expire.
 * @member {Date} expirationDate
 */
Client.prototype['expirationDate'] = undefined;

/**
 * Specifies whether client is deletable.
 * @member {Boolean} deletable
 * @default false
 */
Client.prototype['deletable'] = false;

/**
 * Attribute Scope Id.
 * @member {String} jansId
 */
Client.prototype['jansId'] = undefined;





/**
 * Allowed values for the <code>responseTypes</code> property.
 * @enum {String}
 * @readonly
 */
Client['ResponseTypesEnum'] = {

    /**
     * value: "code"
     * @const
     */
    "code": "code",

    /**
     * value: "token"
     * @const
     */
    "token": "token",

    /**
     * value: "id_token"
     * @const
     */
    "id_token": "id_token"
};


/**
 * Allowed values for the <code>grantTypes</code> property.
 * @enum {String}
 * @readonly
 */
Client['GrantTypesEnum'] = {

    /**
     * value: "authorization_code"
     * @const
     */
    "authorization_code": "authorization_code",

    /**
     * value: "implicit"
     * @const
     */
    "implicit": "implicit",

    /**
     * value: "password"
     * @const
     */
    "password": "password",

    /**
     * value: "client_credentials"
     * @const
     */
    "client_credentials": "client_credentials",

    /**
     * value: "refresh_token"
     * @const
     */
    "refresh_token": "refresh_token",

    /**
     * value: "urn:ietf:params:oauth:grant-type:uma-ticket"
     * @const
     */
    "urn:ietf:params:oauth:grant-type:uma-ticket": "urn:ietf:params:oauth:grant-type:uma-ticket",

    /**
     * value: "urn:openid:params:grant-type:ciba"
     * @const
     */
    "urn:openid:params:grant-type:ciba": "urn:openid:params:grant-type:ciba",

    /**
     * value: "urn:ietf:params:oauth:grant-type:device_code"
     * @const
     */
    "urn:ietf:params:oauth:grant-type:device_code": "urn:ietf:params:oauth:grant-type:device_code"
};


/**
 * Allowed values for the <code>applicationType</code> property.
 * @enum {String}
 * @readonly
 */
Client['ApplicationTypeEnum'] = {

    /**
     * value: "web"
     * @const
     */
    "web": "web",

    /**
     * value: "native"
     * @const
     */
    "native": "native"
};


/**
 * Allowed values for the <code>subjectType</code> property.
 * @enum {String}
 * @readonly
 */
Client['SubjectTypeEnum'] = {

    /**
     * value: "pairwise"
     * @const
     */
    "pairwise": "pairwise",

    /**
     * value: "public"
     * @const
     */
    "public": "public"
};


/**
 * Allowed values for the <code>idTokenSignedResponseAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['IdTokenSignedResponseAlgEnum'] = {

    /**
     * value: "HS256"
     * @const
     */
    "HS256": "HS256",

    /**
     * value: "HS384"
     * @const
     */
    "HS384": "HS384",

    /**
     * value: "HS512"
     * @const
     */
    "HS512": "HS512",

    /**
     * value: "RS256"
     * @const
     */
    "RS256": "RS256",

    /**
     * value: "RS384"
     * @const
     */
    "RS384": "RS384",

    /**
     * value: "RS512"
     * @const
     */
    "RS512": "RS512",

    /**
     * value: "ES256"
     * @const
     */
    "ES256": "ES256",

    /**
     * value: "ES384"
     * @const
     */
    "ES384": "ES384",

    /**
     * value: "ES512"
     * @const
     */
    "ES512": "ES512",

    /**
     * value: "PS256"
     * @const
     */
    "PS256": "PS256",

    /**
     * value: "PS384"
     * @const
     */
    "PS384": "PS384",

    /**
     * value: "PS512"
     * @const
     */
    "PS512": "PS512"
};


/**
 * Allowed values for the <code>idTokenEncryptedResponseAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['IdTokenEncryptedResponseAlgEnum'] = {

    /**
     * value: "RSA1_5"
     * @const
     */
    "RSA1_5": "RSA1_5",

    /**
     * value: "RSA-OAEP"
     * @const
     */
    "RSA-OAEP": "RSA-OAEP",

    /**
     * value: "A128KW"
     * @const
     */
    "A128KW": "A128KW",

    /**
     * value: "A256KW"
     * @const
     */
    "A256KW": "A256KW"
};


/**
 * Allowed values for the <code>idTokenEncryptedResponseEnc</code> property.
 * @enum {String}
 * @readonly
 */
Client['IdTokenEncryptedResponseEncEnum'] = {

    /**
     * value: "A128CBC+HS256"
     * @const
     */
    "A128CBC+HS256": "A128CBC+HS256",

    /**
     * value: "A256CBC+HS512"
     * @const
     */
    "A256CBC+HS512": "A256CBC+HS512",

    /**
     * value: "A128GCM"
     * @const
     */
    "A128GCM": "A128GCM",

    /**
     * value: "A256GCM"
     * @const
     */
    "A256GCM": "A256GCM"
};


/**
 * Allowed values for the <code>userInfoSignedResponseAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['UserInfoSignedResponseAlgEnum'] = {

    /**
     * value: "HS256"
     * @const
     */
    "HS256": "HS256",

    /**
     * value: "HS384"
     * @const
     */
    "HS384": "HS384",

    /**
     * value: "HS512"
     * @const
     */
    "HS512": "HS512",

    /**
     * value: "RS256"
     * @const
     */
    "RS256": "RS256",

    /**
     * value: "RS384"
     * @const
     */
    "RS384": "RS384",

    /**
     * value: "RS512"
     * @const
     */
    "RS512": "RS512",

    /**
     * value: "ES256"
     * @const
     */
    "ES256": "ES256",

    /**
     * value: "ES384"
     * @const
     */
    "ES384": "ES384",

    /**
     * value: "ES512"
     * @const
     */
    "ES512": "ES512",

    /**
     * value: "PS256"
     * @const
     */
    "PS256": "PS256",

    /**
     * value: "PS384"
     * @const
     */
    "PS384": "PS384",

    /**
     * value: "PS512"
     * @const
     */
    "PS512": "PS512"
};


/**
 * Allowed values for the <code>userInfoEncryptedResponseAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['UserInfoEncryptedResponseAlgEnum'] = {

    /**
     * value: "RSA1_5"
     * @const
     */
    "RSA1_5": "RSA1_5",

    /**
     * value: "RSA-OAEP"
     * @const
     */
    "RSA-OAEP": "RSA-OAEP",

    /**
     * value: "A128KW"
     * @const
     */
    "A128KW": "A128KW",

    /**
     * value: "A256KW"
     * @const
     */
    "A256KW": "A256KW"
};


/**
 * Allowed values for the <code>userInfoEncryptedResponseEnc</code> property.
 * @enum {String}
 * @readonly
 */
Client['UserInfoEncryptedResponseEncEnum'] = {

    /**
     * value: "A128CBC+HS256"
     * @const
     */
    "A128CBC+HS256": "A128CBC+HS256",

    /**
     * value: "A256CBC+HS512"
     * @const
     */
    "A256CBC+HS512": "A256CBC+HS512",

    /**
     * value: "A128GCM"
     * @const
     */
    "A128GCM": "A128GCM",

    /**
     * value: "A256GCM"
     * @const
     */
    "A256GCM": "A256GCM"
};


/**
 * Allowed values for the <code>requestObjectSigningAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['RequestObjectSigningAlgEnum'] = {

    /**
     * value: "HS256"
     * @const
     */
    "HS256": "HS256",

    /**
     * value: "HS384"
     * @const
     */
    "HS384": "HS384",

    /**
     * value: "HS512"
     * @const
     */
    "HS512": "HS512",

    /**
     * value: "RS256"
     * @const
     */
    "RS256": "RS256",

    /**
     * value: "RS384"
     * @const
     */
    "RS384": "RS384",

    /**
     * value: "RS512"
     * @const
     */
    "RS512": "RS512",

    /**
     * value: "ES256"
     * @const
     */
    "ES256": "ES256",

    /**
     * value: "ES384"
     * @const
     */
    "ES384": "ES384",

    /**
     * value: "ES512"
     * @const
     */
    "ES512": "ES512",

    /**
     * value: "PS256"
     * @const
     */
    "PS256": "PS256",

    /**
     * value: "PS384"
     * @const
     */
    "PS384": "PS384",

    /**
     * value: "PS512"
     * @const
     */
    "PS512": "PS512"
};


/**
 * Allowed values for the <code>requestObjectEncryptionAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['RequestObjectEncryptionAlgEnum'] = {

    /**
     * value: "RSA1_5"
     * @const
     */
    "RSA1_5": "RSA1_5",

    /**
     * value: "RSA-OAEP"
     * @const
     */
    "RSA-OAEP": "RSA-OAEP",

    /**
     * value: "A128KW"
     * @const
     */
    "A128KW": "A128KW",

    /**
     * value: "A256KW"
     * @const
     */
    "A256KW": "A256KW"
};


/**
 * Allowed values for the <code>requestObjectEncryptionEnc</code> property.
 * @enum {String}
 * @readonly
 */
Client['RequestObjectEncryptionEncEnum'] = {

    /**
     * value: "A128CBC+HS256"
     * @const
     */
    "A128CBC+HS256": "A128CBC+HS256",

    /**
     * value: "A256CBC+HS512"
     * @const
     */
    "A256CBC+HS512": "A256CBC+HS512",

    /**
     * value: "A128GCM"
     * @const
     */
    "A128GCM": "A128GCM",

    /**
     * value: "A256GCM"
     * @const
     */
    "A256GCM": "A256GCM"
};


/**
 * Allowed values for the <code>tokenEndpointAuthMethod</code> property.
 * @enum {String}
 * @readonly
 */
Client['TokenEndpointAuthMethodEnum'] = {

    /**
     * value: "client_secret_basic"
     * @const
     */
    "client_secret_basic": "client_secret_basic",

    /**
     * value: "client_secret_post"
     * @const
     */
    "client_secret_post": "client_secret_post",

    /**
     * value: "client_secret_jwt"
     * @const
     */
    "client_secret_jwt": "client_secret_jwt",

    /**
     * value: "private_key_jwt"
     * @const
     */
    "private_key_jwt": "private_key_jwt",

    /**
     * value: "none"
     * @const
     */
    "none": "none"
};


/**
 * Allowed values for the <code>tokenEndpointAuthSigningAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['TokenEndpointAuthSigningAlgEnum'] = {

    /**
     * value: "HS256"
     * @const
     */
    "HS256": "HS256",

    /**
     * value: "HS384"
     * @const
     */
    "HS384": "HS384",

    /**
     * value: "HS512"
     * @const
     */
    "HS512": "HS512",

    /**
     * value: "RS256"
     * @const
     */
    "RS256": "RS256",

    /**
     * value: "RS384"
     * @const
     */
    "RS384": "RS384",

    /**
     * value: "RS512"
     * @const
     */
    "RS512": "RS512",

    /**
     * value: "ES256"
     * @const
     */
    "ES256": "ES256",

    /**
     * value: "ES384"
     * @const
     */
    "ES384": "ES384",

    /**
     * value: "ES512"
     * @const
     */
    "ES512": "ES512",

    /**
     * value: "PS256"
     * @const
     */
    "PS256": "PS256",

    /**
     * value: "PS384"
     * @const
     */
    "PS384": "PS384",

    /**
     * value: "PS512"
     * @const
     */
    "PS512": "PS512"
};


/**
 * Allowed values for the <code>accessTokenSigningAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['AccessTokenSigningAlgEnum'] = {

    /**
     * value: "HS256"
     * @const
     */
    "HS256": "HS256",

    /**
     * value: "HS384"
     * @const
     */
    "HS384": "HS384",

    /**
     * value: "HS512"
     * @const
     */
    "HS512": "HS512",

    /**
     * value: "RS256"
     * @const
     */
    "RS256": "RS256",

    /**
     * value: "RS384"
     * @const
     */
    "RS384": "RS384",

    /**
     * value: "RS512"
     * @const
     */
    "RS512": "RS512",

    /**
     * value: "ES256"
     * @const
     */
    "ES256": "ES256",

    /**
     * value: "ES384"
     * @const
     */
    "ES384": "ES384",

    /**
     * value: "ES512"
     * @const
     */
    "ES512": "ES512",

    /**
     * value: "PS256"
     * @const
     */
    "PS256": "PS256",

    /**
     * value: "PS384"
     * @const
     */
    "PS384": "PS384",

    /**
     * value: "PS512"
     * @const
     */
    "PS512": "PS512"
};


/**
 * Allowed values for the <code>backchannelTokenDeliveryMode</code> property.
 * @enum {String}
 * @readonly
 */
Client['BackchannelTokenDeliveryModeEnum'] = {

    /**
     * value: "poll"
     * @const
     */
    "poll": "poll",

    /**
     * value: "ping"
     * @const
     */
    "ping": "ping",

    /**
     * value: "push"
     * @const
     */
    "push": "push"
};


/**
 * Allowed values for the <code>backchannelAuthenticationRequestSigningAlg</code> property.
 * @enum {String}
 * @readonly
 */
Client['BackchannelAuthenticationRequestSigningAlgEnum'] = {

    /**
     * value: "RS256"
     * @const
     */
    "RS256": "RS256",

    /**
     * value: "RS384"
     * @const
     */
    "RS384": "RS384",

    /**
     * value: "RS512"
     * @const
     */
    "RS512": "RS512",

    /**
     * value: "ES256"
     * @const
     */
    "ES256": "ES256",

    /**
     * value: "ES384"
     * @const
     */
    "ES384": "ES384",

    /**
     * value: "ES512"
     * @const
     */
    "ES512": "ES512",

    /**
     * value: "PS256"
     * @const
     */
    "PS256": "PS256",

    /**
     * value: "PS384"
     * @const
     */
    "PS384": "PS384",

    /**
     * value: "PS512"
     * @const
     */
    "PS512": "PS512"
};



export default Client;

