/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomAttribute model module.
 * @module model/CustomAttribute
 * @version 1.0.0
 */
class CustomAttribute {
    /**
     * Constructs a new <code>CustomAttribute</code>.
     * Attribute.
     * @alias module:model/CustomAttribute
     * @param name {String} Name of the attribute.
     * @param multiValued {Boolean} Indicates if the attribute can hold multiple values.
     * @param values {Array.<String>} 
     */
    constructor(name, multiValued, values) { 
        
        CustomAttribute.initialize(this, name, multiValued, values);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, multiValued, values) { 
        obj['name'] = name;
        obj['multiValued'] = multiValued;
        obj['values'] = values;
    }

    /**
     * Constructs a <code>CustomAttribute</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomAttribute} obj Optional instance to populate.
     * @return {module:model/CustomAttribute} The populated <code>CustomAttribute</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomAttribute();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('multiValued')) {
                obj['multiValued'] = ApiClient.convertToType(data['multiValued'], 'Boolean');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Name of the attribute.
 * @member {String} name
 */
CustomAttribute.prototype['name'] = undefined;

/**
 * Indicates if the attribute can hold multiple values.
 * @member {Boolean} multiValued
 */
CustomAttribute.prototype['multiValued'] = undefined;

/**
 * @member {Array.<String>} values
 */
CustomAttribute.prototype['values'] = undefined;






export default CustomAttribute;

