/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JsonWebKey model module.
 * @module model/JsonWebKey
 * @version 1.0.0
 */
class JsonWebKey {
    /**
     * Constructs a new <code>JsonWebKey</code>.
     * JsonWebKey
     * @alias module:model/JsonWebKey
     */
    constructor() { 
        
        JsonWebKey.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JsonWebKey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JsonWebKey} obj Optional instance to populate.
     * @return {module:model/JsonWebKey} The populated <code>JsonWebKey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JsonWebKey();

            if (data.hasOwnProperty('kid')) {
                obj['kid'] = ApiClient.convertToType(data['kid'], 'String');
            }
            if (data.hasOwnProperty('kty')) {
                obj['kty'] = ApiClient.convertToType(data['kty'], 'String');
            }
            if (data.hasOwnProperty('use')) {
                obj['use'] = ApiClient.convertToType(data['use'], 'String');
            }
            if (data.hasOwnProperty('alg')) {
                obj['alg'] = ApiClient.convertToType(data['alg'], 'String');
            }
            if (data.hasOwnProperty('crv')) {
                obj['crv'] = ApiClient.convertToType(data['crv'], 'String');
            }
            if (data.hasOwnProperty('exp')) {
                obj['exp'] = ApiClient.convertToType(data['exp'], 'Number');
            }
            if (data.hasOwnProperty('x5c')) {
                obj['x5c'] = ApiClient.convertToType(data['x5c'], ['String']);
            }
            if (data.hasOwnProperty('n')) {
                obj['n'] = ApiClient.convertToType(data['n'], 'String');
            }
            if (data.hasOwnProperty('e')) {
                obj['e'] = ApiClient.convertToType(data['e'], 'String');
            }
            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'String');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The unique identifier for the key.
 * @member {String} kid
 */
JsonWebKey.prototype['kid'] = undefined;

/**
 * The family of cryptographic algorithms used with the key.
 * @member {String} kty
 */
JsonWebKey.prototype['kty'] = undefined;

/**
 * How the key was meant to be used; sig represents the signature.
 * @member {String} use
 */
JsonWebKey.prototype['use'] = undefined;

/**
 * The specific cryptographic algorithm used with the key.
 * @member {String} alg
 */
JsonWebKey.prototype['alg'] = undefined;

/**
 * The crv member identifies the cryptographic curve used with the key. Values defined by this specification are P-256, P-384 and P-521. Additional crv values MAY be used, provided they are understood by implementations using that Elliptic Curve key. The crv value is case sensitive.
 * @member {String} crv
 */
JsonWebKey.prototype['crv'] = undefined;

/**
 * Contains the token expiration timestamp
 * @member {Number} exp
 */
JsonWebKey.prototype['exp'] = undefined;

/**
 * The x.509 certificate chain. The first entry in the array is the certificate to use for token verification; the other certificates can be used to verify this first certificate.
 * @member {Array.<String>} x5c
 */
JsonWebKey.prototype['x5c'] = undefined;

/**
 * The modulus for the RSA public key.
 * @member {String} n
 */
JsonWebKey.prototype['n'] = undefined;

/**
 * The exponent for the RSA public key.
 * @member {String} e
 */
JsonWebKey.prototype['e'] = undefined;

/**
 * The x member contains the x coordinate for the elliptic curve point. It is represented as the base64url encoding of the coordinate's big endian representation.
 * @member {String} x
 */
JsonWebKey.prototype['x'] = undefined;

/**
 * The y member contains the y coordinate for the elliptic curve point. It is represented as the base64url encoding of the coordinate's big endian representation.
 * @member {String} y
 */
JsonWebKey.prototype['y'] = undefined;






export default JsonWebKey;

