/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestedParties model module.
 * @module model/RequestedParties
 * @version 1.0.0
 */
class RequestedParties {
    /**
     * Constructs a new <code>RequestedParties</code>.
     * Credential Type.
     * @alias module:model/RequestedParties
     */
    constructor() { 
        
        RequestedParties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequestedParties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestedParties} obj Optional instance to populate.
     * @return {module:model/RequestedParties} The populated <code>RequestedParties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestedParties();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('domains')) {
                obj['domains'] = ApiClient.convertToType(data['domains'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Name of the Requested Party.
 * @member {String} name
 */
RequestedParties.prototype['name'] = undefined;

/**
 * Requested Party domains.
 * @member {Array.<String>} domains
 */
RequestedParties.prototype['domains'] = undefined;






export default RequestedParties;

