/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScopeAttributes from './ScopeAttributes';

/**
 * The Scope model module.
 * @module model/Scope
 * @version 1.0.0
 */
class Scope {
    /**
     * Constructs a new <code>Scope</code>.
     * Auth Scope.
     * @alias module:model/Scope
     * @param displayName {String} A human-readable name of the scope.
     * @param id {String} The base64url encoded id.
     * @param description {String} A human-readable string describing the scope.
     * @param scopeType {module:model/Scope.ScopeTypeEnum} The scopes type associated with Access Tokens determine what resources will.
     */
    constructor(displayName, id, description, scopeType) { 
        
        Scope.initialize(this, displayName, id, description, scopeType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, displayName, id, description, scopeType) { 
        obj['displayName'] = displayName;
        obj['id'] = id;
        obj['description'] = description;
        obj['scopeType'] = scopeType;
    }

    /**
     * Constructs a <code>Scope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Scope} obj Optional instance to populate.
     * @return {module:model/Scope} The populated <code>Scope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Scope();

            if (data.hasOwnProperty('dn')) {
                obj['dn'] = ApiClient.convertToType(data['dn'], 'String');
            }
            if (data.hasOwnProperty('inum')) {
                obj['inum'] = ApiClient.convertToType(data['inum'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('iconUrl')) {
                obj['iconUrl'] = ApiClient.convertToType(data['iconUrl'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('scopeType')) {
                obj['scopeType'] = ApiClient.convertToType(data['scopeType'], 'String');
            }
            if (data.hasOwnProperty('claims')) {
                obj['claims'] = ApiClient.convertToType(data['claims'], ['String']);
            }
            if (data.hasOwnProperty('defaultScope')) {
                obj['defaultScope'] = ApiClient.convertToType(data['defaultScope'], 'Boolean');
            }
            if (data.hasOwnProperty('groupClaims')) {
                obj['groupClaims'] = ApiClient.convertToType(data['groupClaims'], 'Boolean');
            }
            if (data.hasOwnProperty('dynamicScopeScripts')) {
                obj['dynamicScopeScripts'] = ApiClient.convertToType(data['dynamicScopeScripts'], ['String']);
            }
            if (data.hasOwnProperty('umaAuthorizationPolicies')) {
                obj['umaAuthorizationPolicies'] = ApiClient.convertToType(data['umaAuthorizationPolicies'], ['String']);
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ScopeAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('umaType')) {
                obj['umaType'] = ApiClient.convertToType(data['umaType'], 'Boolean');
            }
            if (data.hasOwnProperty('deletable')) {
                obj['deletable'] = ApiClient.convertToType(data['deletable'], 'Boolean');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} dn
 */
Scope.prototype['dn'] = undefined;

/**
 * Unique id identifying the .
 * @member {String} inum
 */
Scope.prototype['inum'] = undefined;

/**
 * A human-readable name of the scope.
 * @member {String} displayName
 */
Scope.prototype['displayName'] = undefined;

/**
 * The base64url encoded id.
 * @member {String} id
 */
Scope.prototype['id'] = undefined;

/**
 * A URL for a graphic icon representing the scope. The referenced icon MAY be used by the authorization server in any user interface it presents to the resource owner.
 * @member {String} iconUrl
 */
Scope.prototype['iconUrl'] = undefined;

/**
 * A human-readable string describing the scope.
 * @member {String} description
 */
Scope.prototype['description'] = undefined;

/**
 * The scopes type associated with Access Tokens determine what resources will.
 * @member {module:model/Scope.ScopeTypeEnum} scopeType
 */
Scope.prototype['scopeType'] = undefined;

/**
 * Claim attributes associated with the scope.
 * @member {Array.<String>} claims
 */
Scope.prototype['claims'] = undefined;

/**
 * Boolean value to specify default scope.
 * @member {Boolean} defaultScope
 */
Scope.prototype['defaultScope'] = undefined;

/**
 * Specifies if the scope is group claims.
 * @member {Boolean} groupClaims
 */
Scope.prototype['groupClaims'] = undefined;

/**
 * Dynamic Scope Scripts associated with the scope.
 * @member {Array.<String>} dynamicScopeScripts
 */
Scope.prototype['dynamicScopeScripts'] = undefined;

/**
 * Policies associated with scopes.
 * @member {Array.<String>} umaAuthorizationPolicies
 */
Scope.prototype['umaAuthorizationPolicies'] = undefined;

/**
 * @member {module:model/ScopeAttributes} attributes
 */
Scope.prototype['attributes'] = undefined;

/**
 * Specifies if the scope is of type UMA.
 * @member {Boolean} umaType
 * @default false
 */
Scope.prototype['umaType'] = false;

/**
 * Specifies if the scope can be deleted.
 * @member {Boolean} deletable
 * @default false
 */
Scope.prototype['deletable'] = false;

/**
 * Expiry date of the Scope.
 * @member {Date} expirationDate
 */
Scope.prototype['expirationDate'] = undefined;





/**
 * Allowed values for the <code>scopeType</code> property.
 * @enum {String}
 * @readonly
 */
Scope['ScopeTypeEnum'] = {

    /**
     * value: "openid"
     * @const
     */
    "openid": "openid",

    /**
     * value: "dynamic"
     * @const
     */
    "dynamic": "dynamic",

    /**
     * value: "uma"
     * @const
     */
    "uma": "uma",

    /**
     * value: "spontaneous"
     * @const
     */
    "spontaneous": "spontaneous",

    /**
     * value: "oauth"
     * @const
     */
    "oauth": "oauth"
};



export default Scope;

