/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SimpleCustomProperty model module.
 * @module model/SimpleCustomProperty
 * @version 1.0.0
 */
class SimpleCustomProperty {
    /**
     * Constructs a new <code>SimpleCustomProperty</code>.
     * Simple Property.
     * @alias module:model/SimpleCustomProperty
     */
    constructor() { 
        
        SimpleCustomProperty.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SimpleCustomProperty</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SimpleCustomProperty} obj Optional instance to populate.
     * @return {module:model/SimpleCustomProperty} The populated <code>SimpleCustomProperty</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleCustomProperty();

            if (data.hasOwnProperty('value1')) {
                obj['value1'] = ApiClient.convertToType(data['value1'], 'String');
            }
            if (data.hasOwnProperty('value2')) {
                obj['value2'] = ApiClient.convertToType(data['value2'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} value1
 */
SimpleCustomProperty.prototype['value1'] = undefined;

/**
 * @member {String} value2
 */
SimpleCustomProperty.prototype['value2'] = undefined;

/**
 * @member {String} description
 */
SimpleCustomProperty.prototype['description'] = undefined;






export default SimpleCustomProperty;

