/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UmaResource model module.
 * @module model/UmaResource
 * @version 1.0.0
 */
class UmaResource {
    /**
     * Constructs a new <code>UmaResource</code>.
     * UMAResource
     * @alias module:model/UmaResource
     * @param id {String} Resource id.
     * @param iconUri {String} A URL for a graphic icon representing the resource.
     * @param type {String} Resource type.
     */
    constructor(id, iconUri, type) { 
        
        UmaResource.initialize(this, id, iconUri, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, iconUri, type) { 
        obj['id'] = id;
        obj['iconUri'] = iconUri;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>UmaResource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UmaResource} obj Optional instance to populate.
     * @return {module:model/UmaResource} The populated <code>UmaResource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UmaResource();

            if (data.hasOwnProperty('dn')) {
                obj['dn'] = ApiClient.convertToType(data['dn'], 'String');
            }
            if (data.hasOwnProperty('inum')) {
                obj['inum'] = ApiClient.convertToType(data['inum'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('iconUri')) {
                obj['iconUri'] = ApiClient.convertToType(data['iconUri'], 'String');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
            if (data.hasOwnProperty('scopeExpression')) {
                obj['scopeExpression'] = ApiClient.convertToType(data['scopeExpression'], 'String');
            }
            if (data.hasOwnProperty('clients')) {
                obj['clients'] = ApiClient.convertToType(data['clients'], ['String']);
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], ['String']);
            }
            if (data.hasOwnProperty('rev')) {
                obj['rev'] = ApiClient.convertToType(data['rev'], 'String');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
            if (data.hasOwnProperty('deletable')) {
                obj['deletable'] = ApiClient.convertToType(data['deletable'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} dn
 */
UmaResource.prototype['dn'] = undefined;

/**
 * XRI i-number. Client Identifier to uniquely identify the UMAResource.
 * @member {String} inum
 */
UmaResource.prototype['inum'] = undefined;

/**
 * Resource id.
 * @member {String} id
 */
UmaResource.prototype['id'] = undefined;

/**
 * A human-readable name of the scope.
 * @member {String} name
 */
UmaResource.prototype['name'] = undefined;

/**
 * A URL for a graphic icon representing the resource.
 * @member {String} iconUri
 */
UmaResource.prototype['iconUri'] = undefined;

/**
 * Applicable resource scopes.
 * @member {Array.<String>} scopes
 */
UmaResource.prototype['scopes'] = undefined;

/**
 * Resource scope expression.
 * @member {String} scopeExpression
 */
UmaResource.prototype['scopeExpression'] = undefined;

/**
 * List of client assosiated with the resource.
 * @member {Array.<String>} clients
 */
UmaResource.prototype['clients'] = undefined;

/**
 * List of assosiated resource.
 * @member {Array.<String>} resources
 */
UmaResource.prototype['resources'] = undefined;

/**
 * Resource revision.
 * @member {String} rev
 */
UmaResource.prototype['rev'] = undefined;

/**
 * Resource creator or owner.
 * @member {String} creator
 */
UmaResource.prototype['creator'] = undefined;

/**
 * Resource description.
 * @member {String} description
 */
UmaResource.prototype['description'] = undefined;

/**
 * Resource type.
 * @member {String} type
 */
UmaResource.prototype['type'] = undefined;

/**
 * Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this resource will created.
 * @member {Date} creationDate
 */
UmaResource.prototype['creationDate'] = undefined;

/**
 * Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this resource will expire.
 * @member {Date} expirationDate
 */
UmaResource.prototype['expirationDate'] = undefined;

/**
 * Specifies whether client is deletable.
 * @member {Boolean} deletable
 * @default false
 */
UmaResource.prototype['deletable'] = false;






export default UmaResource;

