// Auth Actions
export const GET_OAUTH2_CONFIG = 'GET_OAUTH2_CONFIG'
export const GET_OAUTH2_CONFIG_RESPONSE = 'GET_OAUTH2_CONFIG_RESPONSE'
export const GET_API_ACCESS_TOKEN = 'GET_API_ACCESS_TOKEN'
export const GET_API_ACCESS_TOKEN_RESPONSE = 'GET_API_ACCESS_TOKEN_RESPONSE'
export const SET_STATE = 'SET_STATE'
export const RESET = 'RESET'
export const SET_ITEM = 'SET_ITEM'
export const USERINFO_REQUEST = 'USERINFO_REQUEST'
export const USERINFO_RESPONSE = 'USERINFO_RESPONSE'

// scopes
export const GET_SCOPES = 'GET_SCOPES'
export const GET_SCOPES_RESPONSE = 'GET_SCOPES_RESPONSE'
export const SEARCH_SCOPES = 'SEARCH_SCOPES'
export const GET_SCOPE_BY_INUM = 'GET_SCOPE_BY_INUM'
export const GET_SCOPE_BY_INUM_RESPONSE = 'GET_SCOPE_BY_INUM_RESPONSE'
export const ADD_SCOPE = 'ADD_SCOPE'
export const ADD_SCOPE_RESPONSE = 'ADD_SCOPE_RESPONSE'
export const EDIT_SCOPE = 'EDIT_SCOPE'
export const EDIT_SCOPE_RESPONSE = 'EDIT_SCOPE_RESPONSE'
export const DELETE_SCOPE = 'DELETE_SCOPE'
export const DELETE_SCOPE_RESPONSE = 'DELETE_SCOPE_RESPONSE'
export const SET_SCOPE_ITEM = 'SET_SCOPE_ITEM'
export const GET_SCOPE_BY_PATTERN = 'GET_SCOPE_BY_PATTERN'
export const GET_SCOPE_BY_PATTERN_RESPONSE = 'GET_SCOPE_BY_PATTERN_RESPONSE'

// Clients
export const GET_OPENID_CLIENTS = 'GET_OPENID_CLIENTS'
export const GET_OPENID_CLIENTS_RESPONSE = 'GET_OPENID_CLIENTS_RESPONSE'
export const SEARCH_CLIENTS = 'SEARCH_CLIENTS'
export const EDIT_CLIENT = 'EDIT_CLIENT'
export const EDIT_CLIENT_RESPONSE = 'EDIT_CLIENT_RESPONSE'
export const ADD_NEW_CLIENT = 'ADD_NEW_CLIENT'
export const ADD_CLIENT_RESPONSE = 'ADD_CLIENT_RESPONSE'
export const DELETE_CLIENT = 'DELETE_CLIENT'
export const DELETE_CLIENT_RESPONSE = 'DELETE_CLIENT_RESPONSE'
export const SET_CLIENT_ITEM = 'SET_CLIENT_ITEM'

// Attributes types
export const GET_ATTRIBUTES = 'GET_ATTRIBUTES'
export const GET_ATTRIBUTES_RESPONSE = 'GET_ATTRIBUTES_RESPONSE'
export const SEARCH_ATTRIBUTES = 'SEARCH_ATTRIBUTES'
export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const ADD_ATTRIBUTE_RESPONSE = 'ADD_ATTRIBUTE_RESPONSE'
export const EDIT_ATTRIBUTE = 'EDIT_ATTRIBUTE'
export const EDIT_ATTRIBUTE_RESPONSE = 'EDIT_ATTRIBUTE_RESPONSE'
export const GET_ATTRIBUTE_BY_INUM = 'GET_ATTRIBUTE_BY_INUM'
export const GET_ATTRIBUTE_BY_INUM_RESPONSE = 'GET_ATTRIBUTE_BY_INUM_RESPONSE'
export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE'
export const DELETE_ATTRIBUTE_RESPONSE = 'DELETE_ATTRIBUTE_RESPONSE'
export const SET_ATTRIBUTE_ITEM = 'SET_ATTRIBUTE_ITEM'

//JSON Config
export const GET_JSON_CONFIG = 'GET_JSON_CONFIG'
export const GET_JSONCONFIG_RESPONSE = 'GET_JSONCONFIG_RESPONSE'
export const PATCH_JSON_CONFIG = 'PATCH_JSON_CONFIG'
export const PATCH_JSONCONFIG_RESPONSE = 'PATCH_JSONCONFIG_RESPONSE'

export const GET_JWKS = 'GET_JWKS'
export const GET_JWKS_RESPONSE = 'GET_JWKS_RESPONSE'

// Acrs
export const GET_ACRS = 'GET_ACRS'
export const GET_ACRS_RESPONSE = 'GET_ACRS_RESPONSE'
export const PUT_ACRS = 'PUT_ACRS'
export const PUT_ACRS_RESPONSE = 'PUT_ACRS_RESPONSE'
export const GET_ACR_AUTH_SCRIPT = 'GET_ACR_AUTH_SCRIPT'
export const GET_ACR_AUTH_SCRIPT_RESPONSE = 'GET_ACR_AUTH_SCRIPT_RESPONSE'


// logging
export const GET_LOGGING = 'GET_LOGGING'
export const GET_LOGGING_RESPONSE = 'GET_LOGGING_RESPONSE'
export const PUT_LOGGING = 'PUT_LOGGING'
export const PUT_LOGGING_RESPONSE = 'PUT_LOGGING_RESPONSE'