// SMTP Management

export const GET_SMTPS = 'GET_SMTPS'
export const GET_SMTPS_RESPONSE = 'GET_SMTPS_RESPONSE'
export const UPDATE_SMTP = 'UPDATE_SMTP'
export const UPDATE_SMTP_RESPONSE = 'UPDATE_SMTP_RESPONSE'
export const SELECTED_SMTP_DATA = 'SELECTED_SMTP_DATA'
export const TEST_SMTP_CONFIG = 'TEST_SMTP_CONFIG'
export const TEST_SMTP_CONFIG_RESPONSE = 'TEST_SMTP_CONFIG_RESPONSE'
export const CLEAR_TEST_CONFIG = 'CLEAR_TEST_CONFIG'