// SMTP Management

export const GET_SMTPS = 'GET_SMTPS'
export const GET_SMTPS_RESPONSE = 'GET_SMTPS_RESPONSE'
export const UPDATE_SMTP = 'UPDATE_SMTP'
export const UPDATE_SMTP_RESPONSE = 'UPDATE_SMTP_RESPONSE'
export const SELECTED_SMTP_DATA = 'SELECTED_SMTP_DATA'
export const TEST_SMTP = 'TEST_SMTP'
export const TEST_SMTP_RESPONSE = 'TEST_SMTP_RESPONSE'