openapi: 3.0.3
info:
  title: Jans Config API
  contact:
    name: Contact
    url: 'https://github.com/JanssenProject/jans/discussions'
  license:
    name: License
    url: 'https://github.com/JanssenProject/jans/blob/main/LICENSE'
  version: OAS Version
servers:
  - url: 'https://jans.local.io'
    description: The Jans server
tags:
  - name: Attribute
  - name: Default Authentication Method
  - name: Cache Configuration
  - name: Cache Configuration – Memcached
  - name: Cache Configuration – Redis
  - name: Cache Configuration – in-Memory
  - name: Cache Configuration – Native-Persistence
  - name: Configuration – Properties
  - name: Configuration – SMTP
  - name: Configuration – Logging
  - name: Configuration – JWK - JSON Web Key (JWK)
  - name: Custom Scripts
  - name: Database - LDAP configuration
  - name: OAuth - OpenID Connect - Clients
  - name: OAuth - UMA Resources
  - name: OAuth - Scopes
  - name: Agama - Configuration
  - name: Agama
  - name: Statistics - User
  - name: Health - Check
  - name: Server Stats
  - name: Auth - Session Management
  - name: Organization Configuration
  - name: Auth Server Health - Check
  - name: Plugins
  - name: Configuration – Config API
  - name: Client Authorization
  - name: Jans Assets
  - name: Token
  - name: Fido2 - Configuration
  - name: Fido2 - Registration
  - name: Configuration – User Management
  - name: Admin UI - Role
  - name: Admin UI - Permission
  - name: Admin UI - Role-Permissions Mapping
  - name: Admin UI - License
  - name: Admin UI - Webhooks
  - name: Jans Link - Configuration
  - name: SCIM - Config Management
  - name: SAML - Configuration
  - name: SAML - Trust Relationship
  - name: SAML - Identity Broker
  - name: Keycloak Link - Configuration
  - name: Lock - Configuration
  - name: Lock - Audit
paths:
  /api/v1/health/app-version:
    get:
      tags:
        - Health - Check
      summary: Returns application version
      description: Returns application version
      operationId: get-app-version
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/app-version.readonly'
  /api/v1/health:
    get:
      tags:
        - Health - Check
      summary: Returns application health status
      description: Returns application health status
      operationId: get-config-health
  /api/v1/health/live:
    get:
      tags:
        - Health - Check
      summary: Returns application liveness status
      description: Returns application liveness status
      operationId: get-config-health-live
  /api/v1/health/ready:
    get:
      tags:
        - Health - Check
      summary: Returns application readiness status
      description: Returns application readiness status
      operationId: get-config-health-ready
  /api/v1/health/server-stat:
    get:
      tags:
        - Health - Check
      summary: Returns application server status
      description: Returns application server status
      operationId: get-server-stat
  /api/v1/health/service-status:
    get:
      tags:
        - Health - Check
      summary: Fetch service status
      description: Fetch service status
      operationId: get-service-status
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/data.readonly'
  /api/v1/acrs:
    get:
      tags:
        - Default Authentication Method
      summary: Gets default authentication method.
      description: Gets default authentication method.
      operationId: get-acrs
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/acrs.readonly'
            - 'https://jans.io/oauth/config/acrs.write'
            - 'https://jans.io/oauth/config/read-all'
    put:
      tags:
        - Default Authentication Method
      summary: Updates default authentication method.
      description: Updates default authentication method.
      operationId: put-acrs
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/acrs.write'
            - 'https://jans.io/oauth/config/write-all'
  '/api/v1/agama-deployment/{name}':
    get:
      tags:
        - Agama
      summary: Fetches deployed Agama project based on name.
      description: Fetches deployed Agama project based on name.
      operationId: get-agama-prj-by-name
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/agama.readonly'
    post:
      tags:
        - Agama
      summary: Deploy an Agama project.
      description: Deploy an Agama project.
      operationId: post-agama-prj
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/agama.write'
    delete:
      tags:
        - Agama
      summary: Delete a deployed Agama project.
      description: Delete a deployed Agama project.
      operationId: delete-agama-prj
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/agama.delete'
  '/api/v1/agama-deployment/configs/{name}':
    get:
      tags:
        - Agama
      summary: Retrieve the list of configs based on name.
      description: Retrieve the list of configs based on name.
      operationId: get-agama-prj-configs
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/agama.readonly'
    put:
      tags:
        - Agama
      summary: Update an Agama project.
      description: Update an Agama project.
      operationId: put-agama-prj
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/agama.write'
  /api/v1/agama-deployment:
    get:
      tags:
        - Agama
      summary: Retrieve the list of projects deployed currently.
      description: Retrieve the list of projects deployed currently.
      operationId: get-agama-prj
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/agama.readonly'
  '/api/v1/agama/syntax-check/{qname}':
    post:
      tags:
        - Agama - Configuration
      summary: Determine if the text passed is valid Agama code
      description: Determine if the text passed is valid Agama code
      operationId: agama-syntax-check
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/agama.readonly'
            - 'https://jans.io/oauth/config/agama.write'
            - 'https://jans.io/oauth/config/read-all'
  '/api/v1/jans-assets/{inum}':
    get:
      tags:
        - Jans Assets
      summary: Gets an asset by inum - unique identifier
      description: Gets an asset by inum - unique identifier
      operationId: get-asset-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-read'
    delete:
      tags:
        - Jans Assets
      summary: Delete an asset
      description: Delete an asset
      operationId: delete-asset
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-delete'
  '/api/v1/jans-assets/name/{name}':
    get:
      tags:
        - Jans Assets
      summary: Fetch asset by name
      description: Fetch asset by name.
      operationId: get-asset-by-name
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-read'
  /api/v1/jans-assets/asset-dir-mapping:
    get:
      tags:
        - Jans Assets
      summary: Get valid asset types
      description: Get valid asset types
      operationId: get-asset-dir-mapping
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-read'
  /api/v1/jans-assets:
    get:
      tags:
        - Jans Assets
      summary: Gets all Jans assets.
      description: Gets all Jans assets.
      operationId: get-all-assets
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-read'
  /api/v1/jans-assets/services:
    get:
      tags:
        - Jans Assets
      summary: Gets asset services
      description: Gets asset services
      operationId: get-asset-services
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-read'
  /api/v1/jans-assets/asset-type:
    get:
      tags:
        - Jans Assets
      summary: Get valid asset types
      description: Get valid asset types
      operationId: get-asset-types
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-read'
  '/api/v1/jans-assets/service/{service-name}':
    post:
      tags:
        - Jans Assets
      summary: Load assets on server for a service
      description: Load assets on server for a service
      operationId: load-service-asset
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-write'
  /api/v1/jans-assets/upload:
    put:
      tags:
        - Jans Assets
      summary: Update existing asset
      description: Update existing asset
      operationId: put-asset
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-write'
    post:
      tags:
        - Jans Assets
      summary: Upload new asset
      description: Upload new asset
      operationId: post-new-asset
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans_asset-write'
  /api/v1/attributes:
    get:
      tags:
        - Attribute
      summary: Gets a list of Jans attributes.
      description: Gets a list of Jans attributes.
      operationId: get-attributes
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/attributes.readonly'
    put:
      tags:
        - Attribute
      summary: Updates an existing attribute
      description: Updates an existing attribute
      operationId: put-attributes
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/attributes.write'
    post:
      tags:
        - Attribute
      summary: Adds a new attribute
      description: Adds a new attribute
      operationId: post-attributes
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/attributes.write'
  '/api/v1/attributes/{inum}':
    get:
      tags:
        - Attribute
      summary: Gets an attribute based on inum
      description: Gets an attribute based on inum
      operationId: get-attributes-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/attributes.readonly'
    delete:
      tags:
        - Attribute
      summary: Deletes an attribute based on inum
      description: Deletes an attribute based on inum
      operationId: delete-attributes-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/attributes.delete'
    patch:
      tags:
        - Attribute
      summary: Partially modify a JansAttribute
      description: Partially modify a JansAttribute
      operationId: patch-attributes-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/attributes.write'
  /api/v1/jans-auth-server/config:
    get:
      tags:
        - Configuration – Properties
      summary: Gets all Jans authorization server configuration properties.
      description: Gets all Jans authorization server configuration properties.
      operationId: get-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/config/properties.readonly'
    patch:
      tags:
        - Configuration – Properties
      summary: >-
        Partially modifies Jans authorization server Application configuration
        properties.
      description: >-
        Partially modifies Jans authorization server AppConfiguration
        properties.
      operationId: patch-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/config/properties.write'
  /api/v1/jans-auth-server/config/feature-flags:
    get:
      tags:
        - Configuration – Properties
      summary: Returns feature flags type configured for Jans authorization server.
      description: Returns feature flags type configured for Jans authorization server.
      operationId: get-feature-flag-type
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/config/properties.readonly'
  /api/v1/jans-auth-server/config/persistence:
    get:
      tags:
        - Configuration – Properties
      summary: Returns persistence type configured for Jans authorization server.
      description: Returns persistence type configured for Jans authorization server.
      operationId: get-properties-persistence
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/config/properties.readonly'
  /api/v1/config/cache:
    get:
      tags:
        - Cache Configuration
      summary: Returns cache configuration.
      description: Returns cache configuration.
      operationId: get-config-cache
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.readonly'
    patch:
      tags:
        - Cache Configuration
      summary: Patch cache configuration.
      description: Patch cache configuration
      operationId: patch-config-cache
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
  /api/v1/config/cache/in-memory:
    get:
      tags:
        - Cache Configuration – in-Memory
      summary: Returns in-Memory cache configuration.
      description: Returns in-Memory cache configuration.
      operationId: get-config-cache-in-memory
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.readonly'
    put:
      tags:
        - Cache Configuration – in-Memory
      summary: Updates in-Memory cache configuration.
      description: Updates in-Memory cache configuration
      operationId: put-config-cache-in-memory
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
    patch:
      tags:
        - Cache Configuration – in-Memory
      summary: Patch In-Memory cache configuration.
      description: Patch In-Memory cache configuration
      operationId: patch-config-cache-in-memory
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
  /api/v1/config/cache/memcached:
    get:
      tags:
        - Cache Configuration – Memcached
      summary: Returns memcached cache configuration.
      description: Returns memcached cache configuration.
      operationId: get-config-cache-memcached
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.readonly'
    put:
      tags:
        - Cache Configuration – Memcached
      summary: Updates memcached cache configuration.
      description: Updates memcached cache configuration
      operationId: put-config-cache-memcached
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
    patch:
      tags:
        - Cache Configuration – Memcached
      summary: Patch memcached cache configuration.
      description: Patch memcached cache configuration
      operationId: patch-config-cache-memcached
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
  /api/v1/config/cache/native-persistence:
    get:
      tags:
        - Cache Configuration – Native-Persistence
      summary: Returns native persistence cache configuration.
      description: Returns native persistence cache configuration.
      operationId: get-config-cache-native-persistence
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.readonly'
    put:
      tags:
        - Cache Configuration – Native-Persistence
      summary: Updates native persistence cache configuration.
      description: Updates native persistence cache configuration
      operationId: put-config-cache-native-persistence
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
    patch:
      tags:
        - Cache Configuration – Native-Persistence
      summary: Patch native persistence cache configuration.
      description: Patch native persistence cache configuration
      operationId: patch-config-cache-native-persistence
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
  /api/v1/config/cache/redis:
    get:
      tags:
        - Cache Configuration – Redis
      summary: Returns Redis cache configuration.
      description: Returns Redis cache configuration
      operationId: get-config-cache-redis
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.readonly'
    put:
      tags:
        - Cache Configuration – Redis
      summary: Updates Redis cache configuration.
      description: Updates Redis cache configuration
      operationId: put-config-cache-redis
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
    patch:
      tags:
        - Cache Configuration – Redis
      summary: Patch Redis cache configuration.
      description: Patch Redis cache configuration
      operationId: patch-config-cache-redis
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/cache.write'
  '/api/v1/clients/authorizations/{userId}/{clientId}/{username}':
    delete:
      tags:
        - Client Authorization
      summary: Revoke client authorization
      description: Revoke client authorizations
      operationId: delete-client-authorization
      security:
        - oauth2:
            - 'https://jans.io/oauth/client/authorizations.delete'
  '/api/v1/clients/authorizations/{userId}':
    get:
      tags:
        - Client Authorization
      summary: Gets list of client authorization
      description: Gets list of client authorizations
      operationId: get-client-authorization
      security:
        - oauth2:
            - 'https://jans.io/oauth/client/authorizations.readonly'
  /api/v1/openid/clients:
    get:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Gets list of OpenID Connect clients
      description: Gets list of OpenID Connect clients
      operationId: get-oauth-openid-clients
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/openid/clients.readonly'
    put:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Update OpenId Connect client
      description: Update OpenId Connect client
      operationId: put-oauth-openid-client
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/openid/clients.write'
    post:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Create new OpenId Connect client
      description: Create new OpenId Connect client
      operationId: post-oauth-openid-client
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/openid/clients.write'
  '/api/v1/openid/clients/{inum}':
    get:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Get OpenId Connect Client by Inum
      description: Get OpenId Connect Client by Inum
      operationId: get-oauth-openid-clients-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/openid/clients.readonly'
    delete:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Delete OpenId Connect client
      description: Delete OpenId Connect client
      operationId: delete-oauth-openid-client-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/openid/clients.delete'
    patch:
      tags:
        - OAuth - OpenID Connect - Clients
      summary: Patch OpenId Connect client
      description: Patch OpenId Connect client
      operationId: patch-oauth-openid-client-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/openid/clients.write'
  /api/v1/api-config:
    get:
      tags:
        - Configuration – Config API
      summary: Gets config-api configuration properties.
      description: Gets config-api configuration properties.
      operationId: get-config-api-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/properties.readonly'
    patch:
      tags:
        - Configuration – Config API
      summary: Partially modifies config-api configuration properties.
      description: Partially modifies config-api Configuration properties.
      operationId: patch-config-api-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/properties.write'
  /api/v1/config/smtp:
    get:
      tags:
        - Configuration – SMTP
      summary: Returns SMTP server configuration
      description: Returns SMTP server configuration
      operationId: get-config-smtp
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/smtp.readonly'
    put:
      tags:
        - Configuration – SMTP
      summary: Updates SMTP server configuration
      description: Updates SMTP server configuration
      operationId: put-config-smtp
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/smtp.write'
    post:
      tags:
        - Configuration – SMTP
      summary: Adds SMTP server configuration
      description: Adds SMTP server configuration
      operationId: post-config-smtp
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/smtp.write'
    delete:
      tags:
        - Configuration – SMTP
      summary: Deletes SMTP server configuration
      description: Deletes SMTP server configuration
      operationId: delete-config-smtp
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/smtp.delete'
  /api/v1/config/smtp/test:
    post:
      tags:
        - Configuration – SMTP
      summary: Signing Test SMTP server configuration
      description: Signing Test SMTP server configuration
      operationId: test-config-smtp
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/smtp.write'
  /api/v1/config/scripts:
    get:
      tags:
        - Custom Scripts
      summary: Gets a list of custom scripts
      description: Gets a list of custom scripts
      operationId: get-config-scripts
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.readonly'
    put:
      tags:
        - Custom Scripts
      summary: Updates a custom script
      description: Updates a custom script
      operationId: put-config-scripts
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.write'
    post:
      tags:
        - Custom Scripts
      summary: Adds a new custom script
      description: Adds a new custom script
      operationId: post-config-scripts
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.write'
  '/api/v1/config/scripts/{inum}':
    delete:
      tags:
        - Custom Scripts
      summary: Deletes a custom script
      description: Deletes a custom script
      operationId: delete-config-scripts-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.delete'
    patch:
      tags:
        - Custom Scripts
      summary: Patches a custom script
      description: Patches a custom script
      operationId: patch-config-scripts-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.write'
  '/api/v1/config/scripts/inum/{inum}':
    get:
      tags:
        - Custom Scripts
      summary: Gets a script by Inum
      description: Gets a script by Inum
      operationId: get-config-scripts-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.readonly'
  '/api/v1/config/scripts/name/{name}':
    get:
      tags:
        - Custom Scripts
      summary: Fetch custom script by name
      description: Fetch custom script by name
      operationId: get-custom-script-by-name
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.readonly'
  /api/v1/config/scripts/types:
    get:
      tags:
        - Custom Scripts
      summary: Fetch custom script types
      description: Fetch custom script types
      operationId: get-custom-script-type
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.readonly'
  /api/v1/config/scripts/script-types:
    get:
      tags:
        - Custom Scripts
      summary: Fetch custom script types
      description: Fetch custom script types
      operationId: get-custom-script-types
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.readonly'
  '/api/v1/config/scripts/type/{type}':
    get:
      tags:
        - Custom Scripts
      summary: Gets list of scripts by type
      description: Gets list of scripts by type
      operationId: get-config-scripts-by-type
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scripts.readonly'
  /api/v1/jans-auth-server/health:
    get:
      tags:
        - Auth Server Health - Check
      summary: Returns auth server health status
      description: Returns auth server health status
      operationId: get-auth-server-health
  '/api/v1/config/jwks/{kid}':
    get:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Get a JSON Web Key based on kid
      description: Get a JSON Web Key based on kid
      operationId: get-jwk-by-kid
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jwks.readonly'
    delete:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Delete a JSON Web Key based on kid
      description: Delete a JSON Web Key based on kid
      operationId: delete-config-jwk-kid
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jwks.delete'
    patch:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Patch a specific JSON Web Key based on kid
      description: Patch a specific JSON Web Key based on kid
      operationId: patch-config-jwk-kid
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jwks.write'
  /api/v1/config/jwks:
    get:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Gets list of JSON Web Key (JWK) used by server
      description: Gets list of JSON Web Key (JWK) used by server
      operationId: get-config-jwks
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jwks.readonly'
    put:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Replaces JSON Web Keys
      description: Replaces JSON Web Keys
      operationId: put-config-jwks
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jwks.write'
    patch:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Patches JSON Web Keys
      description: Patches JSON Web Keys
      operationId: patch-config-jwks
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jwks.write'
  /api/v1/config/jwks/key:
    post:
      tags:
        - Configuration – JWK - JSON Web Key (JWK)
      summary: Configuration – JWK - JSON Web Key (JWK)
      description: Configuration – JWK - JSON Web Key (JWK)
      operationId: post-config-jwks-key
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jwks.write'
  /api/v1/config/database/ldap:
    get:
      tags:
        - Database - LDAP configuration
      summary: Gets list of existing LDAP configurations.
      description: Gets list of existing LDAP configurations.
      operationId: get-config-database-ldap
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/database/ldap.readonly'
    put:
      tags:
        - Database - LDAP configuration
      summary: Updates LDAP configuration
      description: Updates LDAP configuration
      operationId: put-config-database-ldap
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/database/ldap.write'
    post:
      tags:
        - Database - LDAP configuration
      summary: Adds a new LDAP configuration
      description: Adds a new LDAP configuration
      operationId: post-config-database-ldap
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/database/ldap.write'
  '/api/v1/config/database/ldap/{name}':
    get:
      tags:
        - Database - LDAP configuration
      summary: Gets an LDAP configuration by name.
      description: Gets an LDAP configuration by name.
      operationId: get-config-database-ldap-by-name
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/database/ldap.readonly'
    delete:
      tags:
        - Database - LDAP configuration
      summary: Deletes an LDAP configuration
      description: Deletes an LDAP configuration
      operationId: delete-config-database-ldap-by-name
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/database/ldap.delete'
    patch:
      tags:
        - Database - LDAP configuration
      summary: Patches a LDAP configuration by name
      description: Patches a LDAP configuration by name
      operationId: patch-config-database-ldap-by-name
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/database/ldap.write'
  /api/v1/config/database/ldap/test:
    post:
      tags:
        - Database - LDAP configuration
      summary: Tests an LDAP configuration
      description: Tests an LDAP configuration
      operationId: post-config-database-ldap-test
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/database/ldap.readonly'
  /api/v1/logging:
    get:
      tags:
        - Configuration – Logging
      summary: Returns Jans Authorization Server logging settings
      description: Returns Jans Authorization Server logging settings
      operationId: get-config-logging
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/logging.readonly'
    put:
      tags:
        - Configuration – Logging
      summary: Updates Jans Authorization Server logging settings
      description: Updates Jans Authorization Server logging settings
      operationId: put-config-logging
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/logging.write'
  /api/v1/config/message:
    get:
      tags:
        - Message Configuration
      summary: Returns message configuration.
      description: Returns message configuration.
      operationId: get-config-message
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.readonly'
    patch:
      tags:
        - Message Configuration
      summary: Patch message configuration.
      description: Patch message configuration
      operationId: patch-config-message
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.write'
  /api/v1/config/message/postgres:
    get:
      tags:
        - Message Configuration – Postgres
      summary: Returns Postgres message configuration.
      description: Returns Postgres message configuration.
      operationId: get-config-message-postgres
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.readonly'
    put:
      tags:
        - Message Configuration – Postgres
      summary: Updates Postgres message configuration.
      description: Updates Postgres message configuration
      operationId: put-config-message-postgres
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.write'
    patch:
      tags:
        - Message Configuration – Postgres
      summary: Patch Postgres message configuration.
      description: Patch Postgres message configuration
      operationId: patch-config-message-postgres
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.write'
  /api/v1/config/message/redis:
    get:
      tags:
        - Message Configuration – Redis
      summary: Returns Redis message configuration.
      description: Returns Redis message configuration
      operationId: get-config-message-redis
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.readonly'
    put:
      tags:
        - Message Configuration – Redis
      summary: Updates Redis message configuration.
      description: Updates Redis message configuration
      operationId: put-config-message-redis
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.write'
    patch:
      tags:
        - Message Configuration – Redis
      summary: Patch Redis message configuration.
      description: Patch Redis message configuration
      operationId: patch-config-message-redis
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/message.write'
  /api/v1/org:
    get:
      tags:
        - Organization Configuration
      summary: Retrieves organization configuration
      description: Retrieves organization configuration
      operationId: get-organization-config
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/organization.readonly'
    patch:
      tags:
        - Organization Configuration
      summary: Patch organization configuration
      description: Patch organization configuration
      operationId: patch-organization-config
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/organization.write'
  /api/v1/plugin:
    get:
      tags:
        - Plugins
      summary: Gets list of Plugins
      description: Gets list of Plugins
      operationId: get-plugins
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/plugin.readonly'
  '/api/v1/plugin/{pluginName}':
    get:
      tags:
        - Plugins
      summary: Get plugin by name
      description: Get plugin by name
      operationId: get-plugin-by-name
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/plugin.readonly'
  /api/v1/scopes:
    get:
      tags:
        - OAuth - Scopes
      summary: Gets list of Scopes
      description: Gets list of Scopes
      operationId: get-oauth-scopes
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.readonly'
    put:
      tags:
        - OAuth - Scopes
      summary: Update Scope
      description: Update Scope
      operationId: put-oauth-scopes
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.write'
    post:
      tags:
        - OAuth - Scopes
      summary: Create Scope
      description: Create Scope
      operationId: post-oauth-scopes
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.write'
  '/api/v1/scopes/{inum}':
    get:
      tags:
        - OAuth - Scopes
      summary: Get Scope by Inum
      description: Get Scope by Inum
      operationId: get-oauth-scopes-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.readonly'
    delete:
      tags:
        - OAuth - Scopes
      summary: Delete Scope
      description: Delete Scope
      operationId: delete-oauth-scopes-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.delete'
    patch:
      tags:
        - OAuth - Scopes
      summary: Patch Scope
      description: Patch Scope
      operationId: patch-oauth-scopes-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.write'
  '/api/v1/scopes/creator/{creatorId}':
    get:
      tags:
        - OAuth - Scopes
      summary: Get Scope by creatorId
      description: Get Scope by creatorId
      operationId: get-scope-by-creator
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.readonly'
  '/api/v1/scopes/type/{type}':
    get:
      tags:
        - OAuth - Scopes
      summary: Get Scope by type
      description: Get Scope by type
      operationId: get-scope-by-type
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/scopes.readonly'
  '/api/v1/jans-auth-server/session/sid/{sid}':
    get:
      tags:
        - Auth - Session Management
      summary: Get session by id.
      description: Get session by id.
      operationId: get-session-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/session.readonly'
            - revoke_session
    delete:
      tags:
        - Auth - Session Management
      summary: Delete a session.
      description: Delete a session.
      operationId: delete-session
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/session.delete'
            - revoke_session
  '/api/v1/jans-auth-server/session/user/{userDn}':
    delete:
      tags:
        - Auth - Session Management
      summary: Revoke all sessions by userDn
      description: Revoke all sessions by userDn
      operationId: revoke-user-session
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/session.delete'
            - revoke_session
  /api/v1/jans-auth-server/session:
    get:
      tags:
        - Auth - Session Management
      summary: Return all session
      description: Return all session
      operationId: get-sessions
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/session.readonly'
            - revoke_session
  /api/v1/jans-auth-server/session/search:
    get:
      tags:
        - Auth - Session Management
      summary: Search session
      description: Search session
      operationId: search-session
      security:
        - oauth2:
            - 'https://jans.io/oauth/jans-auth-server/session.readonly'
            - revoke_session
  /api/v1/stat:
    get:
      tags:
        - Statistics - User
      summary: Provides server with basic statistic
      description: Provides server with basic statistic
      operationId: get-stat
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/stats.readonly'
            - jans_stat
  '/api/v1/token/client/{clientId}':
    get:
      tags:
        - Token
      summary: Get token details by client.
      description: Get token details by client.
      operationId: get-token-by-client
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/token.readonly'
  '/api/v1/token/tknCde/{tknCde}':
    get:
      tags:
        - Token
      summary: Get token details by Id.
      description: Get token details by Id.
      operationId: get-token-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/token.readonly'
  '/api/v1/token/revoke/{tknCde}':
    delete:
      tags:
        - Token
      summary: Revoke client token.
      description: Revoke client token.
      operationId: revoke-token
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/token.delete'
  /api/v1/token/search:
    get:
      tags:
        - Token
      summary: Search tokens
      description: Search tokens
      operationId: search-token
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/token.readonly'
  /api/v1/uma/resources:
    get:
      tags:
        - OAuth - UMA Resources
      summary: Gets list of UMA resources
      description: Gets list of UMA resources
      operationId: get-oauth-uma-resources
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/uma/resources.readonly'
    put:
      tags:
        - OAuth - UMA Resources
      summary: Updates an UMA resource
      description: Updates an UMA resource
      operationId: put-oauth-uma-resources
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/uma/resources.write'
    post:
      tags:
        - OAuth - UMA Resources
      summary: Creates an UMA resource
      description: Creates an UMA resource
      operationId: post-oauth-uma-resources
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/uma/resources.write'
  '/api/v1/uma/resources/{id}':
    get:
      tags:
        - OAuth - UMA Resources
      summary: Gets an UMA resource by ID
      description: Gets an UMA resource by ID
      operationId: get-oauth-uma-resources-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/uma/resources.readonly'
    delete:
      tags:
        - OAuth - UMA Resources
      summary: Deletes an UMA resource
      description: Deletes an UMA resource
      operationId: delete-oauth-uma-resources-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/uma/resources.delete'
    patch:
      tags:
        - OAuth - UMA Resources
      summary: Patch UMA resource
      description: Patch UMA resource
      operationId: patch-oauth-uma-resources-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/uma/resources.write'
  '/api/v1/uma/resources/clientId/{clientId}':
    get:
      tags:
        - OAuth - UMA Resources
      summary: Fetch uma resources by client id
      description: Fetch uma resources by client id
      operationId: get-oauth-uma-resources-by-clientid
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/uma/resources.readonly'
  /fido2/fido2-config:
    get:
      tags:
        - Fido2 - Configuration
      summary: Gets Jans Authorization Server Fido2 configuration properties
      description: Gets Jans Authorization Server Fido2 configuration properties
      operationId: get-properties-fido2
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/fido2.readonly'
    put:
      tags:
        - Fido2 - Configuration
      summary: Updates Fido2 configuration properties
      description: Updates Fido2 configuration properties
      operationId: put-properties-fido2
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/fido2.write'
  '/fido2/registration/id/{jansId}':
    get:
      tags:
        - Fido2 - Registration
      summary: Fetch Fido2RegistrationEntry by Id.
      description: Fetch Fido2RegistrationEntry by Id.
      operationId: get-fido2-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/fido2.readonly'
    delete:
      tags:
        - Fido2 - Registration
      summary: Delete Fido2 Device Data based on device UID
      description: Delete Fido2 Device Data based on device UID
      operationId: delete-fido2-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/fido2.delete'
  '/fido2/registration/entries/{username}':
    get:
      tags:
        - Fido2 - Registration
      summary: Get details of connected FIDO2 devices registered to user
      description: Get details of connected FIDO2 devices registered to user
      operationId: get-registration-entries-fido2
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/fido2.readonly'
  /fido2/registration:
    get:
      tags:
        - Fido2 - Registration
      summary: Get a list of Fido2RegistrationEntry.
      description: Get a list of Fido2RegistrationEntry.
      operationId: search-fido2-registration-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/fido2.readonly'
  /mgt/configuser:
    get:
      tags:
        - Configuration – User Management
      summary: Gets list of users
      description: Gets list of users
      operationId: get-user
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/user.readonly'
    put:
      tags:
        - Configuration – User Management
      summary: Update User
      description: Update User
      operationId: put-user
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/user.write'
    post:
      tags:
        - Configuration – User Management
      summary: Create new User
      description: Create new User
      operationId: post-user
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/user.write'
  '/mgt/configuser/{inum}':
    get:
      tags:
        - Configuration – User Management
      summary: Get User by Inum
      description: Get User by Inum
      operationId: get-user-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/user.readonly'
    delete:
      tags:
        - Configuration – User Management
      summary: Delete User
      description: Delete User
      operationId: delete-user
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/user.delete'
    patch:
      tags:
        - Configuration – User Management
      summary: Patch user properties by Inum
      description: Patch user properties by Inum
      operationId: patch-user-by-inum
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/user.write'
  /admin-ui/adminUIPermissions:
    get:
      tags:
        - Admin UI - Permission
      summary: Get all admin ui permissions
      description: Get all admin ui permissions
      operationId: get-all-adminui-permissions
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.readonly
    put:
      tags:
        - Admin UI - Permission
      summary: Edit admin ui permissions
      description: Edit admin ui permissions
      operationId: edit-adminui-permission
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write
    post:
      tags:
        - Admin UI - Permission
      summary: Add admin ui permissions
      description: Add admin ui permissions
      operationId: add-adminui-permission
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.write
  /admin-ui/adminUIRolePermissionsMapping:
    get:
      tags:
        - Admin UI - Role-Permissions Mapping
      summary: Get all admin ui role-permissions mapping
      description: Get all admin ui role-permissions mapping
      operationId: get-all-adminui-role-permissions
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.readonly
    put:
      tags:
        - Admin UI - Role-Permissions Mapping
      summary: Map permissions to role
      description: Map permissions to role
      operationId: map-permissions-to-role
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write
    post:
      tags:
        - Admin UI - Role-Permissions Mapping
      summary: Add role-permissions mapping
      description: Add role-permissions mapping
      operationId: add-role-permissions-mapping
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.write
  /admin-ui/adminUIRoles:
    get:
      tags:
        - Admin UI - Role
      summary: Get all admin ui roles
      description: Get all admin ui roles
      operationId: get-all-adminui-roles
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/role.readonly
    put:
      tags:
        - Admin UI - Role
      summary: Edit admin ui role
      description: Edit admin ui role
      operationId: edit-adminui-role
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write
    post:
      tags:
        - Admin UI - Role
      summary: Add admin ui role
      description: Add admin ui role
      operationId: add-adminui-role
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/role.write
  '/admin-ui/adminUIPermissions/{adminUIPermission}':
    get:
      tags:
        - Admin UI - Permission
      summary: Get admin ui permission by permission-name
      description: Get admin ui permission by permission-name
      operationId: get-adminui-permission
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.readonly
    delete:
      tags:
        - Admin UI - Permission
      summary: Delete admin ui permission by permission-name
      description: Delete admin ui permission by permission-name
      operationId: delete-adminui-permission
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/permission.delete
  '/admin-ui/adminUIRoles/{adminUIRole}':
    get:
      tags:
        - Admin UI - Role
      summary: Get admin ui role details by role-name
      description: Get admin ui role details by role-name
      operationId: get-adminui-role
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/role.readonly
    delete:
      tags:
        - Admin UI - Role
      summary: Delete admin ui role by role-name
      description: Delete admin ui role by role-name
      operationId: delete-adminui-role
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/role.delete
  /admin-ui/config:
    get:
      tags:
        - Admin UI - Configuration
      summary: Get Admin UI editable configuration
      description: Get Admin UI editable configuration
      operationId: get-adminui-conf
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/role.readonly
    put:
      tags:
        - Admin UI - Configuration
      summary: Edit Admin UI editable configuration
      description: Edit Admin UI editable configuration
      operationId: edit-adminui-conf
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/properties.write
  '/admin-ui/adminUIRolePermissionsMapping/{adminUIRole}':
    get:
      tags:
        - Admin UI - Role-Permissions Mapping
      summary: Get admin ui role-permissions mapping by role-name
      description: Get admin ui role-permissions mapping by role-name
      operationId: get-adminui-role-permissions
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.readonly
    delete:
      tags:
        - Admin UI - Role-Permissions Mapping
      summary: Remove role-permissions mapping by role-name
      description: Remove role-permissions mapping by role-name
      operationId: remove-role-permissions-permission
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/user/rolePermissionMapping.delete
  /admin-ui/license/activate:
    post:
      tags:
        - Admin UI - License
      summary: Activate license using license-key
      description: Activate license using license-key
      operationId: activate-adminui-license
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/license.write
  /admin-ui/license/details:
    get:
      tags:
        - Admin UI - License
      summary: Get admin ui license details
      description: Get admin ui license details
      operationId: get-adminui-license
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/isActive:
    get:
      tags:
        - Admin UI - License
      summary: Check if admin-ui license is active
      description: Check if admin-ui license is active
      operationId: is-license-active
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/isConfigValid:
    get:
      tags:
        - Admin UI - License
      summary: Is license configuration valid
      description: Is license configuration valid
      operationId: check-adminui-license-config
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/retrieve:
    get:
      tags:
        - Admin UI - License
      summary: Retrieve license from SCAN
      description: Retrieve license from SCAN
      operationId: retrieve-license
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/license/ssa:
    post:
      tags:
        - Admin UI - License
      summary: Save SSA in configuration
      description: Save SSA in configuration
      operationId: adminui-post-ssa
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/license.write
  /admin-ui/license/trial:
    get:
      tags:
        - Admin UI - License
      summary: Generate trial license
      description: Generate trial license
      operationId: get-trial-license
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/license.readonly
  /admin-ui/webhook:
    get:
      tags:
        - Admin UI - Webhooks
      summary: Gets list of webhooks
      description: Gets list of webhooks
      operationId: get-all-webhooks
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResult'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    {
                      "start": 0,
                      "totalEntriesCount": 2,
                      "entriesCount": 2,
                      "entries": [{
                        "dn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans",
                        "inum": "aad9e1dd-87f3-357f-a2fa-93ae8eb94998",
                        "displayName": "test-5",
                        "description": "test1",
                        "url": "https://jsonplaceholder.typicode.com/posts",
                        "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                        "httpMethod": "POST",
                        "jansEnabled": true,
                        "httpHeaders": [{
                          "key": "Content-Type",
                          "value": "application/json"
                        }],
                        "baseDn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans"
                      }, {
                        "dn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans",
                        "inum": "d23d60e8-0187-3878-94d9-30d594c4c986",
                        "displayName": "test-6",
                        "description": "test1",
                        "url": "https://jsonplaceholder.typicode.com/posts",
                        "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                        "httpMethod": "POST",
                        "jansEnabled": true,
                        "httpHeaders": [{
                          "key": "Content-Type",
                          "value": "application/json"
                        }],
                        "baseDn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans"
                      }]
                    }
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
    put:
      tags:
        - Admin UI - Webhooks
      summary: Update Webhook
      description: Update Webhook
      operationId: put-webhook
      requestBody:
        description: Webhook object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEntry'
            examples:
              Request json example:
                description: Request json example
                value: |
                  {
                    "dn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans",
                    "inum": "2d3fe60f-db3f-3ab8-a285-e71e935ff282",
                    "displayName": "posts-webhook-1",
                    "description": "posts-webhook description",
                    "url": "https://jsonplaceholder.typicode.com/posts",
                    "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsuscipit recusandae consequuntur expedita et cumreprehenderit molestiae ut ut quas otamnostrum rerum est autem sunt rem eveniet architecto\"}",
                    "httpMethod": "POST",
                    "jansEnabled": true,
                    "httpHeaders": [{
                      "key": "Content-Type",
                      "value": "application/json"
                    }],
                    "auiFeatureIds": ["jans_link_write"],
                    "baseDn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans"
                  }
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookEntry'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    {
                      "dn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "2d3fe60f-db3f-3ab8-a285-e71e935ff282",
                      "displayName": "posts-webhook-1",
                      "description": "posts-webhook description",
                      "url": "https://jsonplaceholder.typicode.com/posts",
                      "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsuscipit recusandae consequuntur expedita et cumreprehenderit molestiae ut ut quas otamnostrum rerum est autem sunt rem eveniet architecto\"}",
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "auiFeatureIds": ["jans_link_write"],
                      "baseDn": "inum=2d3fe60f-db3f-3ab8-a285-e71e935ff282,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.write
    post:
      tags:
        - Admin UI - Webhooks
      summary: Create Webhook
      description: Create Webhook
      operationId: post-webhook
      requestBody:
        description: Webhook object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEntry'
            examples:
              Request json example:
                description: Request json example
                value: |
                  {
                    "displayName": "posts-webhook-1",
                    "description": "posts-webhook description",
                    "url": "https://reqres.in/api/users",
                    "httpRequestBody": {
                      "name": "morpheus",
                      "job": "leader"
                    },
                    "httpMethod": "POST",
                    "jansEnabled": true,
                    "httpHeaders":[{"key":"Content-Type", "value":"application/json"}],
                    "auiFeatureIds":["jans_link_write"]
                  }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scope'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    {
                      "dn": "inum=f704922d-e97f-3097-a06a-4a90ddedb87a,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "f704922d-e97f-3097-a06a-4a90ddedb87a",
                      "displayName": "posts-webhook-1",
                      "description": "posts-webhook description",
                      "url": "https://reqres.in/api/users",
                      "httpRequestBody": {
                        "name": "morpheus",
                        "job": "leader"
                      },
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "auiFeatureIds": ["jans_link_write"],
                      "baseDn": "inum=f704922d-e97f-3097-a06a-4a90ddedb87a,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.write
  '/admin-ui/webhook/{webhookId}':
    delete:
      tags:
        - Admin UI - Webhooks
      summary: Delete Webhook
      description: Delete Webhook
      operationId: delete-Webhook-by-inum
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.delete
  /admin-ui/webhook/features:
    get:
      tags:
        - Admin UI - Webhooks
      summary: Gets list of Admin UI features
      description: Gets list of Admin UI features
      operationId: get-all-features
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
  '/admin-ui/webhook/features/{webhookId}':
    get:
      tags:
        - Admin UI - Webhooks
      summary: Gets list of Admin UI features mapped to webhookId
      description: Gets list of Admin UI features mapped to webhookId
      operationId: get-features-by-webhook-id
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
  '/admin-ui/webhook/{featureId}':
    get:
      tags:
        - Admin UI - Webhooks
      summary: Gets list of Admin UI Webhooks mapped to featureId
      description: Gets list of Admin UI Webhooks mapped to featureId
      operationId: get-webhooks-by-feature-id
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookEntry'
              examples:
                Response json example:
                  description: Response json example
                  value: |
                    [{
                      "dn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "aad9e1dd-87f3-357f-a2fa-93ae8eb94998",
                      "displayName": "test-5",
                      "description": "test1",
                      "url": "https://jsonplaceholder.typicode.com/posts",
                      "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "baseDn": "inum=aad9e1dd-87f3-357f-a2fa-93ae8eb94998,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }, {
                      "dn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans",
                      "inum": "d23d60e8-0187-3878-94d9-30d594c4c986",
                      "displayName": "test-6",
                      "description": "test1",
                      "url": "https://jsonplaceholder.typicode.com/posts",
                      "httpRequestBody": "{\"userId\": 11,\"id\": 11,\"title\": \"sunt aut facere repellat provident occaecati excepturi optio reprehenderit\",\"body\": \"quia et suscipitsutem sunt rem eveniet architecto\"}",
                      "httpMethod": "POST",
                      "jansEnabled": true,
                      "httpHeaders": [{
                        "key": "Content-Type",
                        "value": "application/json"
                      }],
                      "baseDn": "inum=d23d60e8-0187-3878-94d9-30d594c4c986,ou=auiWebhooks,ou=admin-ui,o=jans"
                    }]
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
  '/admin-ui/webhook/trigger/{featureId}':
    post:
      tags:
        - Admin UI - Webhooks
      summary: Trigger webhooks mapped to featureId
      description: Trigger webhooks mapped to featureId
      operationId: trigger-webhook
      security:
        - oauth2:
            - >-
              https://jans.io/oauth/jans-auth-server/config/adminui/webhook.readonly
  /jans-link/link-config:
    get:
      tags:
        - Jans Link - Configuration
      summary: Gets Jans Link App configuration.
      description: Gets Jans Link App configuration.
      operationId: get-jans-link-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans-link.readonly'
    put:
      tags:
        - Jans Link - Configuration
      summary: Updates Jans Link configuration properties.
      description: Updates Jans Link configuration properties.
      operationId: put-jans-link-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/jans-link.write'
  /scim/scim-config:
    get:
      tags:
        - SCIM - Config Management
      summary: Retrieves SCIM App configuration
      description: Retrieves SCIM App configuration
      operationId: get-scim-config
      security:
        - oauth2:
            - 'https://jans.io/scim/config.readonly'
    patch:
      tags:
        - SCIM - Config Management
      summary: Patch SCIM App configuration
      description: Patch SCIM App configuration
      operationId: patch-scim-config
      security:
        - oauth2:
            - 'https://jans.io/scim/config.write'
  /kc/saml/idp/upload:
    put:
      tags:
        - SAML - Identity Broker
      summary: Update SAML Identity Provider
      description: Update SAML Identity Provider
      operationId: put-saml-identity-provider
      security:
        - oauth2:
            - 'https://jans.io/idp/saml.write'
    post:
      tags:
        - SAML - Identity Broker
      summary: Create SAML Identity Provider
      description: Create SAML Identity Provider
      operationId: post-saml-identity-provider
      security:
        - oauth2:
            - 'https://jans.io/idp/saml.write'
  '/kc/saml/idp/{inum}':
    get:
      tags:
        - SAML - Identity Broker
      summary: Get SAML Identity Provider by Inum
      description: Get SAML Identity Provider by Inum
      operationId: get-saml-identity-provider-by-inum
      security:
        - oauth2:
            - 'https://jans.io/idp/saml.readonly'
    delete:
      tags:
        - SAML - Identity Broker
      summary: Delete SAML Identity Provider
      description: Delete SAML Identity Provider
      operationId: delete-saml-identity-provider
      security:
        - oauth2:
            - 'https://jans.io/idp/saml.delete'
  /kc/saml/idp:
    get:
      tags:
        - SAML - Identity Broker
      summary: Retrieves SAML Identity Provider
      description: Retrieves SAML Identity Provider
      operationId: get-saml-identity-provider
      security:
        - oauth2:
            - 'https://jans.io/idp/saml.readonly'
  '/kc/saml/idp/sp-metadata/{inum}':
    get:
      tags:
        - SAML - Identity Broker
      summary: Get SAML SP Metadata as Json
      description: Get SAML SP Metadata as Json
      operationId: get-saml-sp-metadata-json
      security:
        - oauth2:
            - 'https://jans.io/idp/saml.readonly'
  '/kc/saml/idp/sp-metadata-file/{inum}':
    get:
      tags:
        - SAML - Identity Broker
      summary: Get SAML SP Metadata Endpoint URL
      description: Get SAML SP Metadata Endpoint URL
      operationId: get-saml-sp-metadata-url
      security:
        - oauth2:
            - 'https://jans.io/idp/saml.readonly'
  /kc/samlConfig:
    get:
      tags:
        - SAML - Configuration
      summary: Gets SAML configuration properties
      description: Gets SAML configuration properties
      operationId: get-saml-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml-config.readonly'
    put:
      tags:
        - SAML - Configuration
      summary: Update SAML configuration properties
      description: Update SAML configuration properties
      operationId: put-saml-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml-config.write'
    patch:
      tags:
        - SAML - Configuration
      summary: Partially modifies SAML configuration properties.
      description: Partially modifies SAML Configuration properties.
      operationId: patch-saml-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml-config.write'
  /kc/saml/trust-relationship/upload:
    put:
      tags:
        - SAML - Trust Relationship
      summary: Update TrustRelationship
      description: Update TrustRelationship
      operationId: put-trust-relationship
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml.write'
    post:
      tags:
        - SAML - Trust Relationship
      summary: Create Trust Relationship with Metadata File
      description: Create Trust Relationship with Metadata File
      operationId: post-trust-relationship-metadata-file
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml.write'
  '/kc/saml/trust-relationship/{id}':
    delete:
      tags:
        - SAML - Trust Relationship
      summary: Delete TrustRelationship
      description: Delete TrustRelationship
      operationId: delete-trust-relationship
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml.write'
  /kc/saml/trust-relationship:
    get:
      tags:
        - SAML - Trust Relationship
      summary: Get all Trust Relationship
      description: Get all TrustRelationship.
      operationId: get-trust-relationships
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml.readonly'
  '/kc/saml/trust-relationship/id/{id}':
    get:
      tags:
        - SAML - Trust Relationship
      summary: Get TrustRelationship by Id
      description: Get TrustRelationship by Id
      operationId: get-trust-relationship-by-id
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml.readonly'
  '/kc/saml/trust-relationship/sp-metadata-file/{id}':
    get:
      tags:
        - SAML - Trust Relationship
      summary: Get TrustRelationship file metadata
      description: Get TrustRelationship file metadata
      operationId: get-trust-relationship-file-metadata
      security:
        - oauth2:
            - 'https://jans.io/oauth/config/saml.readonly'
  /kc-link/kcLinkConfig:
    get:
      tags:
        - KC Link - Configuration
      summary: Gets KC Link configuration properties
      description: Gets KC Link configuration properties
      operationId: get-kc-link-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/kc-link-config.readonly'
    put:
      tags:
        - KC Link - Configuration
      summary: Update KC Link configuration properties
      description: Update KC Link configuration properties
      operationId: put-kc-link-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/kc-link-config.write'
    patch:
      tags:
        - KC Link - Configuration
      summary: Partially modifies KC Link configuration properties.
      description: Partially modifies KC Link configuration properties.
      operationId: patch-kc-link-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/kc-link-config.write'
  /lock/audit/health/search:
    get:
      tags:
        - Lock - Audit
      summary: Rerquest health records for specific event range
      description: Rerquest health records for specific event range
      operationId: request-lock-health-records-event-range
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/health.readonly'
  /lock/audit/log/search:
    get:
      tags:
        - Lock - Log
      summary: Rerquest log records for specific event range
      description: Rerquest log records for specific event range
      operationId: request-lock-log-records-event-range
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/log.readonly'
  /lock/audit/telemetry/search:
    get:
      tags:
        - Lock - Audit
      summary: Request telemetry records for specific event range
      description: Rerquest telemetry records for specific event range
      operationId: request-lock-telemetry-records-event-range
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/telemetry.readonly'
  /lock/audit/health/bulk:
    post:
      tags:
        - Lock - Audit
      summary: Bulk save health data
      description: Bulk save health data
      operationId: bulk-save-health-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/health.write'
  /lock/audit/log/bulk:
    post:
      tags:
        - Lock - Audit
      summary: Bulk save log data
      description: Bulk save log data
      operationId: bulk-save-log-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/log.write'
  /lock/audit/telemetry/bulk:
    post:
      tags:
        - Lock - Audit
      summary: Bulk save telemetry data
      description: Bulk save telemetry data
      operationId: bulk-save-telemetry-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/telemetry.write'
  /lock/audit/health:
    post:
      tags:
        - Lock - Audit
      summary: Save health data
      description: Save health data
      operationId: save-health-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/health.write'
  /lock/audit/log:
    post:
      tags:
        - Lock - Audit
      summary: Save log data
      description: Save log data
      operationId: save-log-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/log.write'
  /lock/audit/telemetry:
    post:
      tags:
        - Lock - Audit
      summary: Save telemetry data
      description: Save telemetry data
      operationId: save-telemetry-data
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock/telemetry.write'
  /lock/lockConfig:
    get:
      tags:
        - Lock - Configuration
      summary: Gets Lock configuration properties
      description: Gets Lock configuration properties
      operationId: get-lock-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock-config.readonly'
    put:
      tags:
        - Lock - Configuration
      summary: Update Lock configuration properties
      description: Update Lock configuration properties
      operationId: put-lock-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock-config.write'
    patch:
      tags:
        - Lock - Configuration
      summary: Partially modifies Lock configuration properties.
      description: Partially modifies Lock configuration properties.
      operationId: patch-lock-properties
      security:
        - oauth2:
            - 'https://jans.io/oauth/lock-config.write'
components:
  schemas:
    JsonNode:
      type: object
    HealthStatus:
      type: object
      properties:
        status:
          type: string
        checks:
          type: array
          items:
            $ref: '#/components/schemas/Status'
    Status:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
        error:
          type: string
    FacterData:
      type: object
      properties:
        memoryfree:
          type: string
        swapfree:
          type: string
        hostname:
          type: string
        ipaddress:
          type: string
        uptime:
          type: string
        free_disk_space:
          type: string
        load_average:
          type: string
    StatsData:
      type: object
      properties:
        dbType:
          type: string
        lastUpdate:
          type: string
          format: date-time
        facterData:
          $ref: '#/components/schemas/FacterData'
    AuthenticationMethod:
      type: object
      properties:
        defaultAcr:
          type: string
    ApiError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        description:
          type: string
    Deployment:
      type: object
      properties:
        dn:
          type: string
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        taskActive:
          type: boolean
        finishedAt:
          type: string
          format: date-time
        assets:
          type: string
        details:
          $ref: '#/components/schemas/DeploymentDetails'
        baseDn:
          type: string
    DeploymentDetails:
      type: object
      properties:
        folders:
          type: array
          items:
            type: string
        libs:
          type: array
          items:
            type: string
        error:
          type: string
        autoconfigure:
          type: boolean
        flowsError:
          type: object
          additionalProperties:
            type: string
        projectMetadata:
          $ref: '#/components/schemas/ProjectMetadata'
    ProjectMetadata:
      type: object
      properties:
        projectName:
          type: string
        author:
          type: string
        type:
          type: string
        description:
          type: string
        version:
          type: string
        configs:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
        noDirectLaunch:
          type: array
          items:
            type: string
    PagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            type: object
    Document:
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
        fileName:
          type: string
        filePath:
          type: string
        description:
          type: string
        document:
          type: string
        creationDate:
          type: string
          format: date-time
        service:
          type: string
        level:
          type: integer
          format: int32
        revision:
          type: integer
          format: int32
        enabled:
          type: boolean
        alias:
          type: string
        baseDn:
          type: string
    DocumentPagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            $ref: '#/components/schemas/Document'
    AssetDirMapping:
      type: object
      properties:
        directory:
          type: string
          description: Relative path to asset base directory.
        type:
          type: array
          description: List of file extention that are stored in directory.
          items:
            type: string
            description: List of file extention that are stored in directory.
        description:
          type: string
          description: Description of assets stored in directory.
        jansServiceModule:
          type: array
          description: List of supported service module where asset can be uploaded.
          items:
            type: string
            description: List of supported service module where asset can be uploaded.
      description: Asset type mapped to server directory.
    AssetForm:
      required:
        - assetFile
        - document
      type: object
      properties:
        document:
          $ref: '#/components/schemas/Document'
        assetFile:
          type: string
          format: binary
    AttributeValidation:
      type: object
      properties:
        minLength:
          type: integer
          format: int32
        maxLength:
          type: integer
          format: int32
        regexp:
          type: string
    JansAttribute:
      required:
        - dataType
        - description
        - displayName
        - editType
        - name
        - viewType
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
        sourceAttribute:
          type: string
        nameIdType:
          type: string
        name:
          maxLength: 30
          minLength: 1
          pattern: '^[a-zA-Z0-9_]+$'
          type: string
        displayName:
          maxLength: 60
          minLength: 0
          type: string
        description:
          maxLength: 4000
          minLength: 0
          type: string
        origin:
          type: string
        dataType:
          type: string
          enum:
            - string
            - numeric
            - boolean
            - binary
            - certificate
            - generalizedTime
            - json
        editType:
          type: array
          items:
            type: string
            enum:
              - admin
              - owner
              - manager
              - user
              - whitePages
        viewType:
          type: array
          items:
            type: string
            enum:
              - admin
              - owner
              - manager
              - user
              - whitePages
        usageType:
          type: array
          items:
            type: string
            enum:
              - openid
        claimName:
          type: string
        seeAlso:
          type: string
        status:
          type: string
          enum:
            - active
            - inactive
            - expired
            - register
        saml1Uri:
          type: string
        saml2Uri:
          type: string
        urn:
          type: string
        scimCustomAttr:
          type: boolean
        oxMultiValuedAttribute:
          type: boolean
        jansHideOnDiscovery:
          type: boolean
        custom:
          type: boolean
        attributeValidation:
          $ref: '#/components/schemas/AttributeValidation'
        tooltip:
          type: string
        whitePagesCanView:
          type: boolean
        userCanView:
          type: boolean
        adminCanEdit:
          type: boolean
        userCanEdit:
          type: boolean
        adminCanView:
          type: boolean
        userCanAccess:
          type: boolean
        adminCanAccess:
          type: boolean
        baseDn:
          type: string
    PatchRequest:
      type: object
      properties:
        op:
          type: string
        path:
          type: string
        value:
          type: string
    AppConfiguration:
      type: object
      properties:
        issuer:
          type: string
        baseEndpoint:
          type: string
        authorizationEndpoint:
          type: string
        authorizationChallengeEndpoint:
          type: string
        tokenEndpoint:
          type: string
        tokenRevocationEndpoint:
          type: string
        userInfoEndpoint:
          type: string
        clientInfoEndpoint:
          type: string
        checkSessionIFrame:
          type: string
        endSessionEndpoint:
          type: string
        jwksUri:
          type: string
        archivedJwksUri:
          type: string
        registrationEndpoint:
          type: string
        openIdDiscoveryEndpoint:
          type: string
        openIdConfigurationEndpoint:
          type: string
        idGenerationEndpoint:
          type: string
        introspectionEndpoint:
          type: string
        parEndpoint:
          type: string
        requirePar:
          type: boolean
        deviceAuthzEndpoint:
          type: string
        mtlsAuthorizationEndpoint:
          type: string
        mtlsAuthorizationChallengeEndpoint:
          type: string
        mtlsTokenEndpoint:
          type: string
        mtlsTokenRevocationEndpoint:
          type: string
        mtlsUserInfoEndpoint:
          type: string
        mtlsClientInfoEndpoint:
          type: string
        mtlsCheckSessionIFrame:
          type: string
        mtlsEndSessionEndpoint:
          type: string
        mtlsJwksUri:
          type: string
        mtlsRegistrationEndpoint:
          type: string
        mtlsIdGenerationEndpoint:
          type: string
        mtlsIntrospectionEndpoint:
          type: string
        mtlsParEndpoint:
          type: string
        mtlsDeviceAuthzEndpoint:
          type: string
        accessEvaluationAllowBasicClientAuthorization:
          type: boolean
        accessEvaluationScriptName:
          type: string
        requireRequestObjectEncryption:
          type: boolean
        requirePkce:
          type: boolean
        allowAllValueForRevokeEndpoint:
          type: boolean
        allowRevokeForOtherClients:
          type: boolean
        sectorIdentifierCacheLifetimeInMinutes:
          type: integer
          format: int32
        archivedJwkLifetimeInSeconds:
          type: integer
          format: int32
        umaConfigurationEndpoint:
          type: string
        umaRptAsJwt:
          type: boolean
        umaRptLifetime:
          type: integer
          format: int32
        umaTicketLifetime:
          type: integer
          format: int32
        umaPctLifetime:
          type: integer
          format: int32
        umaResourceLifetime:
          type: integer
          format: int32
        umaAddScopesAutomatically:
          type: boolean
        umaValidateClaimToken:
          type: boolean
        umaGrantAccessIfNoPolicies:
          type: boolean
        umaRestrictResourceToAssociatedClient:
          type: boolean
        statTimerIntervalInSeconds:
          type: integer
          format: int32
        statAuthorizationScope:
          type: string
        allowSpontaneousScopes:
          type: boolean
        spontaneousScopeLifetime:
          type: integer
          format: int32
        statusListBitSize:
          type: integer
          format: int32
        statusListResponseJwtSignatureAlgorithm:
          type: string
        statusListResponseJwtLifetime:
          type: integer
          format: int32
        statusListIndexAllocationBlockSize:
          type: integer
          format: int32
        openidSubAttribute:
          type: string
        publicSubjectIdentifierPerClientEnabled:
          type: boolean
        subjectIdentifiersPerClientSupported:
          type: array
          items:
            type: string
        applyXFrameOptionsHeaderIfUriContainsAny:
          type: array
          items:
            type: string
        xframeOptionsHeaderValue:
          type: string
          enum:
            - SAMEORIGIN
            - DENY
        responseTypesSupported:
          uniqueItems: true
          type: array
          items:
            uniqueItems: true
            type: array
            items:
              type: string
              enum:
                - code
                - token
                - id_token
        responseModesSupported:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
              - query
              - fragment
              - form_post
              - query.jwt
              - fragment.jwt
              - form_post.jwt
              - jwt
        grantTypesSupported:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
              - none
              - authorization_code
              - implicit
              - password
              - client_credentials
              - refresh_token
              - 'urn:ietf:params:oauth:grant-type:uma-ticket'
              - 'urn:ietf:params:oauth:grant-type:token-exchange'
              - 'urn:openid:params:grant-type:ciba'
              - 'urn:ietf:params:oauth:grant-type:device_code'
        subjectTypesSupported:
          type: array
          items:
            type: string
        defaultSubjectType:
          type: string
        authorizationSigningAlgValuesSupported:
          type: array
          items:
            type: string
        authorizationEncryptionAlgValuesSupported:
          type: array
          items:
            type: string
        authorizationEncryptionEncValuesSupported:
          type: array
          items:
            type: string
        userInfoSigningAlgValuesSupported:
          type: array
          items:
            type: string
        userInfoEncryptionAlgValuesSupported:
          type: array
          items:
            type: string
        userInfoEncryptionEncValuesSupported:
          type: array
          items:
            type: string
        introspectionSigningAlgValuesSupported:
          type: array
          items:
            type: string
        introspectionEncryptionAlgValuesSupported:
          type: array
          items:
            type: string
        introspectionEncryptionEncValuesSupported:
          type: array
          items:
            type: string
        txTokenSigningAlgValuesSupported:
          type: array
          items:
            type: string
        txTokenEncryptionAlgValuesSupported:
          type: array
          items:
            type: string
        txTokenEncryptionEncValuesSupported:
          type: array
          items:
            type: string
        idTokenSigningAlgValuesSupported:
          type: array
          items:
            type: string
        idTokenEncryptionAlgValuesSupported:
          type: array
          items:
            type: string
        idTokenEncryptionEncValuesSupported:
          type: array
          items:
            type: string
        accessTokenSigningAlgValuesSupported:
          type: array
          items:
            type: string
        forceSignedRequestObject:
          type: boolean
        requestObjectSigningAlgValuesSupported:
          type: array
          items:
            type: string
        requestObjectEncryptionAlgValuesSupported:
          type: array
          items:
            type: string
        requestObjectEncryptionEncValuesSupported:
          type: array
          items:
            type: string
        tokenEndpointAuthMethodsSupported:
          type: array
          items:
            type: string
        tokenEndpointAuthSigningAlgValuesSupported:
          type: array
          items:
            type: string
        dynamicRegistrationCustomAttributes:
          type: array
          items:
            type: string
        dynamicRegistrationDefaultCustomAttributes:
          $ref: '#/components/schemas/JsonNode'
        displayValuesSupported:
          type: array
          items:
            type: string
        claimTypesSupported:
          type: array
          items:
            type: string
        jwksAlgorithmsSupported:
          type: array
          items:
            type: string
        serviceDocumentation:
          type: string
        claimsLocalesSupported:
          type: array
          items:
            type: string
        idTokenTokenBindingCnfValuesSupported:
          type: array
          items:
            type: string
        uiLocalesSupported:
          type: array
          items:
            type: string
        claimsParameterSupported:
          type: boolean
        requestParameterSupported:
          type: boolean
        requestUriParameterSupported:
          type: boolean
        requestUriHashVerificationEnabled:
          type: boolean
        requireRequestUriRegistration:
          type: boolean
        requestUriBlockList:
          type: array
          items:
            type: string
        opPolicyUri:
          type: string
        opTosUri:
          type: string
        cleanUpInactiveClientAfterHoursOfInactivity:
          type: integer
          format: int32
        clientPeriodicUpdateTimerInterval:
          type: integer
          format: int32
        authorizationCodeLifetime:
          type: integer
          format: int32
        refreshTokenLifetime:
          type: integer
          format: int32
        txTokenLifetime:
          type: integer
          format: int32
        idTokenLifetime:
          type: integer
          format: int32
        idTokenFilterClaimsBasedOnAccessToken:
          type: boolean
        saveTokensInCache:
          type: boolean
        saveTokensInCacheAndDontSaveInPersistence:
          type: boolean
        accessTokenLifetime:
          type: integer
          format: int32
        cleanServiceInterval:
          type: integer
          format: int32
        cleanServiceBatchChunkSize:
          type: integer
          format: int32
        keyRegenerationEnabled:
          type: boolean
        keyRegenerationInterval:
          type: integer
          format: int32
        defaultSignatureAlgorithm:
          type: string
        jansOpenIdConnectVersion:
          type: string
        jansId:
          type: string
        dynamicRegistrationExpirationTime:
          type: integer
          format: int32
        dynamicRegistrationPersistClientAuthorizations:
          type: boolean
        trustedClientEnabled:
          type: boolean
        skipAuthorizationForOpenIdScopeAndPairwiseId:
          type: boolean
        dynamicRegistrationScopesParamEnabled:
          type: boolean
        dynamicRegistrationPasswordGrantTypeEnabled:
          type: boolean
        dynamicRegistrationAllowedPasswordGrantScopes:
          type: array
          items:
            type: string
        dynamicRegistrationCustomObjectClass:
          type: string
        personCustomObjectClassList:
          type: array
          items:
            type: string
        persistIdToken:
          type: boolean
        persistRefreshToken:
          type: boolean
        allowPostLogoutRedirectWithoutValidation:
          type: boolean
        invalidateSessionCookiesAfterAuthorizationFlow:
          type: boolean
        returnClientSecretOnRead:
          type: boolean
        rotateClientRegistrationAccessTokenOnUsage:
          type: boolean
        rejectJwtWithNoneAlg:
          type: boolean
        expirationNotificatorEnabled:
          type: boolean
        useNestedJwtDuringEncryption:
          type: boolean
        expirationNotificatorMapSizeLimit:
          type: integer
          format: int32
        expirationNotificatorIntervalInSeconds:
          type: integer
          format: int32
        redirectUrisRegexEnabled:
          type: boolean
        useHighestLevelScriptIfAcrScriptNotFound:
          type: boolean
        acrMappings:
          type: object
          additionalProperties:
            type: string
        authenticationFiltersEnabled:
          type: boolean
        clientAuthenticationFiltersEnabled:
          type: boolean
        clientRegDefaultToCodeFlowWithRefresh:
          type: boolean
        grantTypesAndResponseTypesAutofixEnabled:
          type: boolean
        authenticationFilters:
          type: array
          items:
            $ref: '#/components/schemas/AuthenticationFilter'
        clientAuthenticationFilters:
          type: array
          items:
            $ref: '#/components/schemas/ClientAuthenticationFilter'
        corsConfigurationFilters:
          type: array
          items:
            $ref: '#/components/schemas/CorsConfigurationFilter'
        sessionIdUnusedLifetime:
          type: integer
          format: int32
        sessionIdUnauthenticatedUnusedLifetime:
          type: integer
          format: int32
        sessionIdPersistOnPromptNone:
          type: boolean
        sessionIdRequestParameterEnabled:
          type: boolean
        changeSessionIdOnAuthentication:
          type: boolean
        sessionIdPersistInCache:
          type: boolean
        includeSidInResponse:
          type: boolean
        disablePromptLogin:
          type: boolean
        disablePromptConsent:
          type: boolean
        sessionIdCookieLifetime:
          type: integer
          format: int32
        sessionIdLifetime:
          type: integer
          format: int32
        activeSessionAuthorizationScope:
          type: string
        configurationUpdateInterval:
          type: integer
          format: int32
        logNotFoundEntityAsError:
          type: boolean
        enableClientGrantTypeUpdate:
          type: boolean
        grantTypesSupportedByDynamicRegistration:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
              - none
              - authorization_code
              - implicit
              - password
              - client_credentials
              - refresh_token
              - 'urn:ietf:params:oauth:grant-type:uma-ticket'
              - 'urn:ietf:params:oauth:grant-type:token-exchange'
              - 'urn:openid:params:grant-type:ciba'
              - 'urn:ietf:params:oauth:grant-type:device_code'
        cssLocation:
          type: string
        jsLocation:
          type: string
        imgLocation:
          type: string
        metricReporterInterval:
          type: integer
          format: int32
        metricReporterKeepDataDays:
          type: integer
          format: int32
        pairwiseIdType:
          type: string
        pairwiseCalculationKey:
          type: string
        pairwiseCalculationSalt:
          type: string
        shareSubjectIdBetweenClientsWithSameSectorId:
          type: boolean
        webKeysStorage:
          type: string
          enum:
            - keystore
            - pkcs11
        dnName:
          type: string
        keyStoreFile:
          type: string
        keyStoreSecret:
          type: string
        keySelectionStrategy:
          type: string
          enum:
            - OLDER
            - NEWER
            - FIRST
        keyAlgsAllowedForGeneration:
          type: array
          items:
            type: string
        keySignWithSameKeyButDiffAlg:
          type: boolean
        staticKid:
          type: string
        staticDecryptionKid:
          type: string
        introspectionAccessTokenMustHaveUmaProtectionScope:
          type: boolean
        introspectionAccessTokenMustHaveIntrospectionScope:
          type: boolean
        introspectionSkipAuthorization:
          type: boolean
        introspectionRestrictBasicAuthnToOwnTokens:
          type: boolean
        endSessionWithAccessToken:
          type: boolean
        disablePromptCreate:
          type: boolean
        cookieDomain:
          type: string
        enabledOAuthAuditLogging:
          type: boolean
        jmsBrokerURISet:
          uniqueItems: true
          type: array
          items:
            type: string
        jmsUserName:
          type: string
        jmsPassword:
          type: string
        externalUriWhiteList:
          type: array
          items:
            type: string
        clientWhiteList:
          type: array
          items:
            type: string
        clientBlackList:
          type: array
          items:
            type: string
        legacyIdTokenClaims:
          type: boolean
        customHeadersWithAuthorizationResponse:
          type: boolean
        frontChannelLogoutSessionSupported:
          type: boolean
        loggingLevel:
          type: string
        loggingLayout:
          type: string
        updateUserLastLogonTime:
          type: boolean
        updateClientAccessTime:
          type: boolean
        logClientIdOnClientAuthentication:
          type: boolean
        logClientNameOnClientAuthentication:
          type: boolean
        disableJdkLogger:
          type: boolean
        authorizationRequestCustomAllowedParameters:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationRequestCustomParameter'
        openidScopeBackwardCompatibility:
          type: boolean
        disableU2fEndpoint:
          type: boolean
        authorizationChallengeSessionLifetimeInSeconds:
          type: integer
          format: int32
        rotateDeviceSecret:
          type: boolean
        returnDeviceSecretFromAuthzEndpoint:
          type: boolean
        dcrForbidExpirationTimeInRequest:
          type: boolean
        dcrSignatureValidationEnabled:
          type: boolean
        dcrSignatureValidationSharedSecret:
          type: string
        dcrSignatureValidationSoftwareStatementJwksURIClaim:
          type: string
        dcrSignatureValidationSoftwareStatementJwksClaim:
          type: string
        dcrSignatureValidationJwks:
          type: string
        dcrSignatureValidationJwksUri:
          type: string
        dcrAuthorizationWithClientCredentials:
          type: boolean
        dcrAuthorizationWithMTLS:
          type: boolean
        dcrAttestationEvidenceRequired:
          type: boolean
        trustedSsaIssuers:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TrustedIssuerConfig'
        useLocalCache:
          type: boolean
        fapiCompatibility:
          type: boolean
        forceIdTokenHintPresence:
          type: boolean
        rejectEndSessionIfIdTokenExpired:
          type: boolean
        allowEndSessionWithUnmatchedSid:
          type: boolean
        forceOfflineAccessScopeToEnableRefreshToken:
          type: boolean
        errorReasonEnabled:
          type: boolean
        removeRefreshTokensForClientOnLogout:
          type: boolean
        skipRefreshTokenDuringRefreshing:
          type: boolean
        refreshTokenExtendLifetimeOnRotation:
          type: boolean
        allowBlankValuesInDiscoveryResponse:
          type: boolean
        checkUserPresenceOnRefreshToken:
          type: boolean
        consentGatheringScriptBackwardCompatibility:
          type: boolean
        introspectionScriptBackwardCompatibility:
          type: boolean
        introspectionResponseScopesBackwardCompatibility:
          type: boolean
        softwareStatementValidationType:
          type: string
        softwareStatementValidationClaimName:
          type: string
        authenticationProtectionConfiguration:
          $ref: '#/components/schemas/AuthenticationProtectionConfiguration'
        errorHandlingMethod:
          type: string
          enum:
            - internal
            - remote
        disableAuthnForMaxAgeZero:
          type: boolean
        keepAuthenticatorAttributesOnAcrChange:
          type: boolean
        deviceAuthzRequestExpiresIn:
          type: integer
          format: int32
        deviceAuthzTokenPollInterval:
          type: integer
          format: int32
        deviceAuthzResponseTypeToProcessAuthz:
          type: string
        deviceAuthzAcr:
          type: string
        backchannelClientId:
          type: string
        backchannelRedirectUri:
          type: string
        backchannelAuthenticationEndpoint:
          type: string
        backchannelDeviceRegistrationEndpoint:
          type: string
        backchannelTokenDeliveryModesSupported:
          type: array
          items:
            type: string
        backchannelAuthenticationRequestSigningAlgValuesSupported:
          type: array
          items:
            type: string
        backchannelUserCodeParameterSupported:
          type: boolean
        backchannelBindingMessagePattern:
          type: string
        backchannelAuthenticationResponseExpiresIn:
          type: integer
          format: int32
        backchannelAuthenticationResponseInterval:
          type: integer
          format: int32
        backchannelLoginHintClaims:
          type: array
          items:
            type: string
        cibaEndUserNotificationConfig:
          $ref: '#/components/schemas/CIBAEndUserNotificationConfig'
        backchannelRequestsProcessorJobIntervalSec:
          type: integer
          format: int32
        backchannelRequestsProcessorJobChunkSize:
          type: integer
          format: int32
        cibaGrantLifeExtraTimeSec:
          type: integer
          format: int32
        cibaMaxExpirationTimeAllowedSec:
          type: integer
          format: int32
        dpopSigningAlgValuesSupported:
          type: array
          items:
            type: string
        dpopTimeframe:
          type: integer
          format: int32
        dpopJtiCacheTime:
          type: integer
          format: int32
        dpopUseNonce:
          type: boolean
        dpopNonceCacheTime:
          type: integer
          format: int32
        dpopJktForceForAuthorizationCode:
          type: boolean
        allowIdTokenWithoutImplicitGrantType:
          type: boolean
        forceRopcInAuthorizationEndpoint:
          type: boolean
        discoveryCacheLifetimeInMinutes:
          type: integer
          format: int32
        discoveryAllowedKeys:
          type: array
          items:
            type: string
        discoveryDenyKeys:
          type: array
          items:
            type: string
        featureFlags:
          type: array
          items:
            type: string
            enum:
              - UNKNOWN
              - HEALTH_CHECK
              - USERINFO
              - CLIENTINFO
              - ID_GENERATION
              - REGISTRATION
              - INTROSPECTION
              - REVOKE_TOKEN
              - REVOKE_SESSION
              - GLOBAL_TOKEN_REVOCATION
              - STATUS_LIST
              - ACTIVE_SESSION
              - END_SESSION
              - STATUS_SESSION
              - JANS_CONFIGURATION
              - CIBA
              - UMA
              - U2F
              - DEVICE_AUTHZ
              - METRIC
              - STAT
              - PAR
              - ACCESS_EVALUATION
              - SSA
        httpLoggingEnabled:
          type: boolean
        httpLoggingExcludePaths:
          uniqueItems: true
          type: array
          items:
            type: string
        externalLoggerConfiguration:
          type: string
        agamaConfiguration:
          $ref: '#/components/schemas/EngineConfig'
        dcrSsaValidationConfigs:
          type: array
          items:
            $ref: '#/components/schemas/SsaValidationConfig'
        ssaConfiguration:
          $ref: '#/components/schemas/SsaConfiguration'
        blockWebviewAuthorizationEnabled:
          type: boolean
        authorizationChallengeDefaultAcr:
          type: string
        authorizationChallengeShouldGenerateSession:
          type: boolean
        dateFormatterPatterns:
          type: object
          additionalProperties:
            type: string
        httpLoggingResponseBodyContent:
          type: boolean
        skipAuthenticationFilterOptionsMethod:
          type: boolean
        lockMessageConfig:
          $ref: '#/components/schemas/LockMessageConfig'
        fapi:
          type: boolean
        allResponseTypesSupported:
          uniqueItems: true
          type: array
          items:
            type: string
            enum:
              - code
              - token
              - id_token
    AuthenticationFilter:
      required:
        - baseDn
        - filter
      type: object
      properties:
        filter:
          type: string
        bind:
          type: boolean
        bindPasswordAttribute:
          type: string
          xml:
            name: bind-password-attribute
        baseDn:
          type: string
          xml:
            name: base-dn
    AuthenticationProtectionConfiguration:
      type: object
      properties:
        attemptExpiration:
          type: integer
          format: int32
        maximumAllowedAttemptsWithoutDelay:
          type: integer
          format: int32
        delayTime:
          type: integer
          format: int32
        bruteForceProtectionEnabled:
          type: boolean
    AuthorizationRequestCustomParameter:
      type: object
      properties:
        paramName:
          type: string
        returnInResponse:
          type: boolean
    CIBAEndUserNotificationConfig:
      type: object
      properties:
        apiKey:
          type: string
        authDomain:
          type: string
        databaseURL:
          type: string
        projectId:
          type: string
        storageBucket:
          type: string
        messagingSenderId:
          type: string
        appId:
          type: string
        notificationUrl:
          type: string
        notificationKey:
          type: string
        publicVapidKey:
          type: string
    ClientAuthenticationFilter:
      required:
        - baseDn
        - filter
      type: object
      properties:
        filter:
          type: string
        bind:
          type: boolean
        bindPasswordAttribute:
          type: string
          xml:
            name: bind-password-attribute
        baseDn:
          type: string
          xml:
            name: base-dn
    CorsConfigurationFilter:
      type: object
      properties:
        filterName:
          type: string
        corsEnabled:
          type: boolean
        corsAllowedOrigins:
          type: string
        corsAllowedMethods:
          type: string
        corsAllowedHeaders:
          type: string
        corsExposedHeaders:
          type: string
        corsSupportCredentials:
          type: boolean
        corsLoggingEnabled:
          type: boolean
        corsPreflightMaxAge:
          type: integer
          format: int32
        corsRequestDecorate:
          type: boolean
      description: CORS configuration filter properties.
    EngineConfig:
      type: object
      properties:
        enabled:
          type: boolean
        rootDir:
          type: string
        templatesPath:
          type: string
        scriptsPath:
          type: string
        maxItemsLoggedInCollections:
          type: integer
          format: int32
        disableTCHV:
          type: boolean
        pageMismatchErrorPage:
          type: string
        interruptionErrorPage:
          type: string
        crashErrorPage:
          type: string
        finishedFlowPage:
          type: string
        bridgeScriptPage:
          type: string
        serializeRules:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        defaultResponseHeaders:
          type: object
          additionalProperties:
            type: string
    LockMessageConfig:
      type: object
      properties:
        enableTokenMessages:
          type: boolean
        tokenMessagesChannel:
          type: string
    SsaConfiguration:
      type: object
      properties:
        ssaEndpoint:
          type: string
        ssaCustomAttributes:
          type: array
          items:
            type: string
        ssaSigningAlg:
          type: string
        ssaExpirationInDays:
          type: integer
          format: int32
    SsaValidationConfig:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - NONE
            - SSA
            - DCR
        displayName:
          type: string
        description:
          type: string
        scopes:
          type: array
          items:
            type: string
        allowedClaims:
          type: array
          items:
            type: string
        jwks:
          type: string
        jwksUri:
          type: string
        issuers:
          type: array
          items:
            type: string
        configurationEndpoint:
          type: string
        configurationEndpointClaim:
          type: string
        sharedSecret:
          type: string
    TrustedIssuerConfig:
      type: object
      properties:
        automaticallyGrantedScopes:
          type: array
          items:
            type: string
    PersistenceConfiguration:
      type: object
      properties:
        persistenceType:
          type: string
    JsonPatch:
      type: object
    CacheConfiguration:
      type: object
      properties:
        cacheProviderType:
          type: string
          enum:
            - IN_MEMORY
            - MEMCACHED
            - REDIS
            - NATIVE_PERSISTENCE
        memcachedConfiguration:
          $ref: '#/components/schemas/MemcachedConfiguration'
        inMemoryConfiguration:
          $ref: '#/components/schemas/InMemoryConfiguration'
        redisConfiguration:
          $ref: '#/components/schemas/RedisConfiguration'
        nativePersistenceConfiguration:
          $ref: '#/components/schemas/NativePersistenceConfiguration'
    InMemoryConfiguration:
      type: object
      properties:
        defaultPutExpiration:
          type: integer
          format: int32
    MemcachedConfiguration:
      type: object
      properties:
        servers:
          type: string
        maxOperationQueueLength:
          type: integer
          format: int32
        bufferSize:
          type: integer
          format: int32
        defaultPutExpiration:
          type: integer
          format: int32
        connectionFactoryType:
          type: string
          enum:
            - DEFAULT
            - BINARY
    NativePersistenceConfiguration:
      type: object
      properties:
        defaultPutExpiration:
          type: integer
          format: int32
        defaultCleanupBatchSize:
          type: integer
          format: int32
        deleteExpiredOnGetRequest:
          type: boolean
        disableAttemptUpdateBeforeInsert:
          type: boolean
    RedisConfiguration:
      type: object
      properties:
        redisProviderType:
          type: string
          enum:
            - STANDALONE
            - CLUSTER
            - SHARDED
            - SENTINEL
        servers:
          type: string
        defaultPutExpiration:
          type: integer
          format: int32
        sentinelMasterGroupName:
          type: string
        password:
          type: string
        useSSL:
          type: boolean
        sslTrustStoreFilePath:
          type: string
        sslTrustStorePassword:
          type: string
        sslKeyStoreFilePath:
          type: string
        sslKeyStorePassword:
          type: string
        maxIdleConnections:
          type: integer
          format: int32
        maxTotalConnections:
          type: integer
          format: int32
        connectionTimeout:
          type: integer
          format: int32
        soTimeout:
          type: integer
          format: int32
        maxRetryAttempts:
          type: integer
          format: int32
    ClientAuth:
      type: object
      properties:
        clientAuths:
          type: object
          additionalProperties:
            uniqueItems: true
            type: array
            items:
              $ref: '#/components/schemas/Scope'
    Scope:
      type: object
      properties:
        dn:
          type: string
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        inum:
          type: string
        displayName:
          type: string
        id:
          type: string
        iconUrl:
          type: string
        description:
          type: string
        scopeType:
          type: string
          enum:
            - openid
            - dynamic
            - uma
            - spontaneous
            - oauth
        claims:
          type: array
          items:
            type: string
        defaultScope:
          type: boolean
        groupClaims:
          type: boolean
        dynamicScopeScripts:
          type: array
          items:
            type: string
        umaAuthorizationPolicies:
          type: array
          items:
            type: string
        attributes:
          $ref: '#/components/schemas/ScopeAttributes'
        creatorId:
          type: string
        creatorType:
          type: string
          enum:
            - none
            - client
            - user
            - auto
        creationDate:
          type: string
          format: date-time
        creatorAttributes:
          type: object
          additionalProperties:
            type: string
        umaType:
          type: boolean
        baseDn:
          type: string
    ScopeAttributes:
      type: object
      properties:
        spontaneousClientScopes:
          type: array
          items:
            type: string
        showInConfigurationEndpoint:
          type: boolean
    Client:
      type: object
      properties:
        dn:
          type: string
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        clientSecret:
          type: string
        frontChannelLogoutUri:
          type: string
        frontChannelLogoutSessionRequired:
          type: boolean
        registrationAccessToken:
          type: string
        clientIdIssuedAt:
          type: string
          format: date-time
        clientSecretExpiresAt:
          type: string
          format: date-time
        redirectUris:
          type: array
          items:
            type: string
        claimRedirectUris:
          type: array
          items:
            type: string
        responseTypes:
          type: array
          items:
            type: string
            enum:
              - code
              - token
              - id_token
        grantTypes:
          type: array
          items:
            type: string
            enum:
              - none
              - authorization_code
              - implicit
              - password
              - client_credentials
              - refresh_token
              - 'urn:ietf:params:oauth:grant-type:uma-ticket'
              - 'urn:ietf:params:oauth:grant-type:token-exchange'
              - 'urn:openid:params:grant-type:ciba'
              - 'urn:ietf:params:oauth:grant-type:device_code'
        applicationType:
          type: string
          enum:
            - native
            - web
        contacts:
          type: array
          items:
            type: string
        idTokenTokenBindingCnf:
          type: string
        clientName:
          type: string
        logoUri:
          type: string
        clientUri:
          type: string
        policyUri:
          type: string
        tosUri:
          type: string
        clientNameLocalized:
          $ref: '#/components/schemas/LocalizedString'
        logoUriLocalized:
          $ref: '#/components/schemas/LocalizedString'
        clientUriLocalized:
          $ref: '#/components/schemas/LocalizedString'
        policyUriLocalized:
          $ref: '#/components/schemas/LocalizedString'
        tosUriLocalized:
          $ref: '#/components/schemas/LocalizedString'
        jwksUri:
          type: string
        jwks:
          type: string
        sectorIdentifierUri:
          type: string
        subjectType:
          type: string
          enum:
            - pairwise
            - public
        idTokenSignedResponseAlg:
          type: string
        idTokenEncryptedResponseAlg:
          type: string
        idTokenEncryptedResponseEnc:
          type: string
        userInfoSignedResponseAlg:
          type: string
        userInfoEncryptedResponseAlg:
          type: string
        userInfoEncryptedResponseEnc:
          type: string
        requestObjectSigningAlg:
          type: string
        requestObjectEncryptionAlg:
          type: string
        requestObjectEncryptionEnc:
          type: string
        tokenEndpointAuthMethod:
          type: string
          format: enum
          enum:
            - client_secret_basic
            - client_secret_post
            - client_secret_jwt
            - private_key_jwt
            - access_token
            - tls_client_auth
            - self_signed_tls_client_auth
            - none
        tokenEndpointAuthSigningAlg:
          type: string
        defaultMaxAge:
          type: integer
          format: int32
        defaultAcrValues:
          type: array
          items:
            type: string
        initiateLoginUri:
          type: string
        postLogoutRedirectUris:
          type: array
          items:
            type: string
        requestUris:
          type: array
          items:
            type: string
        scopes:
          type: array
          items:
            type: string
        claims:
          type: array
          items:
            type: string
        trustedClient:
          type: boolean
        lastAccessTime:
          type: string
          format: date-time
        lastLogonTime:
          type: string
          format: date-time
        persistClientAuthorizations:
          type: boolean
        includeClaimsInIdToken:
          type: boolean
        refreshTokenLifetime:
          type: integer
          format: int32
        accessTokenLifetime:
          type: integer
          format: int32
        customAttributes:
          type: array
          items:
            $ref: '#/components/schemas/CustomObjectAttribute'
        customObjectClasses:
          type: array
          items:
            type: string
        rptAsJwt:
          type: boolean
        accessTokenAsJwt:
          type: boolean
        accessTokenSigningAlg:
          type: string
        disabled:
          type: boolean
        authorizedOrigins:
          type: array
          items:
            type: string
        softwareId:
          type: string
        softwareVersion:
          type: string
        softwareStatement:
          type: string
        attributes:
          $ref: '#/components/schemas/ClientAttributes'
        backchannelTokenDeliveryMode:
          type: string
          enum:
            - poll
            - ping
            - push
        backchannelClientNotificationEndpoint:
          type: string
        backchannelAuthenticationRequestSigningAlg:
          type: string
          enum:
            - RS256
            - RS384
            - RS512
            - ES256
            - ES384
            - ES512
            - PS256
            - PS384
            - PS512
        backchannelUserCodeParameter:
          type: boolean
        description:
          type: string
        organization:
          type: string
        groups:
          type: array
          items:
            type: string
        ttl:
          type: integer
          format: int32
        displayName:
          type: string
        baseDn:
          type: string
        inum:
          type: string
    ClientAttributes:
      type: object
      properties:
        tlsClientAuthSubjectDn:
          type: string
        runIntrospectionScriptBeforeJwtCreation:
          type: boolean
        keepClientAuthorizationAfterExpiration:
          type: boolean
        allowSpontaneousScopes:
          type: boolean
        spontaneousScopes:
          type: array
          items:
            type: string
        spontaneousScopeScriptDns:
          type: array
          items:
            type: string
        updateTokenScriptDns:
          type: array
          items:
            type: string
        backchannelLogoutUri:
          type: array
          items:
            type: string
        backchannelLogoutSessionRequired:
          type: boolean
        additionalAudience:
          type: array
          items:
            type: string
        postAuthnScripts:
          type: array
          items:
            type: string
        consentGatheringScripts:
          type: array
          items:
            type: string
        introspectionScripts:
          type: array
          items:
            type: string
        rptClaimsScripts:
          type: array
          items:
            type: string
        ropcScripts:
          type: array
          items:
            type: string
        parLifetime:
          type: integer
          format: int32
        requirePar:
          type: boolean
        dpopBoundAccessToken:
          type: boolean
        jansAuthSignedRespAlg:
          type: string
        jansAuthEncRespAlg:
          type: string
        jansAuthEncRespEnc:
          type: string
        jansSubAttr:
          type: string
        redirectUrisRegex:
          type: string
        jansAuthorizedAcr:
          type: array
          items:
            type: string
        jansDefaultPromptLogin:
          type: boolean
        txTokenLifetime:
          type: integer
          format: int32
        idTokenLifetime:
          type: integer
          format: int32
        allowOfflineAccessWithoutConsent:
          type: boolean
        minimumAcrLevel:
          type: integer
          format: int32
        minimumAcrLevelAutoresolve:
          type: boolean
        additionalTokenEndpointAuthMethods:
          type: array
          items:
            type: string
        minimumAcrPriorityList:
          type: array
          items:
            type: string
        requestedLifetime:
          type: integer
          format: int32
        evidence:
          type: string
        introspectionSignedResponseAlg:
          type: string
        introspectionEncryptedResponseAlg:
          type: string
        introspectionEncryptedResponseEnc:
          type: string
        txTokenSignedResponseAlg:
          type: string
        txTokenEncryptedResponseAlg:
          type: string
        txTokenEncryptedResponseEnc:
          type: string
        authorizationDetailsTypes:
          type: array
          items:
            type: string
    CustomObjectAttribute:
      type: object
      properties:
        name:
          type: string
        multiValued:
          type: boolean
        values:
          type: array
          items:
            type: object
        displayValue:
          type: string
        value:
          type: object
    LocalizedString:
      type: object
      properties:
        values:
          type: object
          additionalProperties:
            type: string
    AgamaConfiguration:
      type: object
      properties:
        mandatoryAttributes:
          type: array
          description: List of attributes required to create the Agama Flow.
          items:
            type: string
            description: List of attributes required to create the Agama Flow.
        optionalAttributes:
          type: array
          description: List of attributes that are optional.
          items:
            type: string
            description: List of attributes that are optional.
      description: Agama configuration details.
    ApiAppConfiguration:
      type: object
      properties:
        serviceName:
          type: string
          description: Config API service name.
        configOauthEnabled:
          type: boolean
          description: OAuth authentication enable/disable flag. Default value `true`.
        disableLoggerTimer:
          type: boolean
          description: >-
            Flag to enable/disable timer to dynamically reflect log
            configuration changes. Default value `true`Default value `false`.
        disableAuditLogger:
          type: boolean
          description: Flag to enable/disable request audit. Default value `false`.
        customAttributeValidationEnabled:
          type: boolean
          description: >-
            Flag to enable/disable check if custom attribue is declared in
            schema. Default value `true`.
        acrValidationEnabled:
          type: boolean
          description: >-
            Flag to enable/disable check if acr customScript is enabled. Default
            value `true`.
        apiApprovedIssuer:
          type: array
          description: List of approved external Auth server to validate token.
          items:
            type: string
            description: List of approved external Auth server to validate token.
        apiProtectionType:
          type: string
          description: >-
            Name of supported API protection mechansim. Supported type is
            `OAuth2`.
        apiClientId:
          type: string
          description: Config-API client ID.
        apiClientPassword:
          type: string
          description: Config-API client password.
        endpointInjectionEnabled:
          type: boolean
        authIssuerUrl:
          type: string
          description: Issuer Identifier of Jans OpenID Connect Provider.
        authOpenidConfigurationUrl:
          type: string
          description: Jans OpenID Connect Provider Well-Known Configuration URL.
        authOpenidIntrospectionUrl:
          type: string
          description: >-
            Jans URL of the OpenID Connect Provider's OAuth 2.0 Authorization
            Endpoint.
        authOpenidTokenUrl:
          type: string
          description: Jans URL of the OpenID Connect Provider's OAuth 2.0 Token Endpoint.
        authOpenidRevokeUrl:
          type: string
          description: >-
            Jans URL of the OpenID Connect Provider's OAuth 2.0 Revoke Token
            Endpoint.
        exclusiveAuthScopes:
          type: array
          description: >-
            List of oAuth scope that can be validity for an access tokens only
            by underlying Jans Auth server.
          items:
            type: string
            description: >-
              List of oAuth scope that can be validity for an access tokens only
              by underlying Jans Auth server.
        corsConfigurationFilters:
          type: array
          description: CORS configuration filter properties.
          items:
            $ref: '#/components/schemas/CorsConfigurationFilter'
        loggingLevel:
          type: string
          description: Specify logging level of Loggers. Default level is `INFO`.
        loggingLayout:
          type: string
          description: Log4j logging layout. Default value `TEXT`.
        externalLoggerConfiguration:
          type: string
          description: The path to the external log4j2 logging configuration.
        disableJdkLogger:
          type: boolean
          description: Choose whether to disable JDK loggers.
        maxCount:
          type: integer
          description: Maximum number of results per page in search endpoints.
          format: int32
        acrExclusionList:
          type: array
          description: >-
            List of ACR values that should be excluded from active validation
            check.
          items:
            type: string
            description: >-
              List of ACR values that should be excluded from active validation
              check.
        userExclusionAttributes:
          type: array
          description: User attribute that should not be returned in response.
          items:
            type: string
            description: User attribute that should not be returned in response.
        userMandatoryAttributes:
          type: array
          description: List of User mandatory attribute for user creation request.
          items:
            type: string
            description: List of User mandatory attribute for user creation request.
        agamaConfiguration:
          $ref: '#/components/schemas/AgamaConfiguration'
        auditLogConf:
          $ref: '#/components/schemas/AuditLogConf'
        dataFormatConversionConf:
          $ref: '#/components/schemas/DataFormatConversionConf'
        plugins:
          type: array
          description: Details of enabled plugins.
          items:
            $ref: '#/components/schemas/PluginConf'
        assetMgtConfiguration:
          $ref: '#/components/schemas/AssetMgtConfiguration'
    AssetMgtConfiguration:
      type: object
      properties:
        assetMgtEnabled:
          type: boolean
          description: Flag indicating if asset management functionality is enabled.
        assetServerUploadEnabled:
          type: boolean
          description: Flag indicating if asset upload to server is enabled.
        fileExtensionValidationEnabled:
          type: boolean
          description: Flag indicating if file extension validation is enabled.
        moduleNameValidationEnabled:
          type: boolean
          description: >-
            Flag indicating if service module name extension validation is
            enabled.
        assetDirMapping:
          type: array
          description: Asset type mapped to server directory.
          items:
            $ref: '#/components/schemas/AssetDirMapping'
      description: Asset management configuration details.
    AuditLogConf:
      type: object
      properties:
        enabled:
          type: boolean
          description: Flag to enable and disable audit log.
        ignoreHttpMethod:
          type: array
          description: HTTP methods for which audit is disabled.
          items:
            type: string
            description: HTTP methods for which audit is disabled.
        headerAttributes:
          type: array
          description: List of header HTTP attributes whose value is to be logged.
          items:
            type: string
            description: List of header HTTP attributes whose value is to be logged.
      description: Audit Log configuration details.
    DataFormatConversionConf:
      type: object
      properties:
        enabled:
          type: boolean
          description: Flag to enable and disable data conversion.
        ignoreHttpMethod:
          type: array
          description: HTTP methods for which data conversion is to be disabled.
          items:
            type: string
            description: HTTP methods for which data conversion is to be disabled.
      description: Configuration for data-type converstion.
    PluginConf:
      type: object
      properties:
        name:
          type: string
          description: Name of the plugin.
        description:
          type: string
          description: Description of the plugin.
        className:
          type: string
          description: Plugin application class.
    SmtpConfiguration:
      type: object
      properties:
        valid:
          type: boolean
        host:
          type: string
        port:
          type: integer
          format: int32
        connect_protection:
          type: string
          enum:
            - None
            - StartTls
            - SslTls
        trust_host:
          type: boolean
        from_name:
          type: string
        from_email_address:
          type: string
        requires_authentication:
          type: boolean
        smtp_authentication_account_username:
          type: string
        smtp_authentication_account_password:
          type: string
        key_store:
          type: string
        key_store_password:
          type: string
        key_store_alias:
          type: string
        signing_algorithm:
          type: string
    SmtpTest:
      type: object
      properties:
        sign:
          type: boolean
        subject:
          type: string
        message:
          type: string
    CustomScript:
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
        name:
          maxLength: 60
          minLength: 2
          pattern: '^[a-zA-Z0-9_\-\:\/\.]+$'
          type: string
        aliases:
          type: array
          items:
            type: string
        description:
          type: string
        script:
          type: string
        scriptType:
          type: string
          enum:
            - person_authentication
            - authorization_challenge
            - introspection
            - resource_owner_password_credentials
            - application_session
            - cache_refresh
            - client_registration
            - id_generator
            - uma_rpt_policy
            - uma_rpt_claims
            - uma_claims_gathering
            - access_evaluation
            - consent_gathering
            - dynamic_scope
            - spontaneous_scope
            - end_session
            - post_authn
            - client_authn
            - select_account
            - create_user
            - scim
            - ciba_end_user_notification
            - revoke_token
            - persistence_extension
            - idp
            - discovery
            - health_check
            - authz_detail
            - update_token
            - config_api_auth
            - modify_ssa_response
            - fido2_extension
            - lock_extension
        programmingLanguage:
          type: string
          enum:
            - python
            - java
        moduleProperties:
          type: array
          items:
            $ref: '#/components/schemas/SimpleCustomProperty'
        configurationProperties:
          type: array
          items:
            $ref: '#/components/schemas/SimpleExtendedCustomProperty'
        level:
          type: integer
          format: int32
        revision:
          type: integer
          format: int64
        enabled:
          type: boolean
        scriptError:
          $ref: '#/components/schemas/ScriptError'
        modified:
          type: boolean
        internal:
          type: boolean
        locationType:
          type: string
          enum:
            - ldap
            - db
            - file
        locationPath:
          type: string
        baseDn:
          type: string
    ScriptError:
      type: object
      properties:
        raisedAt:
          type: string
          format: date-time
        stackTrace:
          type: string
    SimpleCustomProperty:
      type: object
      properties:
        value1:
          type: string
        value2:
          type: string
        description:
          type: string
    SimpleExtendedCustomProperty:
      type: object
      properties:
        value1:
          type: string
        value2:
          type: string
        hide:
          type: boolean
        description:
          type: string
    JSONWebKey:
      type: object
      properties:
        name:
          type: string
        descr:
          type: string
        kid:
          type: string
        kty:
          type: string
          enum:
            - EC
            - RSA
            - OKP
            - oct
        use:
          type: string
          enum:
            - sig
            - enc
        alg:
          type: string
          enum:
            - RS256
            - RS384
            - RS512
            - ES256
            - ES256K
            - ES384
            - ES512
            - PS256
            - PS384
            - PS512
            - EdDSA
            - RSA1_5
            - RSA-OAEP
            - RSA-OAEP-256
            - ECDH-ES
            - ECDH-ES+A128KW
            - ECDH-ES+A192KW
            - ECDH-ES+A256KW
            - A128KW
            - A192KW
            - A256KW
            - A128GCMKW
            - A192GCMKW
            - A256GCMKW
            - PBES2-HS256+A128KW
            - PBES2-HS384+A192KW
            - PBES2-HS512+A256KW
            - dir
        exp:
          type: integer
          format: int64
        crv:
          type: string
          enum:
            - P-256
            - P-256K
            - P-384
            - P-521
            - Ed25519
            - Ed448
        x5c:
          type: array
          items:
            type: string
        'n':
          type: string
        e:
          type: string
        x:
          type: string
        'y':
          type: string
        key_ops_type:
          type: array
          items:
            type: string
            enum:
              - 'KeyOps{value=''connect''} CONNECT'
              - 'KeyOps{value=''ssa''} SSA'
              - 'KeyOps{value=''all''} ALL'
    WebKeysConfiguration:
      type: object
      properties:
        keys:
          type: array
          items:
            $ref: '#/components/schemas/JSONWebKey'
    GluuLdapConfiguration:
      type: object
      properties:
        configId:
          type: string
        bindDN:
          type: string
        bindPassword:
          type: string
        servers:
          type: array
          items:
            type: string
        maxConnections:
          type: integer
          format: int32
        useSSL:
          type: boolean
        baseDNs:
          type: array
          items:
            type: string
        primaryKey:
          type: string
        localPrimaryKey:
          type: string
        useAnonymousBind:
          type: boolean
        enabled:
          type: boolean
        version:
          type: integer
          format: int32
        level:
          type: integer
          format: int32
    Logging:
      type: object
      properties:
        loggingLevel:
          type: string
        loggingLayout:
          type: string
        httpLoggingEnabled:
          type: boolean
        disableJdkLogger:
          type: boolean
        enabledOAuthAuditLogging:
          type: boolean
        externalLoggerConfiguration:
          type: string
        httpLoggingExcludePaths:
          uniqueItems: true
          type: array
          items:
            type: string
    MessageConfiguration:
      type: object
      properties:
        messageProviderType:
          type: string
          enum:
            - DISABLED
            - REDIS
            - POSTGRES
        redisConfiguration:
          $ref: '#/components/schemas/RedisMessageConfiguration'
        postgresConfiguration:
          $ref: '#/components/schemas/PostgresMessageConfiguration'
    PostgresMessageConfiguration:
      type: object
      properties:
        driverClassName:
          type: string
        dbSchemaName:
          type: string
        connectionUri:
          type: string
        authUserName:
          type: string
        authUserPassword:
          type: string
        connectionPoolMaxTotal:
          type: integer
          format: int32
        connectionPoolMaxIdle:
          type: integer
          format: int32
        connectionPoolMinIdle:
          type: integer
          format: int32
        messageWaitMillis:
          type: integer
          format: int32
        messageSleepThreadTime:
          type: integer
          format: int32
    RedisMessageConfiguration:
      type: object
      properties:
        redisProviderType:
          type: string
          enum:
            - STANDALONE
            - CLUSTER
            - SHARDED
            - SENTINEL
        servers:
          type: string
        defaultPutExpiration:
          type: integer
          format: int32
        sentinelMasterGroupName:
          type: string
        password:
          type: string
        useSSL:
          type: boolean
        sslTrustStoreFilePath:
          type: string
        sslTrustStorePassword:
          type: string
        sslKeyStoreFilePath:
          type: string
        sslKeyStorePassword:
          type: string
        maxIdleConnections:
          type: integer
          format: int32
        maxTotalConnections:
          type: integer
          format: int32
        connectionTimeout:
          type: integer
          format: int32
        soTimeout:
          type: integer
          format: int32
        maxRetryAttempts:
          type: integer
          format: int32
    GluuOrganization:
      required:
        - description
        - displayName
      type: object
      properties:
        dn:
          type: string
        displayName:
          maxLength: 60
          minLength: 0
          type: string
        description:
          maxLength: 60
          minLength: 0
          type: string
        member:
          type: string
        countryName:
          type: string
        organization:
          type: string
        status:
          type: string
          enum:
            - active
            - inactive
            - expired
            - register
        managerGroup:
          type: string
        themeColor:
          type: string
        shortName:
          type: string
        customMessages:
          type: array
          items:
            type: string
        title:
          type: string
        jsLogoPath:
          type: string
        jsFaviconPath:
          type: string
        baseDn:
          type: string
    CustomScope:
      type: object
      properties:
        dn:
          type: string
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        inum:
          type: string
        displayName:
          type: string
        id:
          type: string
        iconUrl:
          type: string
        description:
          type: string
        scopeType:
          type: string
          enum:
            - openid
            - dynamic
            - uma
            - spontaneous
            - oauth
        claims:
          type: array
          items:
            type: string
        defaultScope:
          type: boolean
        groupClaims:
          type: boolean
        dynamicScopeScripts:
          type: array
          items:
            type: string
        umaAuthorizationPolicies:
          type: array
          items:
            type: string
        attributes:
          $ref: '#/components/schemas/ScopeAttributes'
        creatorId:
          type: string
        creatorType:
          type: string
          enum:
            - none
            - client
            - user
            - auto
        creationDate:
          type: string
          format: date-time
        creatorAttributes:
          type: object
          additionalProperties:
            type: string
        clients:
          type: array
          items:
            $ref: '#/components/schemas/Client'
        umaType:
          type: boolean
        baseDn:
          type: string
    SessionId:
      type: object
      properties:
        dn:
          type: string
        id:
          type: string
        outsideSid:
          type: string
        lastUsedAt:
          type: string
          format: date-time
        userDn:
          type: string
        authenticationTime:
          type: string
          format: date-time
        state:
          type: string
          enum:
            - unauthenticated
            - authenticated
        sessionState:
          type: string
        permissionGranted:
          type: boolean
        permissionGrantedMap:
          $ref: '#/components/schemas/SessionIdAccessMap'
        sessionAttributes:
          type: object
          additionalProperties:
            type: string
        deviceSecrets:
          type: array
          items:
            type: string
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        creationDate:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/User'
        ttl:
          type: integer
          format: int32
        persisted:
          type: boolean
        opbrowserState:
          type: string
    SessionIdAccessMap:
      type: object
      properties:
        permissionGranted:
          type: object
          additionalProperties:
            type: boolean
          xml:
            name: map
    SessionPagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            $ref: '#/components/schemas/SessionId'
    User:
      type: object
      properties:
        dn:
          type: string
        userId:
          type: string
        updatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        oxAuthPersistentJwt:
          type: array
          items:
            type: string
        externalUid:
          type: array
          items:
            type: string
        authenticator:
          $ref: '#/components/schemas/UserAuthenticatorList'
        status:
          type: string
          enum:
            - active
            - inactive
            - expired
            - register
        customAttributes:
          type: array
          items:
            $ref: '#/components/schemas/CustomObjectAttribute'
        customObjectClasses:
          type: array
          items:
            type: string
        baseDn:
          type: string
    UserAuthenticator:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        custom:
          type: object
          additionalProperties:
            type: object
    UserAuthenticatorList:
      type: object
      properties:
        authenticators:
          type: array
          items:
            $ref: '#/components/schemas/UserAuthenticator'
    TokenAttributes:
      type: object
      properties:
        x5cs256:
          type: string
        online_access:
          type: boolean
        attributes:
          type: object
          additionalProperties:
            type: string
        dpopJkt:
          type: string
        authorizationDetails:
          type: string
        statusListIndex:
          type: integer
          format: int32
    TokenEntity:
      type: object
      properties:
        dn:
          type: string
        grantId:
          type: string
        userId:
          type: string
        userDn:
          type: string
        clientId:
          type: string
        creationDate:
          type: string
          format: date-time
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        authenticationTime:
          type: string
          format: date-time
        scope:
          type: string
        tokenCode:
          type: string
        tokenType:
          type: string
        grantType:
          type: string
        jwtRequest:
          type: string
        authorizationCode:
          type: string
        nonce:
          type: string
        codeChallenge:
          type: string
        codeChallengeMethod:
          type: string
        claims:
          type: string
        tokenBindingHash:
          type: string
        referenceId:
          type: string
        authMode:
          type: string
        sessionDn:
          type: string
        ttl:
          type: integer
          format: int32
        attributes:
          $ref: '#/components/schemas/TokenAttributes'
        dpop:
          type: string
        tokenTypeEnum:
          type: string
          enum:
            - ID_TOKEN
            - ACCESS_TOKEN
            - LONG_LIVED_ACCESS_TOKEN
            - REFRESH_TOKEN
            - AUTHORIZATION_CODE
            - TX_TOKEN
    TokenEntityPagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            $ref: '#/components/schemas/TokenEntity'
    UmaResource:
      required:
        - name
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
        id:
          type: string
        name:
          type: string
        iconUri:
          type: string
        scopes:
          type: array
          items:
            type: string
        scopeExpression:
          type: string
        clients:
          type: array
          items:
            type: string
        resources:
          type: array
          items:
            type: string
        creator:
          type: string
        description:
          type: string
        type:
          type: string
        creationDate:
          type: string
          format: date-time
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        ttl:
          type: integer
          format: int32
    AppConfiguration1:
      type: object
      properties:
        issuer:
          type: string
        baseEndpoint:
          type: string
        cleanServiceInterval:
          type: integer
          format: int32
        cleanServiceBatchChunkSize:
          type: integer
          format: int32
        useLocalCache:
          type: boolean
        disableJdkLogger:
          type: boolean
        loggingLevel:
          type: string
        loggingLayout:
          type: string
        externalLoggerConfiguration:
          type: string
        metricReporterInterval:
          type: integer
          format: int32
        metricReporterKeepDataDays:
          type: integer
          format: int32
        metricReporterEnabled:
          type: boolean
        personCustomObjectClassList:
          type: array
          items:
            type: string
        superGluuEnabled:
          type: boolean
        sessionIdPersistInCache:
          type: boolean
        oldU2fMigrationEnabled:
          type: boolean
        errorReasonEnabled:
          type: boolean
        fido2Configuration:
          $ref: '#/components/schemas/Fido2Configuration'
    Fido2Configuration:
      type: object
      properties:
        authenticatorCertsFolder:
          type: string
        mdsAccessToken:
          type: string
        mdsCertsFolder:
          type: string
        mdsTocsFolder:
          type: string
        checkU2fAttestations:
          type: boolean
        userAutoEnrollment:
          type: boolean
        unfinishedRequestExpiration:
          type: integer
          format: int32
        authenticationHistoryExpiration:
          type: integer
          format: int32
        serverMetadataFolder:
          type: string
        requestedCredentialTypes:
          type: array
          items:
            type: string
        requestedParties:
          type: array
          items:
            $ref: '#/components/schemas/RequestedParty'
        metadataUrlsProvider:
          type: string
        skipDownloadMdsEnabled:
          type: boolean
        skipValidateMdsInAttestationEnabled:
          type: boolean
        assertionOptionsGenerateEndpointEnabled:
          type: boolean
    RequestedParty:
      type: object
      properties:
        name:
          type: string
        domains:
          type: array
          items:
            type: string
    Fido2DeviceData:
      type: object
      properties:
        uuid:
          type: string
        token:
          type: string
          writeOnly: true
        type:
          type: string
        platform:
          type: string
        name:
          type: string
        os_name:
          type: string
        os_version:
          type: string
        custom_data:
          type: object
          additionalProperties:
            type: string
        push_token:
          type: string
    Fido2DeviceNotificationConf:
      type: object
      properties:
        sns_endpoint_arn:
          type: string
        sns_endpoint_arn_remove:
          type: string
        sns_endpoint_arn_history:
          type: array
          items:
            type: string
    Fido2RegistrationData:
      type: object
      properties:
        createdDate:
          type: string
          format: date-time
        updatedDate:
          type: string
          format: date-time
        createdBy:
          type: string
        updatedBy:
          type: string
        username:
          type: string
        domain:
          type: string
        userId:
          type: string
        challenge:
          type: string
        attenstationRequest:
          type: string
        attenstationResponse:
          type: string
        uncompressedECPoint:
          type: string
        publicKeyId:
          type: string
        type:
          type: string
        status:
          type: string
          enum:
            - pending
            - registered
            - compromised
            - canceled
        counter:
          type: integer
          format: int32
        attestationType:
          type: string
        signatureAlgorithm:
          type: integer
          format: int32
        applicationId:
          type: string
    Fido2RegistrationEntry:
      type: object
      properties:
        dn:
          type: string
        id:
          type: string
        challange:
          type: string
        challengeHash:
          type: integer
          format: int32
        creationDate:
          type: string
          format: date-time
        userInum:
          type: string
        rpId:
          type: string
        sessionStateId:
          type: string
        expirationDate:
          type: string
          format: date-time
        deletable:
          type: boolean
        ttl:
          type: integer
          format: int32
        displayName:
          type: string
        publicKeyId:
          type: string
        publicKeyIdHash:
          type: integer
          format: int32
        registrationData:
          $ref: '#/components/schemas/Fido2RegistrationData'
        counter:
          type: integer
          format: int32
        registrationStatus:
          type: string
          enum:
            - pending
            - registered
            - compromised
            - canceled
        deviceNotificationConf:
          $ref: '#/components/schemas/Fido2DeviceNotificationConf'
        deviceData:
          $ref: '#/components/schemas/Fido2DeviceData'
        expiration:
          type: integer
          format: int32
          writeOnly: true
        baseDn:
          type: string
    Fido2RegistrationEntryPagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            $ref: '#/components/schemas/Fido2RegistrationEntry'
    CustomUser:
      type: object
      properties:
        dn:
          type: string
        userId:
          type: string
        updatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        oxAuthPersistentJwt:
          type: array
          items:
            type: string
        externalUid:
          type: array
          items:
            type: string
        authenticator:
          $ref: '#/components/schemas/UserAuthenticatorList'
        status:
          type: string
          enum:
            - active
            - inactive
            - expired
            - register
        customAttributes:
          type: array
          items:
            $ref: '#/components/schemas/CustomObjectAttribute'
        customObjectClasses:
          type: array
          items:
            type: string
        inum:
          type: string
        mail:
          type: string
        displayName:
          type: string
        givenName:
          type: string
        userPassword:
          type: string
        baseDn:
          type: string
    UserPagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            $ref: '#/components/schemas/CustomUser'
    UserPatchRequest:
      type: object
      properties:
        jsonPatchString:
          type: string
        customAttributes:
          type: array
          items:
            $ref: '#/components/schemas/CustomObjectAttribute'
    AdminPermission:
      type: object
      properties:
        tag:
          type: string
        permission:
          type: string
        description:
          type: string
        defaultPermissionInToken:
          type: boolean
    GenericResponse:
      type: object
      properties:
        success:
          type: boolean
        responseMessage:
          type: string
        responseCode:
          type: integer
          format: int32
        responseObject:
          $ref: '#/components/schemas/JsonNode'
    RolePermissionMapping:
      type: object
      properties:
        role:
          type: string
        permissions:
          type: array
          items:
            type: string
    AdminRole:
      type: object
      properties:
        role:
          type: string
        description:
          type: string
        deletable:
          type: boolean
    AppConfigResponse:
      type: object
      properties:
        authServerHost:
          type: string
          description: Auth Server host
          readOnly: true
        authzBaseUrl:
          type: string
          description: Authorization base URL
          readOnly: true
        clientId:
          type: string
          description: OIDC Client ID
          readOnly: true
        responseType:
          type: string
          description: OIDC Client Secret
          readOnly: true
        scope:
          type: string
          description: Scope
          readOnly: true
        redirectUrl:
          type: string
          description: Redirect URL
          readOnly: true
        acrValues:
          type: string
          description: ACR Value
        frontChannelLogoutUrl:
          type: string
          description: Front Channel Logout URL
          readOnly: true
        postLogoutRedirectUri:
          type: string
          description: Post Logout Redirect URL
          readOnly: true
        endSessionEndpoint:
          type: string
          description: End Session Endpoint
          readOnly: true
        sessionTimeoutInMins:
          type: integer
          description: Admin UI Session Timeout
          format: int32
        allowSmtpKeystoreEdit:
          type: boolean
          description: Admin UI allow SMTP Keystore Edit
        additionalParameters:
          type: array
          description: Additional Authentication Parameters
          items:
            $ref: '#/components/schemas/KeyValuePair'
    KeyValuePair:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    LicenseRequest:
      type: object
      properties:
        licenseKey:
          type: string
    LicenseResponse:
      type: object
      properties:
        licenseEnabled:
          type: boolean
        productName:
          type: string
        productCode:
          type: string
        licenseType:
          type: string
        maxActivations:
          type: integer
          format: int32
        licenseKey:
          type: string
        licenseActive:
          type: boolean
        validityPeriod:
          type: string
        companyName:
          type: string
        customerEmail:
          type: string
        customerFirstName:
          type: string
        customerLastName:
          type: string
        licenseExpired:
          type: boolean
    SSARequest:
      type: object
      properties:
        ssa:
          type: string
    WebhookEntry:
      required:
        - displayName
        - url
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
        displayName:
          maxLength: 60
          minLength: 2
          pattern: '^[a-zA-Z0-9_\-\:\/\.]+$'
          type: string
        description:
          type: string
        url:
          type: string
        httpRequestBodyString:
          type: string
        httpMethod:
          type: string
        jansEnabled:
          type: boolean
        httpHeaders:
          type: array
          items:
            $ref: '#/components/schemas/KeyValuePair'
        auiFeatureIds:
          uniqueItems: true
          type: array
          items:
            type: string
        httpRequestBody:
          type: object
          additionalProperties:
            type: object
        baseDn:
          type: string
    AuiFeature:
      type: object
      properties:
        dn:
          type: string
        auiFeatureId:
          type: string
        displayName:
          type: string
        jansScope:
          type: string
        webhookIdsMapped:
          type: array
          items:
            type: string
        baseDn:
          type: string
    ShortCodeRequest:
      required:
        - webhookId
      type: object
      properties:
        webhookId:
          type: string
        shortcodeValueMap:
          type: object
          additionalProperties:
            type: object
    AppConfiguration2:
      type: object
      properties:
        sourceConfigs:
          type: array
          items:
            $ref: '#/components/schemas/GluuLdapConfiguration'
        inumConfig:
          $ref: '#/components/schemas/GluuLdapConfiguration'
        targetConfig:
          $ref: '#/components/schemas/GluuLdapConfiguration'
        ldapSearchSizeLimit:
          type: integer
          format: int32
        keyAttributes:
          type: array
          items:
            type: string
        keyObjectClasses:
          type: array
          items:
            type: string
        sourceAttributes:
          type: array
          items:
            type: string
        customLdapFilter:
          type: string
        updateMethod:
          type: string
        defaultInumServer:
          type: boolean
        keepExternalPerson:
          type: boolean
        useSearchLimit:
          type: boolean
        attributeMapping:
          type: array
          items:
            $ref: '#/components/schemas/CacheRefreshAttributeMapping'
        snapshotFolder:
          type: string
        snapshotMaxCount:
          type: integer
          format: int32
        baseDN:
          type: string
        personObjectClassTypes:
          type: array
          items:
            type: string
        personCustomObjectClass:
          type: string
        contactObjectClassTypes:
          type: array
          items:
            type: string
        allowPersonModification:
          type: boolean
        supportedUserStatus:
          type: array
          items:
            type: string
        loggingLevel:
          type: string
        loggingLayout:
          type: string
        externalLoggerConfiguration:
          type: string
        metricReporterInterval:
          type: integer
          format: int32
        metricReporterKeepDataDays:
          type: integer
          format: int32
        metricReporterEnabled:
          type: boolean
        disableJdkLogger:
          type: boolean
        cleanServiceInterval:
          type: integer
          format: int32
        linkEnabled:
          type: boolean
        serverIpAddress:
          type: string
        pollingInterval:
          type: string
        lastUpdate:
          type: string
          format: date-time
        lastUpdateCount:
          type: string
        problemCount:
          type: string
        useLocalCache:
          type: boolean
    CacheRefreshAttributeMapping:
      type: object
      properties:
        source:
          type: string
        destination:
          type: string
    AppConfiguration3:
      type: object
      properties:
        baseDN:
          type: string
        applicationUrl:
          type: string
        baseEndpoint:
          type: string
        personCustomObjectClass:
          type: string
        oxAuthIssuer:
          type: string
        protectionMode:
          type: string
          enum:
            - OAUTH
            - BYPASS
        maxCount:
          type: integer
          format: int32
        bulkMaxOperations:
          type: integer
          format: int32
        bulkMaxPayloadSize:
          type: integer
          format: int64
        userExtensionSchemaURI:
          type: string
        loggingLevel:
          type: string
        loggingLayout:
          type: string
        externalLoggerConfiguration:
          type: string
        metricReporterInterval:
          type: integer
          format: int32
        metricReporterKeepDataDays:
          type: integer
          format: int32
        metricReporterEnabled:
          type: boolean
        disableJdkLogger:
          type: boolean
        disableLoggerTimer:
          type: boolean
        useLocalCache:
          type: boolean
        skipDefinedPasswordValidation:
          type: boolean
    BrokerIdentityProviderForm:
      required:
        - identityProvider
        - metaDataFile
      type: object
      properties:
        identityProvider:
          $ref: '#/components/schemas/IdentityProvider'
        metaDataFile:
          type: string
          format: binary
    IdentityProvider:
      required:
        - creatorId
        - description
        - displayName
        - name
        - realm
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
          description: Unique identifier.
        creatorId:
          type: string
          description: Creator of IDP.
        name:
          type: string
          description: Name uniquely identifies an identity provider.
        displayName:
          maxLength: 60
          minLength: 0
          type: string
          description: Identity provider display name.
        description:
          maxLength: 500
          minLength: 0
          type: string
          description: Description of Identity provider.
        realm:
          type: string
          description: Realm in which Identity provider is created.
        enabled:
          type: boolean
          description: Indicates if Identity provider is enabled.
        signingCertificate:
          type: string
          description: Digital certificate used to verify the authenticity of the request.
        validateSignature:
          type: string
        singleLogoutServiceUrl:
          type: string
          description: Url used to send logout requests.
        nameIDPolicyFormat:
          type: string
          description: ' URI reference corresponding to a name identifier format.'
        principalAttribute:
          type: string
          description: ' Name or Friendly Name of the attribute used to identify external users.'
        principalType:
          type: string
          description: Way to identify and track external users from the assertion.
        idpEntityId:
          type: string
          description: >-
            Entity ID that will be used to uniquely identify this SAML Service
            Provider.
        singleSignOnServiceUrl:
          type: string
          description: Url used to send SAML authentication requests.
        encryptionPublicKey:
          type: string
          description: Public key to use to encrypt the message.
        providerId:
          type: string
          description: 'IDP provider, should be SAML.'
        trustEmail:
          type: boolean
          description: >-
            If enabled, email provided by this provider is not verified even if
            verification is enabled for the realm.
        storeToken:
          type: boolean
          description: Enable/disable if tokens must be stored after authenticating users.
        addReadTokenRoleOnCreate:
          type: boolean
          description: Enable/disable if new users can read any stored tokens.
        authenticateByDefault:
          type: boolean
        linkOnly:
          type: boolean
          description: >-
            If true, users cannot log in through this provider. They can only
            link to this provider.
        firstBrokerLoginFlowAlias:
          type: string
          description: >-
            Alias of authentication flow, which is triggered after first login
            with this identity provider. Term 'First Login' means that no
            Keycloak account is currently linked to the authenticated identity
            provider account.
        postBrokerLoginFlowAlias:
          type: string
          description: >-
            Alias of authentication flow, which is triggered after each login
            with this identity provider.
        spMetaDataURL:
          type: string
          description: SAML SP metadata file URL.
        spMetaDataLocation:
          type: string
          description: SP metadata file location.
        idpMetaDataURL:
          type: string
          description: SAML IDP metadata file URL.
        idpMetaDataLocation:
          type: string
          description: SAML IDP metadata file location.
        status:
          type: string
          description: IDP setup status.
          enum:
            - active
            - inactive
            - expired
            - register
        validationStatus:
          type: string
          description: IDP validation status.
          enum:
            - In Progress
            - Success
            - Scheduled
            - Failed
        validationLog:
          type: array
          description: IDP validation log.
          items:
            type: string
            description: IDP validation log.
        baseDn:
          type: string
    IdentityProviderPagedResult:
      type: object
      properties:
        start:
          type: integer
          format: int32
        totalEntriesCount:
          type: integer
          format: int32
        entriesCount:
          type: integer
          format: int32
        entries:
          type: array
          items:
            $ref: '#/components/schemas/IdentityProvider'
    SamlAppConfiguration:
      type: object
      properties:
        applicationName:
          type: string
          description: Name of application.
        samlTrustRelationshipDn:
          type: string
          description: Trust relationship organizational unit.
        trustedIdpDn:
          type: string
          description: Identity provider organizational unit.
        enabled:
          type: boolean
          description: SAML functionality enabled.
        selectedIdp:
          type: string
          description: Selected SAML server.
        serverUrl:
          type: string
          description: SAML server URL.
        realm:
          type: string
          description: 'SAML server realm, default is `jans`.'
        clientId:
          type: string
          description: Jans auth SAML client ID.
        clientSecret:
          type: string
          description: Jans auth SAML client password.
        grantType:
          type: string
          description: Grant type to get access token.
        scope:
          type: string
          description: Oauth2 scope to get access token.
        username:
          type: string
          description: SAML server username.
        password:
          type: string
          description: SAML server user credentails.
        spMetadataUrl:
          type: string
          description: Relative SAML server SP Metadata Url.
        tokenUrl:
          type: string
          description: Relative SAML server Token Url.
        idpUrl:
          type: string
          description: Relative SAML server IDP Url.
        extIDPTokenUrl:
          type: string
          description: Relative SAML server IDP Token Url.
        extIDPRedirectUrl:
          type: string
          description: Relative IDP redirect Url.
        idpMetadataImportUrl:
          type: string
          description: Relative SAML server Metadata import Url.
        idpRootDir:
          type: string
          description: Jans Auth server root SAML directory.
        idpMetadataDir:
          type: string
          description: >-
            Jans Auth server relative SAML directory to store IDP Metadata
            files.
        idpMetadataTempDir:
          type: string
          description: >-
            Jans Auth server relative SAML temp directory to store IDP Metadata
            files.
        idpMetadataFile:
          type: string
          description: IDP Metadata file name format.
        spMetadataDir:
          type: string
          description: Jans Auth server relative SAML directory to store SP Metadata files.
        spMetadataTempDir:
          type: string
          description: >-
            Jans Auth server relative SAML temp directory to store SP Metadata
            files.
        spMetadataFile:
          type: string
          description: SP Metadata file name format.
        ignoreValidation:
          type: boolean
          description: Boolean value to enable/disable SAML validation.
        setConfigDefaultValue:
          type: boolean
          description: Boolean value `true` to set the default values for an IDP.
        idpMetadataMandatoryAttributes:
          type: array
          description: List of mandatory IDP Metadata attributes.
          items:
            type: string
            description: List of mandatory IDP Metadata attributes.
        kcAttributes:
          type: array
          description: Keycloak SAML attribute names.
          items:
            type: string
            description: Keycloak SAML attribute names.
        kcSamlConfig:
          type: array
          description: Keycloak SAML config attribute names.
          items:
            type: string
            description: Keycloak SAML config attribute names.
    ProfileConfiguration:
      type: object
      properties:
        name:
          type: string
        signResponses:
          type: string
      description: List of profile configuration.
    SAMLMetadata:
      type: object
      properties:
        nameIDPolicyFormat:
          type: string
          description: ' URI reference corresponding to a name identifier format.'
        entityId:
          type: string
          description: >-
            Entity ID that will be used to uniquely identify this SAML Service
            Provider.
        singleLogoutServiceUrl:
          type: string
          description: Url used to send logout requests.
        jansAssertionConsumerServiceGetURL:
          type: string
          description: >-
            GET URL the Identity provider (IdP) will send the SAML Response
            containing the assertions.
        jansAssertionConsumerServicePostURL:
          type: string
          description: >-
            POST URL the Identity provider (IdP) will send the SAML Response
            containing the assertions.
      description: SAML entity metadata.
    TrustRelationship:
      required:
        - description
        - displayName
        - name
        - spMetaDataSourceType
      type: object
      properties:
        dn:
          type: string
        inum:
          type: string
          description: Unique identifier
        owner:
          type: string
          description: Creator of Trust Relationship.
        name:
          maxLength: 60
          minLength: 0
          type: string
          description: >-
            The alphanumeric ID string that is used to identify the Trust
            Relationship.
        displayName:
          maxLength: 60
          minLength: 0
          type: string
          description: Trust Relationship display name.
        description:
          maxLength: 4000
          minLength: 0
          type: string
          description: Description of the Trust Relationship.
        baseUrl:
          type: string
          description: URL to use when the auth server needs to redirect.
        enabled:
          type: boolean
          description: Indicates if Trust Relationship is enabled.
        alwaysDisplayInConsole:
          type: boolean
          description: Indicates if Trust Relationship should always be listed in the UI.
        clientAuthenticatorType:
          type: string
          description: Preferred Authenticator Type.
        secret:
          type: string
          description: Client secret.
        registrationAccessToken:
          type: string
          description: Registration access token.
        consentRequired:
          type: boolean
          description: Boolean value if consent is required.
        spMetaDataSourceType:
          type: string
          description: 'Trust Relationship SP metadata type - file, URI.'
          enum:
            - file
            - manual
        samlMetadata:
          $ref: '#/components/schemas/SAMLMetadata'
        redirectUris:
          type: array
          description: List of valid Redirect URI.
          items:
            type: string
            description: List of valid Redirect URI.
        spMetaDataURL:
          type: string
          description: SAML entity metadata file URL.
        metaLocation:
          type: string
          description: Trust Relationship metadata file location.
        releasedAttributes:
          type: array
          description: Trust Relationship attributes that will be released to SAML server.
          items:
            type: string
            description: >-
              Trust Relationship attributes that will be released to SAML
              server.
        spLogoutURL:
          pattern: >-
            ^$|(^(https?|http)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|])
          type: string
          description: Logout request URL.
        status:
          type: string
          description: Trust Relationship setup status.
          enum:
            - active
            - inactive
            - expired
            - register
        validationStatus:
          type: string
          description: Trust Relationship validation status.
          enum:
            - In Progress
            - Success
            - Scheduled
            - Failed
        validationLog:
          type: array
          description: Validation log.
          items:
            type: string
            description: Validation log.
        profileConfigurations:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ProfileConfiguration'
          description: List of profile configuration.
        baseDn:
          type: string
    TrustRelationshipForm:
      required:
        - metaDataFile
        - trustRelationship
      type: object
      properties:
        trustRelationship:
          $ref: '#/components/schemas/TrustRelationship'
        metaDataFile:
          type: string
          format: binary
    AppConfiguration4:
      type: object
      properties:
        sourceConfigs:
          type: array
          items:
            $ref: '#/components/schemas/GluuLdapConfiguration'
        inumConfig:
          $ref: '#/components/schemas/GluuLdapConfiguration'
        targetConfig:
          $ref: '#/components/schemas/GluuLdapConfiguration'
        ldapSearchSizeLimit:
          type: integer
          format: int32
        keyAttributes:
          type: array
          items:
            type: string
        keyObjectClasses:
          type: array
          items:
            type: string
        sourceAttributes:
          type: array
          items:
            type: string
        customLdapFilter:
          type: string
        updateMethod:
          type: string
        defaultInumServer:
          type: boolean
        keepExternalPerson:
          type: boolean
        useSearchLimit:
          type: boolean
        attributeMapping:
          type: array
          items:
            $ref: '#/components/schemas/CacheRefreshAttributeMapping'
        snapshotFolder:
          type: string
        snapshotMaxCount:
          type: integer
          format: int32
        keycloakConfiguration:
          $ref: '#/components/schemas/KeycloakConfiguration'
        baseDN:
          type: string
        personObjectClassTypes:
          type: array
          items:
            type: string
        personCustomObjectClass:
          type: string
        contactObjectClassTypes:
          type: array
          items:
            type: string
        allowPersonModification:
          type: boolean
        supportedUserStatus:
          type: array
          items:
            type: string
        loggingLevel:
          type: string
        loggingLayout:
          type: string
        externalLoggerConfiguration:
          type: string
        metricReporterInterval:
          type: integer
          format: int32
        metricReporterKeepDataDays:
          type: integer
          format: int32
        metricReporterEnabled:
          type: boolean
        disableJdkLogger:
          type: boolean
        cleanServiceInterval:
          type: integer
          format: int32
        keycloakLinkEnabled:
          type: boolean
        keycloakLinkServerIpAddress:
          type: string
        keycloakLinkPollingInterval:
          type: string
        keycloakLinkLastUpdate:
          type: string
          format: date-time
        keycloakLinkLastUpdateCount:
          type: string
        keycloakLinkProblemCount:
          type: string
        useLocalCache:
          type: boolean
    KeycloakConfiguration:
      type: object
      properties:
        serverUrl:
          type: string
        realm:
          type: string
        clientId:
          type: string
        clientSecret:
          type: string
        grantType:
          type: string
        username:
          type: string
        password:
          type: string
    HealthEntry:
      type: object
      properties:
        dn:
          type: string
        creationDate:
          type: string
          format: date-time
        eventTime:
          type: string
          format: date-time
        service:
          type: string
        nodeName:
          type: string
        status:
          type: string
        engineStatus:
          type: string
        baseDn:
          type: string
        inum:
          type: string
    LogEntry:
      type: object
      properties:
        dn:
          type: string
        creationDate:
          type: string
          format: date-time
        eventTime:
          type: string
          format: date-time
        service:
          type: string
        nodeName:
          type: string
        eventType:
          type: string
        severetyLevel:
          type: string
        action:
          type: string
        decisionResult:
          type: string
        requestedResource:
          type: string
        princiaplId:
          type: string
        clientId:
          type: string
        contextInformation:
          type: object
          additionalProperties:
            type: string
        baseDn:
          type: string
        inum:
          type: string
    TelemetryEntry:
      type: object
      properties:
        dn:
          type: string
        creationDate:
          type: string
          format: date-time
        eventTime:
          type: string
          format: date-time
        service:
          type: string
        nodeName:
          type: string
        status:
          type: string
        lastPolicyLoadSize:
          type: integer
          format: int32
        policySuccessLoadCounter:
          type: integer
          format: int64
        policyFailedLoadCounter:
          type: integer
          format: int64
        lastPolicyEvaluationTimeNs:
          type: integer
          format: int32
        avgPolicyEvaluationTimeNs:
          type: integer
          format: int32
        evaluationRequestsCount:
          type: integer
          format: int64
        policyStats:
          type: object
          additionalProperties:
            type: string
        baseDn:
          type: string
        inum:
          type: string
        memoryUsage:
          type: string
    AppConfiguration5:
      type: object
      properties:
        baseDN:
          type: string
          description: >-
            Entry Base distinguished name (DN) that identifies the starting
            point of a search
        baseEndpoint:
          type: string
          description: Lock base endpoint URL
        openIdIssuer:
          type: string
          description: OpenID issuer URL
        tokenChannels:
          type: array
          description: List of token channel names
          items:
            type: string
            description: List of token channel names
        clientId:
          type: string
          description: Lock Client ID
        clientPassword:
          type: string
          description: Lock client password
        tokenUrl:
          type: string
          description: Jans URL of the OpenID Connect Provider's OAuth 2.0 Token Endpoint
        groupScopeEnabled:
          type: boolean
          description: Group scope enabled
        endpointGroups:
          type: object
          additionalProperties:
            type: array
            description: Endpoint groups
            items:
              type: string
              description: Endpoint groups
          description: Endpoint groups
        endpointDetails:
          type: object
          additionalProperties:
            type: array
            description: >-
              Jans URL of config-api audit endpoints and corresponding scope
              details
            items:
              type: string
              description: >-
                Jans URL of config-api audit endpoints and corresponding scope
                details
          description: >-
            Jans URL of config-api audit endpoints and corresponding scope
            details
        disableJdkLogger:
          type: boolean
          description: Choose whether to disable JDK loggers
        loggingLevel:
          type: string
          description: Specify the logging level of loggers
        loggingLayout:
          type: string
          description: Logging layout used for Jans Authorization Server loggers
        externalLoggerConfiguration:
          type: string
          description: The path to the external log4j2 logging configuration
        metricChannel:
          type: string
          description: Channel for metric reports
        metricReporterInterval:
          type: integer
          description: The interval for metric reporter in seconds
          format: int32
        metricReporterKeepDataDays:
          type: integer
          description: The days to keep metric reported data
          format: int32
        metricReporterEnabled:
          type: boolean
          description: Enable metric reporter
        cleanServiceInterval:
          type: integer
          description: Time interval for the Clean Service in seconds
          format: int32
        opaConfiguration:
          $ref: '#/components/schemas/OpaConfiguration'
        pdpType:
          type: string
          description: PDP type
        policiesJsonUrisAuthorizationToken:
          type: string
          description: Authorization token to access Json Uris
        policiesJsonUris:
          type: array
          description: List of Json Uris with link to Rego policies
          items:
            type: string
            description: List of Json Uris with link to Rego policies
        policiesZipUrisAuthorizationToken:
          type: string
          description: Authorization token to access Zip Uris
        policiesZipUris:
          type: array
          description: List of Zip Uris with policies
          items:
            type: string
            description: List of Zip Uris with policies
    OpaConfiguration:
      type: object
      properties:
        baseUrl:
          type: string
          description: Base OPA URL
        accessToken:
          type: string
          description: OPA access token
      description: Opa Configuration
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://{op-hostname}/.../token'
          scopes:
            'https://jans.io/oauth/jans-auth-server/config/properties.readonly': View Auth Server properties related information
            'https://jans.io/oauth/jans-auth-server/config/properties.write': Manage Auth Server properties related information
            'https://jans.io/oauth/config/attributes.readonly': View attribute related information
            'https://jans.io/oauth/config/attributes.write': Manage attribute related information
            'https://jans.io/oauth/config/attributes.delete': Delete attribute related information
            'https://jans.io/oauth/config/acrs.readonly': View ACRS related information
            'https://jans.io/oauth/config/acrs.write': Manage ACRS related information
            'https://jans.io/oauth/config/database/ldap.readonly': View LDAP database related information
            'https://jans.io/oauth/config/database/ldap.write': Manage LDAP database related information
            'https://jans.io/oauth/config/database/ldap.delete': Delete LDAP database related information
            'https://jans.io/oauth/config/scripts.readonly': View cache scripts information
            'https://jans.io/oauth/config/scripts.write': Manage scripts related information
            'https://jans.io/oauth/config/scripts.delete': Delete scripts related information
            'https://jans.io/oauth/config/cache.readonly': View cache related information
            'https://jans.io/oauth/config/cache.write': Manage cache related information
            'https://jans.io/oauth/config/smtp.readonly': View SMTP related information
            'https://jans.io/oauth/config/smtp.write': Manage SMTP related information
            'https://jans.io/oauth/config/smtp.delete': Delete SMTP related information
            'https://jans.io/oauth/config/logging.readonly': View logging related information
            'https://jans.io/oauth/config/logging.write': Manage logging related information
            'https://jans.io/oauth/config/jwks.readonly': View JWKS related information
            'https://jans.io/oauth/config/jwks.write': Manage JWKS related information
            'https://jans.io/oauth/config/jwks.delete': Delete JWKS related information
            'https://jans.io/oauth/config/openid/clients.readonly': View clients related information
            'https://jans.io/oauth/config/openid/clients.write': Manage clients related information
            'https://jans.io/oauth/config/openid/clients.delete': Delete clients related information
            'https://jans.io/oauth/config/scopes.readonly': View scope related information
            'https://jans.io/oauth/config/scopes.write': Manage scope related information
            'https://jans.io/oauth/config/scopes.delete': Delete scope related information
            'https://jans.io/oauth/config/uma/resources.readonly': View UMA Resource related information
            'https://jans.io/oauth/config/uma/resources.write': Manage UMA Resource related information
            'https://jans.io/oauth/config/uma/resources.delete': Delete UMA Resource related information
            'https://jans.io/oauth/config/stats.readonly': View server with basic statistic
            'https://jans.io/oauth/config/organization.readonly': View organization configuration information
[...]
