{{ if .Values.usrEnvs.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-user-custom-envs
  labels:
    APP_NAME: admin-ui
{{ include "admin-ui.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if or (.Values.additionalAnnotations) (.Values.customAnnotations.configMaps) (.Values.customAnnotations.secrets) }}
  annotations:
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
{{- if .Values.customAnnotations.configMaps }}
{{ toYaml .Values.customAnnotations.configMaps | indent 4 }}
{{- end }}
{{- if .Values.customAnnotations.secrets }}
{{ toYaml .Values.customAnnotations.secrets | indent 4 }}
{{- end }}
{{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.usrEnvs.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end}}