import { OPACITY } from '@/constants'

const BASELINE_WINDOW_DAYS = 7

const DEVICE_TREND_DAYS = 14

const VELOCITY_BUCKET_HOURS = 4

const TOP_IP_LIMIT = 8

const TOP_USER_LIMIT = 8

const SUSPICIOUS_IP_MIN_FAILURES = 5

const SUSPICIOUS_IP_MIN_FAILURE_RATE = 0.6

const SUSPICIOUS_IP_MIN_TARGETED_USERS = 3

// An account is "under siege" on sustained failure volume, or on a smaller run that almost
// never succeeds.
const USER_SIEGE_MIN_FAILURES = 5

const USER_SIEGE_RATE_MIN_FAILURES = 3

const USER_SIEGE_MIN_FAILURE_RATE = 0.6

const SIEGE_CHIP_LIMIT = 1

const CRITICAL_IP_FAILURE_RATIO = 0.8

const HIGH_IP_FAILURE_RATIO = 0.6

const HIGH_IP_FAILURE_MULTIPLIER = 2

const SPIKE_RATIO_THRESHOLD = 2

// Failures needed to raise an anomaly in a bucket that has no comparable history yet.
const NO_BASELINE_MIN_FAILURES = 3

const CRITICAL_IP_RATIO_THRESHOLD = 4

const DROP_OFF_ALERT_RATE = 20

const VELOCITY_ANOMALY_SIGMA = 2

const VELOCITY_ANOMALY_MIN_ATTEMPTS = 20

const THREAT_LEVELS = {
  CRITICAL: 'critical',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
} as const

const ATTACK_PATTERNS = {
  BRUTE_FORCE: 'brute_force',
  PASSWORD_SPRAYING: 'password_spraying',
  CREDENTIAL_STUFFING: 'credential_stuffing',
  DISTRIBUTED: 'distributed',
} as const

const ANOMALY_KINDS = {
  AUTH_SPIKE: 'auth_spike',
  IPS_FLAGGED: 'ips_flagged',
  DROP_OFF: 'drop_off',
} as const

const KPI_PERIODS = {
  TODAY: 'today',
  LAST_7_DAYS: 'last_7_days',
  THIS_MONTH: 'this_month',
} as const

const KPI_PERIOD_ORDER = [
  KPI_PERIODS.TODAY,
  KPI_PERIODS.LAST_7_DAYS,
  KPI_PERIODS.THIS_MONTH,
] as const

const RECENT_ANOMALY_WINDOW_HOURS = 2

const CHART_LABEL_FORMATS = {
  HOURLY: 'HH',
  DAILY: 'MMM-DD',
} as const

const SECURITY_CHART_HEIGHT = 320

const CHART_TICK_COUNT = 6

const CHART_EMPTY_INSET = {
  AXIS_WIDTH: 60,
  AXIS_HEIGHT: 38,
  TOP_MARGIN: 12,
  BAR_LEFT_MARGIN: 24,
  VELOCITY_LABEL_WIDTH: 200,
  VELOCITY_HEADER_HEIGHT: 30,
} as const

const CHART_PERCENT_TICKS = [0, 25, 50, 75, 100] as const

const CHART_PERCENT_DOMAIN: readonly [number, number] = [0, 100]

const CHART_SCAFFOLD = {
  DROP_OFF_DAYS: 7,
  BAR_ROWS: 5,
  VELOCITY_ROWS: 4,
  EMPTY_COUNT_MAX: 10,
} as const

const SECURITY_CHART_FILL_OPACITY = OPACITY.OVERLAY

const SECURITY_ENTRIES_LIMIT = 500

export {
  ANOMALY_KINDS,
  ATTACK_PATTERNS,
  BASELINE_WINDOW_DAYS,
  CHART_EMPTY_INSET,
  CHART_PERCENT_DOMAIN,
  CHART_PERCENT_TICKS,
  CHART_SCAFFOLD,
  CHART_LABEL_FORMATS,
  CHART_TICK_COUNT,
  CRITICAL_IP_FAILURE_RATIO,
  CRITICAL_IP_RATIO_THRESHOLD,
  DEVICE_TREND_DAYS,
  DROP_OFF_ALERT_RATE,
  HIGH_IP_FAILURE_MULTIPLIER,
  HIGH_IP_FAILURE_RATIO,
  KPI_PERIODS,
  KPI_PERIOD_ORDER,
  NO_BASELINE_MIN_FAILURES,
  SECURITY_CHART_FILL_OPACITY,
  SECURITY_CHART_HEIGHT,
  SECURITY_ENTRIES_LIMIT,
  RECENT_ANOMALY_WINDOW_HOURS,
  SPIKE_RATIO_THRESHOLD,
  SUSPICIOUS_IP_MIN_FAILURES,
  SUSPICIOUS_IP_MIN_FAILURE_RATE,
  SUSPICIOUS_IP_MIN_TARGETED_USERS,
  SIEGE_CHIP_LIMIT,
  THREAT_LEVELS,
  USER_SIEGE_MIN_FAILURES,
  USER_SIEGE_MIN_FAILURE_RATE,
  USER_SIEGE_RATE_MIN_FAILURES,
  TOP_IP_LIMIT,
  TOP_USER_LIMIT,
  VELOCITY_ANOMALY_MIN_ATTEMPTS,
  VELOCITY_ANOMALY_SIGMA,
  VELOCITY_BUCKET_HOURS,
}
