// Auth Actions
export const GET_OAUTH2_CONFIG = "GET_OAUTH2_CONFIG";
export const GET_OAUTH2_CONFIG_RESPONSE = "GET_OAUTH2_CONFIG_RESPONSE";

export const GET_OAUTH2_ACCESS_TOKEN = "GET_OAUTH2_ACCESS_TOKEN";
export const GET_OAUTH2_ACCESS_TOKEN_RESPONSE =
  "GET_OAUTH2_ACCESS_TOKEN_RESPONSE";

export const GET_API_ACCESS_TOKEN = "GET_API_ACCESS_TOKEN";
export const GET_API_ACCESS_TOKEN_RESPONSE = "GET_API_ACCESS_TOKEN_RESPONSE";

// scopes types
export const GET_SCOPES = "GET_SCOPES";
export const DELETE_SCOPE = "DELETE_SCOPE";
export const GET_SCOPE_BY_INUM = "GET_SCOPE_BY_INUM";

export const GET_SCOPES_RESPONSE = "GET_SCOPES_RESPONSE";
export const GET_SCOPE_BY_INUM_RESPONSE = "GET_SCOPE_BY_INUM_RESPONSE";
export const DELETE_SCOPE_RESPONSE = "DELETE_SCOPE_RESPONSE";

// Attributes types
export const GET_ATTRIBUTES = "GET_ATTRIBUTES";
export const GET_ATTRIBUTES_RESPONSE = "GET_ATTRIBUTES_RESPONSE";

export const SET_API_ERROR = "SET_API_ERROR";
export const RESET = "RESET";

