// Auth Actions
export const GET_OAUTH2_CONFIG = 'GET_OAUTH2_CONFIG'
export const GET_OAUTH2_CONFIG_RESPONSE = 'GET_OAUTH2_CONFIG_RESPONSE'
export const GET_API_ACCESS_TOKEN = 'GET_API_ACCESS_TOKEN'
export const GET_API_ACCESS_TOKEN_RESPONSE = 'GET_API_ACCESS_TOKEN_RESPONSE'
export const SET_STATE = 'SET_STATE'

export const USERINFO_REQUEST = 'USERINFO_REQUEST'
export const USERINFO_RESPONSE = 'USERINFO_RESPONSE'

// scopes types
export const GET_SCOPES = 'GET_SCOPES'
export const DELETE_SCOPE = 'DELETE_SCOPE'
export const GET_SCOPE_BY_INUM = 'GET_SCOPE_BY_INUM'

export const GET_SCOPES_RESPONSE = 'GET_SCOPES_RESPONSE'
export const GET_SCOPE_BY_INUM_RESPONSE = 'GET_SCOPE_BY_INUM_RESPONSE'
export const DELETE_SCOPE_RESPONSE = 'DELETE_SCOPE_RESPONSE'

// Attributes types
export const GET_ATTRIBUTES = 'GET_ATTRIBUTES'
export const GET_ATTRIBUTES_RESPONSE = 'GET_ATTRIBUTES_RESPONSE'

export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const ADD_ATTRIBUTE_RESPONSE = 'ADD_ATTRIBUTE_RESPONSE'

export const EDIT_ATTRIBUTE = 'EDIT_ATTRIBUTE'
export const EDIT_ATTRIBUTE_RESPONSE = 'EDIT_ATTRIBUTE_RESPONSE'

export const GET_ATTRIBUTE_BY_INUM = 'GET_ATTRIBUTE_BY_INUM'
export const GET_ATTRIBUTE_BY_INUM_RESPONSE = 'GET_ATTRIBUTE_BY_INUM_RESPONSE'

export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE'
export const DELETE_ATTRIBUTE_RESPONSE = 'DELETE_ATTRIBUTE_RESPONSE'

// Openid Client types
export const GET_OPENID_CLIENTS = 'GET_OPENID_CLIENTS'
export const GET_OPENID_CLIENTS_RESPONSE = 'GET_OPENID_CLIENTS_RESPONSE'

//Custom Script
export const GET_CUSTOM_SCRIPT = 'GET_CUSTOM_SCRIPT'
export const GET_CUSTOM_SCRIPT_RESPONSE = 'GET_CUSTOM_SCRIPT_RESPONSE'
export const ADD_CUSTOM_SCRIPT = 'ADD_CUSTOM_SCRIPT'
export const ADD_CUSTOM_SCRIPT_RESPONSE = 'ADD_CUSTOM_SCRIPT_RESPONSE'
export const EDIT_CUSTOM_SCRIPT = 'EDIT_CUSTOM_SCRIPT'
export const EDIT_CUSTOM_SCRIPT_RESPONSE = 'EDIT_CUSTOM_SCRIPT_RESPONSE'
export const GET_CUSTOM_SCRIPT_BY_INUM = 'GET_CUSTOM_SCRIPT_BY_INUM'
export const GET_CUSTOM_SCRIPT_BY_INUM_RESPONSE =
  'GET_CUSTOM_SCRIPT_BY_INUM_RESPONSE'
export const GET_CUSTOM_SCRIPT_BY_TYPE = 'GET_CUSTOM_SCRIPT_BY_TYPE'
export const GET_CUSTOM_SCRIPT_BY_TYPE_RESPONSE =
  'GET_CUSTOM_SCRIPT_BY_TYPE_RESPONSE'
export const DELETE_CUSTOM_SCRIPT = 'DELETE_CUSTOM_SCRIPT'
export const DELETE_CUSTOM_SCRIPT_RESPONSE = 'DELETE_CUSTOM_SCRIPT_RESPONSE'

// Smtp
export const GET_SMTP = 'GET_SMTP'
export const SET_SMTP = 'SET_SMTP'
export const PUT_SMTP = 'PUT_SMTP'
export const TEST_SMTP = 'TEST_SMTP'


export const SET_API_ERROR = 'SET_API_ERROR'
export const RESET = 'RESET'
export const SET_ITEM = 'SET_ITEM'
