/*
 * cred-manager is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2018, Gluu
 */
package org.gluu.casa.core.ldap;

import com.unboundid.ldap.sdk.ReadOnlyEntry;
import com.unboundid.ldap.sdk.persist.FilterUsage;
import com.unboundid.ldap.sdk.persist.LDAPEntryField;
import com.unboundid.ldap.sdk.persist.LDAPField;
import com.unboundid.ldap.sdk.persist.LDAPObject;

import java.util.Date;

/**
 * This class provides an implementation of an object that can be used to
 * represent oxDeviceRegistration objects in the directory.
 * It was generated by the generate-source-from-schema tool provided with the
 * UnboundID LDAP SDK for Java.  It may be customized as desired to better suit
 * your needs.
 */
@LDAPObject(structuralClass="oxDeviceRegistration",
        superiorClass="top")
public class oxDeviceRegistration {

    // The field to use to hold a read-only copy of the associated entry.
    @LDAPEntryField()
    private ReadOnlyEntry ldapEntry;

    // The field used for RDN attribute oxId.
    @LDAPField(inRDN=true,
            filterUsage=FilterUsage.ALWAYS_ALLOWED,
            requiredForEncode=true)
    private String[] oxId;

    // The field used for RDN attribute oxApplication.
    @LDAPField(filterUsage=FilterUsage.ALWAYS_ALLOWED)
    private String[] oxApplication;

    // The field used for optional attribute oxCounter.
    @LDAPField
    private Long[] oxCounter;

    // The field used for optional attribute displayName.
    @LDAPField(filterUsage = FilterUsage.ALWAYS_ALLOWED)
    private String displayName;

    // The field used for optional attribute creationDate.
    @LDAPField
    private Date[] creationDate;

    // The field used for optional attribute creationDate.
    @LDAPField
    private Date[] oxLastAccessTime;

    // The field used for optional attribute oxStatus.
    @LDAPField
    private String[] oxStatus;

    // The field used for optional attribute oxDeviceData.
    @LDAPField
    private String[] oxDeviceData;

    public String getOxId() {

        if ((oxId == null) ||
                (oxId.length == 0))
        {
            return null;
        }
        else
        {
            return oxId[0];
        }
    }

    public Date getCreationDate() {

        if ((creationDate == null) ||
                (creationDate.length == 0))
        {
            return null;
        }
        else
        {
            return creationDate[0];
        }
    }

    public Date getLastAccessTime() {

        if ((oxLastAccessTime == null) ||
                (oxLastAccessTime.length == 0))
        {
            return null;
        }
        else
        {
            return oxLastAccessTime[0];
        }
    }

    public Long getOxCounter() {

        if ((oxCounter == null) ||
                (oxCounter.length == 0))
        {
            return null;
        }
        else
        {
            return oxCounter[0];
        }

    }

    public String getOxApplication() {
        if ((oxApplication == null) ||
                (oxApplication.length == 0))
        {
            return null;
        }
        else
        {
            return oxApplication[0];
        }

    }

    public String getOxStatus() {

        if ((oxStatus == null) ||
                (oxStatus.length == 0))
        {
            return null;
        }
        else
        {
            return oxStatus[0];
        }
    }

    public String getDeviceData() {

        if ((oxDeviceData == null) ||
                (oxDeviceData.length == 0))
        {
            return null;
        }
        else
        {
            return oxDeviceData[0];
        }
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public void setOxApplication(String ...oxApplication) {
        this.oxApplication = oxApplication;
    }

    public void setOxStatus(String ...oxStatus) {
        this.oxStatus = oxStatus;
    }

    public void setOxId(String ...oxId) {
        this.oxId = oxId;
    }

}
