/*
 * cred-manager is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2018, Gluu
 */
package org.gluu.casa.core.ldap;

import com.unboundid.ldap.sdk.persist.*;
import org.gluu.casa.misc.Utils;

import java.util.List;

/**
 * This class provides an implementation of an object that can be used to
 * represent gluuPerson objects in the directory.
 * It was generated by the generate-source-from-schema tool provided with the
 * UnboundID LDAP SDK for Java.  It may be customized as desired to better suit
 * your needs.
 */
@LDAPObject(structuralClass="gluuPerson",
        superiorClass="top")
public class PersonOTP extends BaseLdapPerson {

    // The field used for optional attribute oxMobileDevices.
    @LDAPField
    private String[] oxExternalUid;

    // The field used for optional attribute oxOTPDevices.
    @LDAPField
    private String[] oxOTPDevices;

    /**
     * Sets the values for the field associated with the
     * oxExternalUid attribute.
     *
     * @param  v  The values for the field associated with the
     *            oxExternalUid attribute.
     */
    public void setExternalUid(final String... v)
    {
        this.oxExternalUid = v;
    }


    public List<String> getExternalUids() {
        return Utils.listfromArray(oxExternalUid);
    }


    /**
     * Retrieves the first value for the field associated with the
     * oxOTPDevices attribute, if present.
     *
     * @return  The first value for the field associated with the
     *          oxOTPDevices attribute, or
     *          {@code null} if that attribute was not present in the entry or
     *          does not have any values.
     */
    public String getOTPDevices()
    {
        if ((oxOTPDevices == null) ||
                (oxOTPDevices.length == 0))
        {
            return null;
        }
        else
        {
            return oxOTPDevices[0];
        }
    }

    /**
     * Sets the values for the field associated with the
     * oxOTPDevices attribute.
     *
     * @param  value  The values for the field associated with the
     *            oxOTPDevices attribute.
     */
    public void setOTPDevices(final String value)
    {
        this.oxOTPDevices = new String[]{ value };
    }

}
