package org.gluu.casa.core.ldap;

import com.unboundid.ldap.sdk.ReadOnlyEntry;
import com.unboundid.ldap.sdk.persist.FilterUsage;
import com.unboundid.ldap.sdk.persist.LDAPEntryField;
import com.unboundid.ldap.sdk.persist.LDAPField;
import com.unboundid.ldap.sdk.persist.LDAPObject;
import org.gluu.casa.misc.Utils;

import java.util.List;

/**
 * This class provides an implementation of an object that can be used to
 * represent oxCustomScript objects in the directory.
 * It was generated by the generate-source-from-schema tool provided with the
 * UnboundID LDAP SDK for Java.  It may be customized as desired to better suit
 * your needs.
 */
@Deprecated
@LDAPObject(structuralClass="oxCustomScript",
        superiorClass="top")
public class oxCustomScript
{

    // The field to use to hold a read-only copy of the associated entry.
    @LDAPEntryField()
    private ReadOnlyEntry ldapEntry;

    // The field used for RDN attribute inum.
    @LDAPField(inRDN=true,
            filterUsage=FilterUsage.ALWAYS_ALLOWED,
            requiredForEncode=true)
    private String[] inum;

    // The field used for optional attribute displayName.
    @LDAPField(filterUsage=FilterUsage.ALWAYS_ALLOWED)
    private String displayName;

    // The field used for optional attribute gluuStatus.
    @LDAPField
    private String[] gluuStatus;

    // The field used for optional attribute oxConfigurationProperty.
    @LDAPField
    private String[] oxConfigurationProperty;

    // The field used for optional attribute oxLevel.
    @LDAPField
    private String[] oxLevel;

    // The field used for optional attribute oxModuleProperty.
    @LDAPField
    private String[] oxModuleProperty;

    // The field used for optional attribute oxRevision.
    @LDAPField
    private String[] oxRevision;

    // The field used for optional attribute oxScript.
    @LDAPField
    private String[] oxScript;

    /**
     * Retrieves the value for the field associated with the
     * displayName attribute, if present.
     *
     * @return  The value for the field associated with the
     *          displayName attribute, or
     *          {@code null} if the field does not have a value.
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Retrieves the values for the field associated with the
     * oxConfigurationProperty attribute, if present.
     * <p>This values hold json content in Gluu Server. For easier-to-consume data, you can use method
     * {@link Utils#scriptConfigPropertiesAsMap(oxCustomScript)}.</p>
     * @return A list of String objects (empty if oxConfigurationProperty not present)
     */
    public List<String> getConfigurationProperties() {
        return Utils.listfromArray(oxConfigurationProperty);
    }

    /**
     * Retrieves the values for the field associated with the
     * oxModuleProperty attribute, if present.
     * @return A list of String objects (empty if oxModuleProperty attribute not present).
     */
    public List<String> getModuleProperties() {
        return Utils.listfromArray(oxModuleProperty);
    }

    /**
     * Retrieves the first value for the field associated with the
     * oxScript attribute, if present.
     *
     * @return  The first value for the field associated with the
     *          oxScript attribute, or
     *          {@code null} if that attribute was not present in the entry or
     *          does not have any values.
     */
    public String getScript()
    {
        if ((oxScript == null) ||
                (oxScript.length == 0))
        {
            return null;
        }
        else
        {
            return oxScript[0];
        }
    }

    /**
     * Retrieves the first value for the field associated with the
     * oxRevision attribute, if present.
     *
     * @return  The first value for the field associated with the
     *          oxRevision attribute, or
     *          {@code null} if that attribute was not present in the entry or
     *          does not have any values.
     */
    public String getRevision()
    {
        if ((oxRevision == null) ||
                (oxRevision.length == 0))
        {
            return null;
        }
        else
        {
            return oxRevision[0];
        }
    }

    /**
     * Whether the custom script represented by this object is enabled or not
     * @return A boolean value
     */
    public boolean isEnabled() {
        return Utils.isNotEmpty(gluuStatus) && Boolean.parseBoolean(gluuStatus[0]);
    }

    /**
     * Sets the value for the field associated with the
     * displayName attribute.
     *
     * @param displayName  The value for the field associated with the
     *            displayName attribute.
     */
    public void setDisplayName(String displayName)
    {
        this.displayName = displayName;
    }

    /**
     * Sets the value for the field associated with the
     * oxRevision attribute.
     *
     * @param v The value for the field associated with the
     *            oxRevision attribute.
     */
    public void setRevision(final String ...v)
    {
        this.oxRevision = v;
    }

}
