import type { Scope } from './types'

export const scopes: Partial<Scope>[] = [
  {
    dn: 'inum=F0C4,ou=scopes,o=jans',
    inum: 'F0C4',
    id: 'openid',
    description: 'Authenticate using OpenID Connect.',
    scopeType: 'openid',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=43F1,ou=scopes,o=jans',
    inum: '43F1',
    id: 'profile',
    description: 'View your basic profile info.',
    scopeType: 'openid',
    claims: [
      'inum=2B29,ou=attributes,o=jans',
      'inum=0C85,ou=attributes,o=jans',
      'inum=B4B0,ou=attributes,o=jans',
      'inum=A0E8,ou=attributes,o=jans',
      'inum=5EC6,ou=attributes,o=jans',
      'inum=B52A,ou=attributes,o=jans',
      'inum=64A0,ou=attributes,o=jans',
      'inum=3B47,ou=attributes,o=jans',
      'inum=3692,ou=attributes,o=jans',
      'inum=98FC,ou=attributes,o=jans',
      'inum=A901,ou=attributes,o=jans',
      'inum=36D9,ou=attributes,o=jans',
      'inum=BE64,ou=attributes,o=jans',
      'inum=6493,ou=attributes,o=jans',
      'inum=4ad95062-91a6-4218-832e-3f3f2c60c6cf,ou=attributes,o=jans',
    ],
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-2AE5,ou=scopes,o=jans',
    inum: 'CACA-2AE5',
    displayName: 'https://jans.io/oauth/config/database/ldap.readonly',
    id: 'https://jans.io/oauth/config/database/ldap.readonly',
    description: 'View LDAP database related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=8CAD-B06D,ou=scopes,o=jans',
    inum: '8CAD-B06D',
    displayName: 'SCIM Access',
    id: 'https://gasmyr.gluu.org/jans-auth/restv1/uma/scopes/scim_access',
    scopeType: 'uma',
    umaAuthorizationPolicies: ['inum=2DAF-F9A5,ou=scripts,o=jans'],
    attributes: { showInConfigurationEndpoint: true },
    umaType: true,
  },
  {
    dn: 'inum=3cd112b7-ae35-4a64-bef6-fbfab693f3e2,ou=scopes,o=jans',
    inum: '3cd112b7-ae35-4a64-bef6-fbfab693f3e2',
    displayName: 'https://jans.io/oauth/config/scripts.delete',
    id: 'https://jans.io/oauth/config/scripts.delete',
    scopeType: 'oauth',
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=C4F5,ou=scopes,o=jans',
    inum: 'C4F5',
    id: 'permission',
    description: 'View your user permission and roles.',
    scopeType: 'dynamic',
    defaultScope: true,
    dynamicScopeScripts: ['inum=CB5B-3211,ou=scripts,o=jans'],
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-E87C,ou=scopes,o=jans',
    inum: 'CACA-E87C',
    displayName: 'https://jans.io/oauth/config/acrs.write',
    id: 'https://jans.io/oauth/config/acrs.write',
    description: 'Manage ACRS related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-0532,ou=scopes,o=jans',
    inum: 'CACA-0532',
    displayName: 'https://jans.io/oauth/config/database/couchbase.write',
    id: 'https://jans.io/oauth/config/database/couchbase.write',
    description: 'Manage Couchbase database related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-0A49,ou=scopes,o=jans',
    inum: 'CACA-0A49',
    displayName: 'https://jans.io/oauth/config/database/ldap.write',
    id: 'https://jans.io/oauth/config/database/ldap.write',
    description: 'Manage LDAP database related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=6D99,ou=scopes,o=jans',
    inum: '6D99',
    displayName: 'UMA Protection',
    id: 'uma_protection',
    description: 'Obtain UMA PAT.',
    scopeType: 'openid',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-2A9B,ou=scopes,o=jans',
    inum: 'CACA-2A9B',
    displayName: 'https://jans.io/oauth/config/fido2.write',
    id: 'https://jans.io/oauth/config/fido2.write',
    description: 'Manage FIDO2 related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-5EAD,ou=scopes,o=jans',
    inum: 'CACA-5EAD',
    displayName: 'https://jans.io/oauth/config/database/couchbase.readonly',
    id: 'https://jans.io/oauth/config/database/couchbase.readonly',
    description: 'View Couchbase database information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-1213,ou=scopes,o=jans',
    inum: 'CACA-1213',
    displayName: 'https://jans.io/oauth/config/cache.write',
    id: 'https://jans.io/oauth/config/cache.write',
    description: 'Manage cache related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=D491,ou=scopes,o=jans',
    inum: 'D491',
    id: 'phone',
    description: 'View your phone number.',
    scopeType: 'openid',
    claims: ['inum=B17A,ou=attributes,o=jans', 'inum=0C18,ou=attributes,o=jans'],
    defaultScope: false,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=C17A,ou=scopes,o=jans',
    inum: 'C17A',
    id: 'address',
    description: 'View your address.',
    scopeType: 'openid',
    claims: [
      'inum=27DB,ou=attributes,o=jans',
      'inum=2A3D,ou=attributes,o=jans',
      'inum=6609,ou=attributes,o=jans',
      'inum=6EEB,ou=attributes,o=jans',
      'inum=BCE8,ou=attributes,o=jans',
      'inum=D90B,ou=attributes,o=jans',
      'inum=E6B8,ou=attributes,o=jans',
      'inum=E999,ou=attributes,o=jans',
    ],
    defaultScope: false,
    groupClaims: true,
    attributes: { showInConfigurationEndpoint: true },
    oxAuthGroupClaims: true,
    umaType: false,
  },
  {
    dn: 'inum=CACA-B7AE,ou=scopes,o=jans',
    inum: 'CACA-B7AE',
    displayName: 'https://jans.io/oauth/config/openid/sectoridentifiers.write',
    id: 'https://jans.io/oauth/config/openid/sectoridentifiers.write',
    description: 'Manage sector related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-593F,ou=scopes,o=jans',
    inum: 'CACA-593F',
    displayName: 'https://jans.io/oauth/config/smtp.readonly',
    id: 'https://jans.io/oauth/config/smtp.readonly',
    description: 'View SMTP related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-8C92,ou=scopes,o=jans',
    inum: 'CACA-8C92',
    displayName: 'https://jans.io/oauth/config/attributes.write',
    id: 'https://jans.io/oauth/config/attributes.write',
    description: 'Manage attribute related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-6A23,ou=scopes,o=jans',
    inum: 'CACA-6A23',
    displayName: 'https://jans.io/oauth/config/openid/clients.write',
    id: 'https://jans.io/oauth/config/openid/clients.write',
    description: 'Manage clients related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-F2E8,ou=scopes,o=jans',
    inum: 'CACA-F2E8',
    displayName: 'https://jans.io/oauth/config/jwks.write',
    id: 'https://jans.io/oauth/config/jwks.write',
    description: 'Manage JWKS related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=8A01,ou=scopes,o=jans',
    inum: '8A01',
    id: 'mobile_phone',
    description: 'View your mobile phone number.',
    scopeType: 'openid',
    claims: ['inum=6DA6,ou=attributes,o=jans'],
    defaultScope: false,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=7D90,ou=scopes,o=jans',
    inum: '7D90',
    displayName: 'revoke_session',
    id: 'revoke_session',
    description: 'revoke_session scope which is required to be able call /revoke_session endpoint',
    scopeType: 'openid',
    defaultScope: false,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-0690,ou=scopes,o=jans',
    inum: 'CACA-0690',
    displayName: 'https://jans.io/oauth/config/openid/sectoridentifiers.readonly',
    id: 'https://jans.io/oauth/config/openid/sectoridentifiers.readonly',
    description: 'View sector related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=10B2,ou=scopes,o=jans',
    inum: '10B2',
    id: 'user_name',
    description: 'View your local username in the Janssen Server.',
    scopeType: 'openid',
    claims: ['inum=42E0,ou=attributes,o=jans'],
    defaultScope: false,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=764C,ou=scopes,o=jans',
    inum: '764C',
    id: 'email',
    description: 'View your email address.',
    scopeType: 'openid',
    claims: ['inum=8F88,ou=attributes,o=jans', 'inum=CAE3,ou=attributes,o=jans'],
    defaultScope: false,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=84ce3ed1-5c0d-4bd5-98a0-eb7c74dd8789,ou=scopes,o=jans',
    inum: '84ce3ed1-5c0d-4bd5-98a0-eb7c74dd8789',
    displayName: 'https://jans.io/oauth/config/smtp.delete',
    id: 'https://jans.io/oauth/config/smtp.delete',
    scopeType: 'oauth',
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=341A,ou=scopes,o=jans',
    inum: '341A',
    id: 'clientinfo',
    description: 'View the client info.',
    scopeType: 'openid',
    claims: ['inum=2B29,ou=attributes,o=jans', 'inum=29DA,ou=attributes,o=jans'],
    defaultScope: false,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-B72D,ou=scopes,o=jans',
    inum: 'CACA-B72D',
    displayName: 'https://jans.io/oauth/config/scripts.readonly',
    id: 'https://jans.io/oauth/config/scripts.readonly',
    description: 'View cache scripts information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=b00530db-e5d1-4617-8b8f-e85c0d5d7c2f,ou=scopes,o=jans',
    inum: 'b00530db-e5d1-4617-8b8f-e85c0d5d7c2f',
    displayName: 'https://jans.io/oauth/config/attributes.delete',
    id: 'https://jans.io/oauth/config/attributes.delete',
    scopeType: 'oauth',
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-34F1,ou=scopes,o=jans',
    inum: 'CACA-34F1',
    displayName: 'https://jans.io/oauth/jans-auth-server/config/properties.readonly',
    id: 'https://jans.io/oauth/jans-auth-server/config/properties.readonly',
    description: 'View Auth Server properties related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=6D90,ou=scopes,o=jans',
    inum: '6D90',
    displayName: 'oxd',
    id: 'oxd',
    description: 'oxd scope which is required to call oxd API',
    scopeType: 'openid',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-9AAD,ou=scopes,o=jans',
    inum: 'CACA-9AAD',
    displayName: 'https://jans.io/oauth/config/cache.readonly',
    id: 'https://jans.io/oauth/config/cache.readonly',
    description: 'View cache related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-A48D,ou=scopes,o=jans',
    inum: 'CACA-A48D',
    displayName: 'https://jans.io/oauth/config/fido2.readonly',
    id: 'https://jans.io/oauth/config/fido2.readonly',
    description: 'View FIDO2 related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-687F,ou=scopes,o=jans',
    inum: 'CACA-687F',
    displayName: 'https://jans.io/oauth/config/smtp.write',
    id: 'https://jans.io/oauth/config/smtp.write',
    description: 'Manage SMTP related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-6FF5,ou=scopes,o=jans',
    inum: 'CACA-6FF5',
    displayName: 'https://jans.io/oauth/config/jwks.readonly',
    id: 'https://jans.io/oauth/config/jwks.readonly',
    description: 'View JWKS related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=c35b76c0-5bad-423b-908a-fca4fabd3fde,ou=scopes,o=jans',
    inum: 'c35b76c0-5bad-423b-908a-fca4fabd3fde',
    displayName: 'https://jans.io/oauth/config/openid/clients.delete',
    id: 'https://jans.io/oauth/config/openid/clients.delete',
    scopeType: 'oauth',
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-3B62,ou=scopes,o=jans',
    inum: 'CACA-3B62',
    displayName: 'https://jans.io/oauth/config/attributes.readonly',
    id: 'https://jans.io/oauth/config/attributes.readonly',
    description: 'View attribute related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-6819,ou=scopes,o=jans',
    inum: 'CACA-6819',
    displayName: 'https://jans.io/oauth/config/scopes.write',
    id: 'https://jans.io/oauth/config/scopes.write',
    description: 'Manage scope related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-B0EF,ou=scopes,o=jans',
    inum: 'CACA-B0EF',
    displayName: 'https://jans.io/oauth/config/openid/clients.readonly',
    id: 'https://jans.io/oauth/config/openid/clients.readonly',
    description: 'View clients related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-8CCB,ou=scopes,o=jans',
    inum: 'CACA-8CCB',
    displayName: 'https://jans.io/oauth/config/uma/resources.write',
    id: 'https://jans.io/oauth/config/uma/resources.write',
    description: 'Manage UMA Resource related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=f4014b02-e6d6-4839-92a2-5f0e6d7819a9,ou=scopes,o=jans',
    inum: 'f4014b02-e6d6-4839-92a2-5f0e6d7819a9',
    displayName: 'https://jans.io/oauth/config/database/couchbase.delete',
    id: 'https://jans.io/oauth/config/database/couchbase.delete',
    scopeType: 'oauth',
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-C8AF,ou=scopes,o=jans',
    inum: 'CACA-C8AF',
    displayName: 'https://jans.io/oauth/config/acrs.readonly',
    id: 'https://jans.io/oauth/config/acrs.readonly',
    description: 'View ACRS related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-B452,ou=scopes,o=jans',
    inum: 'CACA-B452',
    displayName: 'https://jans.io/oauth/config/scripts.write',
    id: 'https://jans.io/oauth/config/scripts.write',
    description: 'Manage scripts related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-2F55,ou=scopes,o=jans',
    inum: 'CACA-2F55',
    displayName: 'https://jans.io/oauth/config/logging.readonly',
    id: 'https://jans.io/oauth/config/logging.readonly',
    description: 'View logging related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-F7D6,ou=scopes,o=jans',
    inum: 'CACA-F7D6',
    displayName: 'https://jans.io/oauth/config/logging.write',
    id: 'https://jans.io/oauth/config/logging.write',
    description: 'Manage logging related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-4941,ou=scopes,o=jans',
    inum: 'CACA-4941',
    displayName: 'https://jans.io/oauth/config/uma/resources.readonly',
    id: 'https://jans.io/oauth/config/uma/resources.readonly',
    description: 'View UMA Resource related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=0631e55e-0a6d-40d0-8043-168d07495c75,ou=scopes,o=jans',
    inum: '0631e55e-0a6d-40d0-8043-168d07495c75',
    displayName: 'jansAdminUIRole',
    id: 'jansAdminUIRole',
    description: 'Jans Admin UI Role',
    scopeType: 'openid',
    claims: ['inum=4ad95062-91a6-4218-832e-3f3f2c60c6cf,ou=attributes,o=jans'],
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=C4F6,ou=scopes,o=jans',
    inum: 'C4F6',
    id: 'offline_access',
    description: 'This scope value requests that an OAuth 2.0 Refresh Token be issued.',
    scopeType: 'openid',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-889F,ou=scopes,o=jans',
    inum: 'CACA-889F',
    displayName: 'https://jans.io/oauth/jans-auth-server/config/properties.write',
    id: 'https://jans.io/oauth/jans-auth-server/config/properties.write',
    description: 'Manage Auth Server properties related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
  {
    dn: 'inum=CACA-A0DF,ou=scopes,o=jans',
    inum: 'CACA-A0DF',
    displayName: 'https://jans.io/oauth/config/scopes.readonly',
    id: 'https://jans.io/oauth/config/scopes.readonly',
    description: 'View scope related information',
    scopeType: 'oauth',
    defaultScope: true,
    attributes: { showInConfigurationEndpoint: true },
    umaType: false,
  },
]

export default scopes
