export const items = [
    {name: "PERSON_AUTHENTICATION", value: "person_authentication"},
    {name: "INTROSPECTION", value: "introspection"},
    {name: "RESOURCE_OWNER_PASSWORD_CREDENTIALS", value: "resource_owner_password_credentials"},
    {name: "APPLICATION_SESSION", value: "application_session"},
    {name: "CACHE_REFRESH", value: "cache_refresh"},
    {name: "CLIENT_REGISTRATION", value: "client_registration"},
    {name: "ID_GENERATOR", value: "id_generator"},
    {name: "UMA_RPT_POLICY", value: "uma_rpt_policy"},
    {name: "UMA_RPT_CLAIMS", value: "uma_rpt_claims"},
    {name: "UMA_CLAIMS_GATHERING", value: "uma_claims_gathering"},
    {name: "CONSENT_GATHERING", value: "consent_gathering"},
    {name: "DYNAMIC_SCOPE", value: "dynamic_scope"},
    {name: "SPONTANEOUS_SCOPE", value: "spontaneous_scope"},
    {name: "END_SESSION", value: "end_session"},
    {name: "POST_AUTHN", value: "post_authn"},
    {name: "SCIM", value: "scim"},
    {name: "CIBA_END_USER_NOTIFICATION", value: "ciba_end_user_notification"},
    {name: "REVOKE_TOKEN", value: "revoke_token"},
    {name: "PERSISTENCE_EXTENSION", value: "persistence_extension"},
    {name: "IDP", value: "idp"},
    {name: "DISCOVERY", value: "discovery"},
    {name: "UPDATE_TOKEN", value: "update_token"},
    {name: "CONFIG_API_AUTH", value: "config_api_auth"},
    {name: "MODIFY_SSA_RESPONSE", value: "modify_ssa_response"},
];

export default items