export const items = [
    {name: "PERSON_AUTHENTICATION"},
    {name: "INTROSPECTION"},
    {name: "RESOURCE_OWNER_PASSWORD_CREDENTIALS"},
    {name: "APPLICATION_SESSION"},
    {name: "CACHE_REFRESH"},
    {name: "UPDATE_USER"},
    {name: "USER_REGISTRATION"},
    {name: "CLIENT_REGISTRATION"},
    {name: "ID_GENERATOR"},
    {name: "UMA_RPT_POLICY"},
    {name: "UMA_RPT_CLAIMS"},
    {name: "UMA_CLAIMS_GATHERING"},
    {name: "CONSENT_GATHERING"},
    {name: "DYNAMIC_SCOPE"},
    {name: "SPONTANEOUS_SCOPE"},
    {name: "END_SESSION"},
    {name: "POST_AUTHN"},
    {name: "SCIM"},
    {name: "CIBA_END_USER_NOTIFICATION"},
    {name: "REVOKE_TOKEN"},
    {name: "PERSISTENCE_EXTENSION"},
    {name: "IDP"},
    {name: "UPDATE_TOKEN"},
];

export default items