export const RESET = 'RESET'

// User Management

export const GET_USERS = 'GET_USERS'
export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE'
export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const CREATE_NEW_USER_RESPONSE = 'CREATE_NEW_USER_RESPONSE'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_RESPONSE = 'UPDATE_USER_RESPONSE'
export const SELECTED_USER_DATA = 'SELECTED_USER_DATA'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_RESPONSE = 'DELETE_USER_RESPONSE'
export const CHANGE_USERS_PASSWORD = 'CHANGE_USERS_PASSWORD'
export const CHANGE_USERS_PASSWORD_RESPONSE = 'CHANGE_USERS_PASSWORD_RESPONSE'
