export const RESET = 'RESET'

// User Management

export const GET_USERS = 'GET_USERS'
export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE'
export const USERS_LOADING = 'USERS_LOADING'
export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const SELECTED_USER_DATA = 'SELECTED_USER_DATA'
export const REDIRECT_TO_USERS_LIST = 'REDIRECT_TO_USERS_LIST'
export const DELETE_USER = 'DELETE_USER'
export const CHANGE_USERS_PASSWORD = 'CHANGE_USERS_PASSWORD'
