export const RESET = 'RESET'

// User Management

export const UM_GET_USERS = 'UM_GET_USERS'
export const UM_UPDATE_USERS_RESPONSE = 'UM_UPDATE_USERS_RESPONSE'
export const UM_UPDATE_LOADING = 'UM_UPDATE_LOADING'
export const UM_CREATE_NEW_USER = 'UM_CREATE_NEW_USER'
export const UM_UPDATE_EXISTING_USER = 'UM_UPDATE_EXISTING_USER'
export const UM_SELECTED_USER_DATA = 'UM_SELECTED_USER_DATA'
export const UM_REDIRECT_TO_LIST = 'UM_REDIRECT_TO_LIST'
export const UM_DELETE_EXISTING_USER = 'UM_DELETE_EXISTING_USER'
export const UM_UPDATE_PASSWORD = 'UM_UPDATE_PASSWORD'
