import { makeStyles } from 'tss-react/mui'
import customColors, { hexToRgb } from '@/customColors'
import { BORDER_RADIUS } from '@/constants/ui'
import { fontFamily, fontSizes, fontWeights } from '@/styles/fonts'
import { BOTTOM_NAV } from './constants'
import { SHEET } from './sheetConstants'
import type { MobileNavSheetThemeColors } from './types'

const useStyles = makeStyles<{ colors: MobileNavSheetThemeColors }>()((_theme, { colors }) => ({
  scrim: {
    position: 'fixed',
    inset: 0,
    zIndex: SHEET.Z_SCRIM,
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    backgroundColor: `rgba(${hexToRgb(customColors.black)}, ${SHEET.SCRIM_OPACITY})`,
    opacity: 0,
    transition: `opacity ${SHEET.TRANSITION_MS}ms ease`,
  },
  scrimOpen: {
    opacity: 1,
  },
  sheet: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: SHEET.Z_SHEET,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: SHEET.MAX_HEIGHT,
    backgroundColor: colors.background,
    borderRadius: `${BORDER_RADIUS.MOBILE_SHEET}px ${BORDER_RADIUS.MOBILE_SHEET}px 0 0`,
    boxShadow: `0px ${SHEET.SHADOW_OFFSET_Y}px ${SHEET.SHADOW_BLUR}px 0px rgba(${hexToRgb(customColors.black)}, ${SHEET.SHADOW_OPACITY})`,
    paddingBottom: `calc(${BOTTOM_NAV.HEIGHT}px + env(safe-area-inset-bottom))`,
    transform: 'translateY(100%)',
    transition: `transform ${SHEET.TRANSITION_MS}ms cubic-bezier(0.32, 0.72, 0, 1)`,
    willChange: 'transform',
  },
  sheetOpen: {
    transform: 'translateY(0)',
  },
  header: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: SHEET.HEADER_GAP,
    padding: SHEET.HEADER_PADDING,
    borderBottom: `1px solid ${colors.border}`,
  },
  headerIcon: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': SHEET.HEADER_ICON_SIZE,
    'height': SHEET.HEADER_ICON_SIZE,
    'color': colors.text,
    '& svg': {
      width: SHEET.HEADER_ICON_SIZE,
      height: SHEET.HEADER_ICON_SIZE,
    },
  },
  headerTitle: {
    flex: 1,
    fontFamily,
    fontSize: fontSizes.md,
    fontWeight: fontWeights.medium,
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: '0.32px',
    color: colors.text,
  },
  headerTitleMuted: {
    color: colors.title,
  },
  close: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': SHEET.CLOSE_SIZE,
    'height': SHEET.CLOSE_SIZE,
    'padding': 0,
    'border': 'none',
    'background': 'transparent',
    'cursor': 'pointer',
    'color': colors.text,
    '& svg': {
      width: SHEET.CLOSE_SIZE,
      height: SHEET.CLOSE_SIZE,
    },
  },
  back: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': SHEET.BACK_SIZE,
    'height': SHEET.BACK_SIZE,
    'flexShrink': 0,
    'padding': 0,
    'border': 'none',
    'borderRadius': '50%',
    'cursor': 'pointer',
    'backgroundColor': colors.chip,
    'color': colors.text,
    '& svg': {
      width: SHEET.BACK_ICON_SIZE,
      height: SHEET.BACK_ICON_SIZE,
    },
  },
  body: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: `repeat(${SHEET.GRID_COLUMNS}, 1fr)`,
    rowGap: SHEET.GRID_ROW_GAP,
    padding: SHEET.GRID_PADDING,
  },
  tile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: SHEET.TILE_GAP,
    padding: 0,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    minWidth: 0,
    color: colors.text,
  },
  tileChip: {
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': SHEET.TILE_CHIP_WIDTH,
    'height': SHEET.TILE_CHIP_HEIGHT,
    'borderRadius': SHEET.TILE_CHIP_RADIUS,
    'backgroundColor': colors.chip,
    'color': colors.text,
    '& svg': {
      width: SHEET.TILE_ICON_SIZE,
      height: SHEET.TILE_ICON_SIZE,
    },
  },
  tileChipActive: {
    backgroundColor: colors.active,
    color: colors.white,
  },
  tileLabel: {
    fontFamily,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.medium,
    letterSpacing: '0.24px',
    color: colors.text,
    textAlign: 'center',
    lineHeight: 1.2,
  },
  tileLabelActive: {
    color: colors.active,
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: SHEET.LIST_ROW_GAP,
    padding: `${SHEET.LIST_PADDING_Y}px ${SHEET.LIST_PADDING_X}px`,
  },
  listItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SHEET.LIST_ITEM_GAP,
    padding: 0,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
    fontFamily,
    fontSize: fontSizes.base,
    fontWeight: fontWeights.medium,
    letterSpacing: '0.28px',
    color: colors.listText,
  },
  listItemActive: {
    fontWeight: fontWeights.semiBold,
    color: colors.listText,
  },
  listGroup: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 0,
    width: '100%',
  },
  chevron: {
    flexShrink: 0,
    color: colors.listText,
    transition: 'transform 0.15s ease',
  },
  subListWrap: {
    display: 'grid',
    gridTemplateRows: '0fr',
    width: '100%',
    transition: `grid-template-rows ${SHEET.SUBLIST_TRANSITION_MS}ms ease`,
  },
  subListWrapOpen: {
    gridTemplateRows: '1fr',
  },
  subListInner: {
    overflow: 'hidden',
    minHeight: 0,
    width: '100%',
  },
  subList: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: SHEET.LIST_ROW_GAP,
    width: '100%',
    paddingLeft: SHEET.SUBLIST_INDENT,
    paddingTop: SHEET.LIST_ROW_GAP,
  },
  subListItem: {
    padding: 0,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
    fontFamily,
    fontSize: fontSizes.base,
    fontWeight: fontWeights.medium,
    letterSpacing: '0.28px',
    color: colors.listText,
  },
}))

export { useStyles }
