/**
 * jans-config-api
 * jans-config-api - Authorization services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xxx@gluu.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JansConfigApi);
  }
}(this, function(expect, JansConfigApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JansConfigApi.ConfigurationSMTPApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigurationSMTPApi', function() {
    describe('deleteConfigSmtp', function() {
      it('should call deleteConfigSmtp successfully', function(done) {
        //uncomment below and update the code to test deleteConfigSmtp
        //instance.deleteConfigSmtp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getConfigSmtp', function() {
      it('should call getConfigSmtp successfully', function(done) {
        //uncomment below and update the code to test getConfigSmtp
        //instance.getConfigSmtp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postConfigSmtp', function() {
      it('should call postConfigSmtp successfully', function(done) {
        //uncomment below and update the code to test postConfigSmtp
        //instance.postConfigSmtp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putConfigSmtp', function() {
      it('should call putConfigSmtp successfully', function(done) {
        //uncomment below and update the code to test putConfigSmtp
        //instance.putConfigSmtp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('testConfigSmtp', function() {
      it('should call testConfigSmtp successfully', function(done) {
        //uncomment below and update the code to test testConfigSmtp
        //instance.testConfigSmtp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
