geo $literal_dollar {
    default "$";
}
server {
    listen 8080 default_server;
    # listen [::]:8080 default_server ipv6only=on;
    server_name _;

    root /var/lib/nginx/html;
    index index.html;

    include /etc/nginx/admin-ui-location.conf;
}
