[tool.poetry]
name = "docs"
version = "5.11.0"
description = "Gluu Flex Documentation"
authors = [ "moabu <47318409+moabu@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pymdown-extensions = "^11.0"
pyyaml = "^6.0.0"
click = "^8.1.0"
jinja2 = "^3.1.0"
markdown = "^3.6"
pygments = "^2.18.0"
zensical = "^0.0.67"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"