import { makeStyles } from 'tss-react/mui'
import customColors from '@/customColors'
import { fontFamily, fontWeights, fontSizes, letterSpacing, lineHeights } from '@/styles/fonts'

interface StylesParams {
  isDark: boolean
}

export const useStyles = makeStyles<StylesParams>()((_theme, { isDark }) => ({
  modalContainer: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: isDark ? customColors.darkCardBg : customColors.white,
    borderRadius: '16px',
    border: isDark ? `1.5px solid ${customColors.darkBorderAccent}` : 'none',
    boxShadow: isDark ? 'none' : `0px 4px 11px 0px ${customColors.shadowLight}`,
    width: '1007px',
    height: '434px',
    zIndex: 1050,
    padding: 0,
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: customColors.modalOverlay,
    zIndex: 1040,
  },
  title: {
    fontFamily,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes['3xl'],
    lineHeight: '45px',
    color: isDark ? customColors.white : customColors.primaryDark,
    marginTop: '51px',
    marginBottom: '24px',
    marginLeft: '50px',
    marginRight: '50px',
    paddingLeft: 0,
    textAlign: 'left',
    width: 'calc(100% - 100px)',
    maxWidth: '100%',
    position: 'relative',
    zIndex: 1,
    wordWrap: 'break-word',
    overflowWrap: 'break-word',
  },
  closeButton: {
    'position': 'absolute',
    'top': '12px',
    'right': '12px',
    'width': '32px',
    'height': '32px',
    'padding': 0,
    'border': 'none',
    'background': 'transparent',
    'cursor': 'pointer',
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'color': isDark ? customColors.white : customColors.primaryDark,
    '&:hover': {
      opacity: 0.8,
    },
  },
  textareaContainer: {
    position: 'absolute',
    top: '123px',
    left: '50%',
    transform: 'translateX(-50%)',
    width: '898px',
    height: '161px',
    backgroundColor: isDark ? customColors.infoBoxBgDark : customColors.lightBackground,
    border: isDark
      ? `1px solid ${customColors.infoBoxBorderDark}`
      : `1px solid ${customColors.borderInput}`,
    borderRadius: '6px',
    padding: 0,
    boxSizing: 'border-box',
    marginBottom: 0,
  },
  textarea: {
    'width': '100%',
    'height': '100%',
    'padding': '14px 21px',
    'backgroundColor': 'transparent',
    'border': 'none',
    'borderRadius': '6px',
    fontFamily,
    'fontSize': fontSizes.base,
    'fontWeight': fontWeights.medium,
    'lineHeight': lineHeights.relaxed,
    'color': isDark ? customColors.white : customColors.primaryDark,
    'resize': 'none',
    'outline': 'none',
    'boxSizing': 'border-box',
    '&::placeholder': {
      color: isDark ? customColors.textMutedDark : customColors.textSecondary,
      opacity: 1,
    },
  },
  errorMessage: {
    position: 'absolute',
    top: '286px',
    left: '50%',
    transform: 'translateX(-50%)',
    width: '898px',
    fontFamily,
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.base,
    lineHeight: lineHeights.relaxed,
    color: customColors.statusInactive,
    margin: 0,
    marginTop: '2px',
    zIndex: 2,
  },
  yesButton: {
    'position': 'absolute',
    'bottom': '54px',
    'left': '50px',
    'backgroundColor': customColors.statusActive,
    'color': customColors.white,
    'border': 'none',
    'borderRadius': '6px',
    'padding': '10px 28px',
    'height': '40px',
    fontFamily,
    'fontSize': fontSizes.base,
    'fontWeight': fontWeights.bold,
    'letterSpacing': letterSpacing.wide,
    'lineHeight': lineHeights.relaxed,
    'cursor': 'pointer',
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'transition': 'opacity 0.2s ease',
    'zIndex': 3,
    '&:hover': {
      opacity: 0.9,
    },
    '&:disabled': {
      opacity: 0.6,
      cursor: 'not-allowed',
    },
  },
}))
