export const SPACING = {
  PAGE: 24,
  CONTENT_PADDING: 40,
  SECTION_GAP: 24,
  CARD_GAP: 24,
  CARD_PADDING: 24,
  CARD_CONTENT_GAP: 8,
} as const

export const BORDER_RADIUS = {
  DEFAULT: 16,
  LARGE: 24,
  MEDIUM: 14,
  SMALL: 5,
  CIRCLE: '50%',
  THIN: '1.5px',
} as const

export const GRADIENT_POSITION = {
  TOP_RIGHT: 'top right',
  TOP_LEFT: 'top left',
  BOTTOM_RIGHT: 'bottom right',
  BOTTOM_LEFT: 'bottom left',
  CENTER: 'center',
} as const

export const ELLIPSE_SIZE = '200% 160%'

export const CEDARLING_CONFIG_SPACING = {
  ALERT_TO_INPUT: 30,
  LABEL_MB: 7,
  INPUT_HEIGHT: 52,
  INPUT_TO_RADIO: 44,
  RADIO_LABEL_MB: 8,
  HELPER_MT: 10,
  BUTTONS_MT: 50,
  ALERT_PADDING_TOP: 22,
  ALERT_PADDING_BOTTOM: 20,
  ALERT_PADDING_LEFT: 56,
  ALERT_PADDING_RIGHT: 24,
  ALERT_ICON_LEFT: 25,
  ALERT_ICON_TOP: 22,
} as const

export const MAPPING_SPACING = {
  PAGE_PADDING_TOP: 53,
  ALERT_TO_CARD: 24,
  CARD_PADDING: 33,
  CARD_HEADER_HEIGHT: 73,
  CARD_BORDER_RADIUS: 16,
  CARD_MARGIN_BOTTOM: 16,
  PERMISSION_ROW_GAP: 20,
  PERMISSION_ITEM_GAP: 30,
  CHECKBOX_SIZE: 22,
  CHECKBOX_LABEL_GAP: 9,
  CHECKBOX_BORDER_RADIUS: 5,
  CHECKBOX_BORDER_WIDTH: 2,
  CHECK_ICON_SIZE: 14,
  INFO_ALERT_PADDING_VERTICAL: 16,
  INFO_ALERT_PADDING_HORIZONTAL: 24,
  INFO_ALERT_GAP: 16,
  INFO_ALERT_BORDER_RADIUS: 6,
  INFO_ICON_SIZE: 24,
  CONTENT_PADDING_TOP: 27,
} as const
