name: Test Linux installer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "flex-linux-setup/**"
  pull_request:
    branches:
      - main
    paths:
      - "flex-linux-setup/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        # add '"pgsql" when supported
        persistence-backends: ["MYSQL"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python3
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test Flex monolith demo
      run: |
        
        sudo apt-get update
        sudo python3 -m pip install --upgrade pip
        sudo pip3 install setuptools --upgrade
        sudo pip3 install dockerfile-parse
        python3 -c "from dockerfile_parse import DockerfileParser ; dfparser = DockerfileParser('./docker-flex-monolith') ; dfparser.envs['FLEX_SOURCE_VERSION'] = '${{ github.sha }}'"
        ip=$(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
        csudo hmod u+x automation/startflexmonolithdemo.sh
        sudo bash ./automation/startflexmonolithdemo.sh demoexample.gluu.org ${{ matrix.persistence-backends }} $ip true
